apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  path: './kubernetes/home.vijayakumar.xyz/core/metallb/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-ip-pool
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 5m
  path: './kubernetes/home.vijayakumar.xyz/core/metallb/ip-pool/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-ip-pool
  interval: 5m
  path: './kubernetes/home.vijayakumar.xyz/core/kube-vip/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-vip
  interval: 5m
  path: './kubernetes/home.vijayakumar.xyz/core/traefik/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: './kubernetes/home.vijayakumar.xyz/core/cert-manager/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: './kubernetes/home.vijayakumar.xyz/core/intel-device-plugins/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: './kubernetes/home.vijayakumar.xyz/core/longhorn/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: smb
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: './kubernetes/home.vijayakumar.xyz/core/smb/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
