---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 60m0s
  timeout: 30m0s
  retryInterval: 2m0s
  path: ./kubernetes/home.vijayakumar.xyz/core/metallb/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-ip-pool
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 60m0s
  timeout: 30m0s
  retryInterval: 2m0s
  path: ./kubernetes/home.vijayakumar.xyz/core/metallb/ip-pool/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-ip-pool
  interval: 60m0s
  timeout: 30m0s
  retryInterval: 2m0s
  path: ./kubernetes/home.vijayakumar.xyz/core/kube-vip/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-vip
  interval: 60m0s
  timeout: 30m0s
  retryInterval: 2m0s
  path: ./kubernetes/home.vijayakumar.xyz/core/traefik/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-vip
  interval: 60m0s
  timeout: 30m0s
  retryInterval: 2m0s
  targetNamespace: tailscale
  path: ./kubernetes/home.vijayakumar.xyz/core/tailscale
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 60m0s
  timeout: 30m0s
  retryInterval: 2m0s
  path: ./kubernetes/home.vijayakumar.xyz/core/cert-manager/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 60m0s
  timeout: 30m0s
  retryInterval: 2m0s
  path: ./kubernetes/home.vijayakumar.xyz/core/cert-manager/certificates/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins
  namespace: flux-system
spec:
  dependsOn:
    - name: certificates
  interval: 60m0s
  timeout: 30m0s
  retryInterval: 2m0s
  path: ./kubernetes/home.vijayakumar.xyz/core/intel-device-plugins/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 60m0s
  timeout: 30m0s
  retryInterval: 2m0s
  path: ./kubernetes/home.vijayakumar.xyz/core/longhorn/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  interval: 60m0s
  timeout: 30m0s
  retryInterval: 2m0s
  targetNamespace: cnpg-system
  path: ./kubernetes/home.vijayakumar.xyz/core/cnpg/
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  dependsOn:
    - name: cnpg
  interval: 5m
  path: ./kubernetes/home.vijayakumar.xyz/core/authentik/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: smb
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: traefik
#   interval: 60m0s
#   timeout: 30m0s
#   retryInterval: 2m0s
#   path: './kubernetes/home.vijayakumar.xyz/core/smb/'
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-keys
