apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: './sealed-secrets/controller.yaml'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets
  interval: 5m
  path: './metallb/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-ip-pool
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 5m
  path: './metallb/ipAddressPool.yaml'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-ip-pool
  interval: 5m
  path: './kube-vip/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-vip
  interval: 5m
  path: './traefik/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: './cert-manager/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: './intel-device-plugins/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: './longhorn/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: smb
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: './smb/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
