apiVersion: v1
kind: Secret
metadata:
    name: infisical-auth-credentials
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:8HvoTuicOcGr+QEnKjww7sv4qmOx1jNhA8+p80YoYE9VlIWS,iv:EBdEF3jGJXIVdjfe7ea93gVsjMGEZcsDlXxsiuV83fc=,tag:vmQ2L14/b/Gug6zsDM1P0Q==,type:str]
    clientSecret: ENC[AES256_GCM,data:B/nn2soppAla8PNqLdw/+hLtL3vzh8kEI8kSFwuemNtZg8k2eA/CEq2DOT0ck+fgGC4riuozeWGA0jFIOZoLbg==,iv:DrPZcb58BN8Wx1EDkhwowvQ+Ud7LF0v3wycy4QyOhwk=,tag:vnFT4+0/fl7OjTj6pge1jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTXhESVVPYmJqdGljUFNJ
            dmVVUTZtM3BGTDZ5dGFtTVphM016MmpSTXpJCjlocld0NXhxbzc1aWVOV2ZDMzIx
            MGlPdHIyeEQ0dXZUUTJCRUdNOG5EWFEKLS0tIFk2OFYvNGRRWlpFckwvVjkweFNL
            SUwwZThaYXJrOTBsMC8yUVdEenVLUGsKnCINX95IxsoTJFB8cA+kJg0JBzW5PKet
            TuwE9uz3ahevoymsWw9nUGVva0rt6yDTZBY6mNHq5+2zDMuaoYLn3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T18:06:37Z"
    mac: ENC[AES256_GCM,data:XrR1qJ0Tkn3xvah+D5Xfi9vYjqnp4snae0xrjQYazB7KGeRb/8cIiZ9k7w8ggCIKfS/alE4Vf1miWm4SH/Nk8VA//vgMz8fGSLvOYmFg4xcW/UEdwk0Z5Vaw5M3U68G0Dv8J2XOIiiu8l2JxDacGp+/UIAVWk0uZUuSiKqqJ6Ys=,iv:QCU8vDGyhg1RPC+kgZqV3Llj1N+P/NCitTaD0+6q+Zk=,tag:oXDdtspAB2yJtOoUmheg7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
