---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: gitlab-secret
    template:
      data:
        smtp_password: "{{ .smtp_password }}"
        object_store_connection: |
            provider: AWS
            region: us-east-1
            aws_access_key_id: {{ .object_store_access_key }}
            aws_secret_access_key: {{ .object_store_secret_key }}
            endpoint: {{ .object_store_endpoint }}
            path_style: true
        registry_storage_config: |
            s3:
              bucket: gitlab
              accesskey: {{ .object_store_access_key }}
              secretkey: {{ .object_store_secret_key }}
              region: us-east-1
              regionendpoint: {{ .object_store_endpoint }}
              v4auth: true
  dataFrom:
    - extract:
        key: gitlab
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: gitlab-db
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres-pguser-gitlab
