# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: gitlab
      version: 9.10.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    global:
      edition: ce
      hosts:
        domain: ${CLUSTER_DOMAIN}
        https: true
        externalIP: ${NODE_IP}

      smtp:
        enabled: true
        address: smtp.purelymail.com
        port: 587
        user_name: noreply@${LAB_DOMAIN}
        password:
          secret: gitlab-secret
          key: smtp_password
      email:
        from: noreply@${LAB_DOMAIN}
        display_name: VJLAB
        reply_to: noreply@${LAB_DOMAIN}
        subject_suffix: " | VJLAB"

      psql:
        host: postgres-primary.database.svc
        port: 5432
        username: gitlab
        database: gitlab
        password:
          secret: gitlab-db
          key: password

      gatewayApi:
        enabled: true
        installEnvoy: false
        class:
          name: "envoy"
        httpToHttpsRedirect: true

      minio:
        enabled: false
      appConfig:
        object_store:
          enabled: true
          connection:
            secret: gitlab-secret
            key: object_store_connection
        lfs:
          bucket: "gitlab/lfs"
        artifacts:
          bucket: "gitlab/artifacts"
        uploads:
          bucket: "gitlab/uploads"
        packages:
          bucket: "gitlab/packages"
        externalDiffs:
          bucket: "gitlab/external-diffs"
        terraformState:
          bucket: "gitlab/terraform-state"
        ciSecureFiles:
          bucket: "gitlab/ci-secure-files"
        dependencyProxy:
          bucket: "gitlab/dependency-proxy"
        backups:
          bucket: "gitlab/backups"
          tmpBucket: "gitlab/tmpbackups"

    registry:
      bucket: "gitlab/registry"
      storage:
        secret: gitlab-secret
        key: registry_storage_config

    gitlab-runner:
      install: true

    redis:
      persistence:
        storageClass: openebs-zfs

    gitlab:
      webservice:
        resources:
          requests:
            cpu: 10m
            memory: 120Mi
      sidekiq:
        resources:
          requests:
            cpu: 10m
            memory: 120Mi
      gitaly:
        persistence:
          storageClass: openebs-zfs
        resources:
          requests:
            cpu: 10m
            memory: 120Mi
      kas:
        resources:
          requests:
            cpu: 10m
            memory: 120Mi

    postgresql:
      install: false
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    certmanager:
      installCRDs: false
    installCertmanager: false
    certmanager-issuer:
      email: ${EMAIL}
