pocket-id: cd /app && su-exec "$PUID:$PGID" /app/pocket-id
backup: echo "1 * * * * /restic.sh" > /crontab && su-exec "$PUID:$PGID" supercronic /crontab
cf_tunnel: su-exec "$PUID:$PGID" cloudflared tunnel --no-autoupdate run --token "$CF_TOKEN"