---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2025.2.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: authentik-secret, authentik-db-secret
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: authentik-secret
        - secretRef:
            name: authentik-db-secret
      volumeMounts:
        - mountPath: /media
          name: authentik-media
        - mountPath: /web/dist/custom.css
          name: custom-css
          subPath: custom.css
      volumes:
        - name: authentik-media
          nfs:
            server: ${NFS_STORAGE_SERVER}
            path: /mnt/tank/Kubernetes/authentik
            readOnly: false
        - name: custom-css
          configMap:
            name: custom-css
            readOnly: true

    authentik:
      log_level: info
      error_reporting:
        enabled: false
      disable_update_check: true
      disable_startup_analytics: true
      redis:
        host: "dragonfly.database.svc.cluster.local"
        db: 1

    postgresql:
      enabled: false

    prometheus:
      rules:
        enabled: true

    redis:
      enabled: false

    server:
      podAnnotations:
        secret.reloader.stakater.com/reload:
      autoscaling:
        enabled: true
        minReplicas: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - auth.${CLUSTER_DOMAIN}
        rules:
          - host: auth.${CLUSTER_DOMAIN}
            http:
              paths:
                - path: /
                  pathType: Prefix

      metrics:
        prometheus:
          serviceMonitor:
            enabled: true

    worker:
      autoscaling:
        enabled: true
        minReplicas: 1
