---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qbittorrent
  name: qbittorrent
  namespace: media
spec:
  ports:
    - name: web-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: web-udp
      port: 8080
      protocol: UDP
      targetPort: 8080
    - name: torrent-tcp
      port: 6881
      protocol: TCP
      targetPort: 6881
    - name: torrent-udp
      port: 6881
      protocol: UDP
      targetPort: 6881
  selector:
    app: qbittorrent
  type: ClusterIP
  clusterIP: 10.43.157.103
