---
- one:
    - Navidrome:
        icon: navidrome.png
        description: Personal Music Streaming Service
        href: "{{HOMEPAGE_VAR_NAVIDROME_URL}}"
    - Immich:
        icon: immich.png
        description: Google photos alternative
        href: "{{HOMEPAGE_VAR_IMMICH_URL}}"
        widget:
          type: immich
          fields: [photos, videos, storage]
          url: "{{HOMEPAGE_VAR_IMMICH_URL}}"
          key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
          version: 2
    - Plex:
        icon: plex.png
        description: Self-hosted media streaming system
        href: "{{HOMEPAGE_VAR_PLEX_URL}}"
        widget:
          type: plex
          url: "{{HOMEPAGE_VAR_PLEX_URL}}"
          key: "{{HOMEPAGE_VAR_PLEX_API_TOKEN}}"
    - Tautulli:
        icon: tautulli.png
        description: A Python based monitoring and tracking tool for Plex Media Server.
        href: "{{HOMEPAGE_VAR_TAUTULLI_URL}}"
        widget:
          type: tautulli
          url: "{{HOMEPAGE_VAR_TAUTULLI_URL}}"
          key: "{{HOMEPAGE_VAR_TAUTULLI_API_KEY}}"
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - Tank:
        icon: truenas.png
        description: Media requesting system
        href: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
        widget:
          type: truenas
          url: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
          key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}"
          enablePools: true # optional, defaults to false
- two:
    - Linkding:
        icon: linkding.png
        description: Bookmarks manager
        href: "{{HOMEPAGE_VAR_LINKDING_URL}}"
    - Adguard Home:
        icon: adguard-home.png
        description: Dns ad blocker
        href: "{{HOMEPAGE_VAR_ADGUARD_URL}}"
        widget:
          type: adguard
          url: "{{HOMEPAGE_VAR_ADGUARD_URL}}"
          username: "{{HOMEPAGE_VAR_ADGUARD_USERNAME}}"
          password: "{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}"
    - Gatusfly:
        icon: gatus.png
        description: self-hosted monitoring tool
        href: "{{HOMEPAGE_VAR_GATUSFLY_URL}}"
        widget:
          type: gatus
          url: "{{HOMEPAGE_VAR_GATUSFLY_URL}}"
    - QBittorrent:
        icon: qbittorrent.png
        description: Torrent downloader
        href: "{{HOMEPAGE_VAR_QBITTORRENT_URL}}"
        widget:
          type: qbittorrent
          url: "{{HOMEPAGE_VAR_QBITTORRENT_URL}}"
          username: "{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}"
          password: "{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}"
    - SABnzbd:
        icon: sabnzbd.png
        description: NZB downloader
        href: "{{HOMEPAGE_VAR_SABNZBD_URL}}"
        widget:
          type: sabnzbd
          url: http://sabnzbd.downloads.svc:8080
          key: "{{HOMEPAGE_VAR_SABNZBD_API_KEY}}"
- three:
    - Vaultwarden:
        icon: bitwarden.png
        description: Password manager
        href: "{{HOMEPAGE_VAR_VAULTWARDEN_URL}}"
    - Sonarr:
        icon: sonarr.png
        description: Series management
        href: "{{HOMEPAGE_VAR_SONARR_URL}}"
        widget:
          type: sonarr
          url: http://sonarr.downloads.svc:8989
          key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
    - Radarr:
        icon: radarr.png
        description: Movie management
        href: "{{HOMEPAGE_VAR_RADARR_URL}}"
        widget:
          type: radarr
          url: http://radarr.downloads.svc:7878
          key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
    - Prowlarr:
        icon: prowlarr.png
        description: Index management
        href: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
        widget:
          type: prowlarr
          url: http://prowlarr.downloads.svc:9696
          key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
    - Bazarr:
        icon: bazarr.png
        description: Subtittle management
        href: "{{HOMEPAGE_VAR_BAZARR_URL}}"
        widget:
          type: bazarr
          url: http://bazarr.downloads.svc:6767
          key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"
- four:
    - IT Tools:
        icon: it-tools-light.png
        description: Handy tools for devs
        href: "{{HOMEPAGE_VAR_ITTOOLS_URL}}"
    - Linkwarden:
        icon: linkwarden.png
        description: Self-hosted bookmark manager
        href: "{{HOMEPAGE_VAR_LINKWARDEN_URL}}"
        widget:
          type: linkwarden
          url: http://linkwarden.selfhosted.svc:3000
          key: "{{HOMEPAGE_VAR_LINKWARDEN_API_KEY}}"
    - Uptime Kuma:
        icon: uptime-kuma.png
        description: self-hosted monitoring tool
        href: "{{HOMEPAGE_VAR_UPTIME_URL}}"
        widget:
          type: uptimekuma
          url: http://uptime.monitoring.svc:3001
          key: "{{HOMEPAGE_VAR_UPTIME_API_KEY}}"
          slug: all
    - Speedtest Tracker:
        icon: speedtest-tracker.png
        description: internet connection monitoring tool
        href: "{{HOMEPAGE_VAR_SPEEDTEST_URL}}"
        widget:
          type: speedtest
          url: http://speedtest.network.svc
          key: "{{HOMEPAGE_VAR_SPEEDTEST_API_KEY}}"
          version: 2
    - Proxmox:
        icon: proxmox.png
        description: Subtittle management
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"
