---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: kopiur-idrive-e2
spec:
  externalSecretName: kopiur-idrive-e2-secret
  externalSecretSpec:
    dataFrom:
      - extract:
          key: kopiur-template
    refreshInterval: 12h
    secretStoreRef:
      kind: ClusterSecretStore
      name: bao
    target:
      creationPolicy: Owner
      name: kopiur-idrive-e2-secret
      template:
        data:
          AWS_ACCESS_KEY_ID: "{{ .IDRIVE_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "{{ .IDRIVE_AWS_SECRET_ACCESS_KEY }}"
          KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
  namespaceSelectors:
    - matchLabels: {}
  refreshTime: 1h
