# fly.toml app configuration file generated for gatusfly on 2023-08-01T12:28:26+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gatusfly'
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"
swap_size_mb = 1024

[build]
dockerfile = "Dockerfile"

[env]
TZ = "Asia/Kolkata"
GATUS_LOG_LEVEL = "INFO"
GATUS_CONFIG_PATH = "/config"

[[mounts]]
source = 'gatus_data'
destination = '/data'
snapshot_retention = 60

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
