# The server configuration file version.
version = "2"

bindaddress = "0.0.0.0:8443"
ldapbindaddress = "0.0.0.0:3636"

db_fs_type = "zfs"
db_path = "/data/kanidm.db"
tls_chain = "/certs/tls.crt"
tls_key = "/certs/tls.key"
adminbindpath = "/var/run/kanidmd.sock"

domain = "idm.${LAB_DOMAIN}"
origin = "https://idm.${LAB_DOMAIN}"

[http_client_address_info]
x-forward-for = ["10.244.0.0/16", "10.96.0.0/12"]

[online_backup]
path = "/data/backups/"
schedule = "30 00 * * *"
