---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-server
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  values:
    defaultPodOptions:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - immich-server
              topologyKey: 'kubernetes.io/hostname'
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      immich-server:
        annotations:
          reloader.stakater.com/auto: 'true'
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.7.5
            env:
              IMMICH_CONFIG_FILE: /config/immich.config.json
              IMMICH_WORKERS_INCLUDE: api
            envFrom:
              - secretRef:
                  name: immich-env
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 200m
              limits:
                cpu: 3000m
                gpu.intel.com/i915: '1'
    persistence:
      config:
        enabled: true
        type: secret
        name: immich-config-secret
        globalMounts:
          - path: /config
      media:
        type: nfs
        path: /mnt/tank/Kubernetes/Apps/immich
        server: tank
        globalMounts:
          - path: /usr/src/app/upload
    route:
      app:
        hostnames:
          - immich.${CLUSTER_DOMAIN}
        parentRefs:
          - name: envoy
            namespace: network
    service:
      immich-server:
        controller: immich-server
        ports:
          http:
            port: 2283
