apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-sops-credentials
  namespace: monitors
data:
  admin-password: ENC[AES256_GCM,data:EcRe60/lE10jZIU28+Y7aA==,iv:5nH97SgBpzTxjaJyb4Zt4VNvfRX3skvNpVEXVWdszb8=,tag:NFElp+oBv/DaQbxvz4XJSA==,type:str]
  admin-user: ENC[AES256_GCM,data:D23965BMc8E=,iv:MXXUiK0oX5YPAgPZ+tdAK7jd9BZub8SGEl57ye00/Sw=,tag:EeKuCID/L5JGv4ylEpbUMw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19654hupmjy08ge0xu43mynjca5wmrd3kmlt7wsja582waanvf4uqvv65ya
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUmI3Q3BSMzBuNnJPaEd2
        d1VEQlRWa0JiTkMrb0hJeGtvU2NnRXNsV1N3CkdGR3ZlU3FNRGpVTnlJQXdxSXRL
        TXhpV1lhMzZCZmI5RDU2OFpOV0J2VHcKLS0tIDhMRXVrNjQxbmp3K3ByZjdOQ2xr
        SmNWaDJHOXd1UWlXVDhnWWp0Y1pFV0UKbLonkTCcilB/2Z5kEu59JmZloAASlMV6
        i6RyKL/UTtdWe5ThPQ1hTd4nDv+xMEIp5K2/bvWAZK/qTIrgSLnK0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-11-02T20:10:38Z'
  mac: ENC[AES256_GCM,data:OWcNr7Ygjfl8e9NUvnzHnX58FZAdjmqFytxlPoZp78grjzcd0pIo4FOyV23frd030xqNoGRL+aIumGvxx2mRwmYb2Uth5u1S4TUM8XWy5vx/XuaIXmAO5UxHVuRtXezlLXBYRtuMCFuei6qF3bgxbBJY+xqIVN1+gohuH7E6BCE=,iv:+zTTmTwGOYC6VltFC1PK1t+XL3/1WIpaTpfeB3fdZZs=,tag:XlPyO94nUrtBV1t5gTIB1Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
