apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitors
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    admin-user: ENC[AES256_GCM,data:yKOT+FI=,iv:m6Ta8ehnf4JkzKKYvSpa9k71YyNQHeHJlS93doBMWFE=,tag:Y03gdEMz4bmJaund2DcgWw==,type:str]
    admin-password: ENC[AES256_GCM,data:/qhBqpjX+x8iOKI=,iv:Mw2xPOP1X4BYVLmq+M8ChQ+XXDE/r7OUfMg06GoWQ3s=,tag:FLji/OL+RSiLb4TeyhXyxw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeTNJNHdWeTc0MXd4a1NZ
            Y29kUjFzZisrczZIaGpmMTJLMFdxNWEzMVNrCkdRZjd3a3Axa3VyMU9BcDArbU1q
            bVhVTUxISFBJOHdEVTE1NWNmbXZEdHcKLS0tIFlIK0QvdGpKUTFuMHpzTVU0TDBk
            V3lFRTAzOTFmaWtCbWFLMVNBTFhCUE0Ku/rTK+0ewQhkFRNYL89D8ID+TOG6yT9S
            VsUQebQ5PH2LfXOkWdu4j092jfW/vCC6mlT17jAMQU4nuco3B/lXFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T15:43:16Z"
    mac: ENC[AES256_GCM,data:B0HQ6R4KyMC3DrFMtY0CwU8hMF8SXmNTHFO8MnyyXNfqALQO1bPw75a5Fkuw1wLRq0d5CSyL45ViwS/Zf4ETEyJ2cDYqmM9ZS8xPttVzz+7klw1c9csoazV9rk0Pp/XPx/hezJpSRr3Okj18ClrghYoPCN7jfLETVFC1bMjDdmg=,iv:OnvHin9Y8hOcFvL/hYSQl6hyGuBowQTjy1seoCcKJhw=,tag:3crJFbH2+nLz1pPRyRPSOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
