apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitors
    labels:
        encrypted-by: sops
        encryption-method: age
data:
    admin-user: ENC[AES256_GCM,data:UJNHRGI=,iv:BmTlKe3/99clA5gRu1fN2+IHiUdZnLsJKeEAeuUksPg=,tag:t7sbQwIwLgpdLQ6dHBuigg==,type:str]
    admin-password: ENC[AES256_GCM,data:aYuIbb2Ozxc+3MU=,iv:UW2bZFAudrx3O5zjsOLjfS48TEfPO1p1+BfGAHB5+So=,tag:iDXgGIrUF01HeTLxu8NLQw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeTNJNHdWeTc0MXd4a1NZ
            Y29kUjFzZisrczZIaGpmMTJLMFdxNWEzMVNrCkdRZjd3a3Axa3VyMU9BcDArbU1q
            bVhVTUxISFBJOHdEVTE1NWNmbXZEdHcKLS0tIFlIK0QvdGpKUTFuMHpzTVU0TDBk
            V3lFRTAzOTFmaWtCbWFLMVNBTFhCUE0Ku/rTK+0ewQhkFRNYL89D8ID+TOG6yT9S
            VsUQebQ5PH2LfXOkWdu4j092jfW/vCC6mlT17jAMQU4nuco3B/lXFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T15:16:32Z"
    mac: ENC[AES256_GCM,data:XSYeItr/A9BdU+084MWhSwlleUL14FKGODro/CBUTgkh9jcsD+MKEMw4uI3tY8n0UnCJcNHI8zxEE9Fpe1fnZIz9JdSCS3ZEMogM8RmH7rGIriXSZQG1ugRtx63RfXWZi57AiIg29xEGiA9RNC0HmxduN3M5IX0Qf6YIlqhrNts=,iv:aOiVLmjuwTUJg5eupYpPX4pn+pDYvieVgnoigR8AMpE=,tag:F/H1Ld6sZiYDqxa8kmoU1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
