---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: speedtest-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: speedtest-secret
    template:
      type: Opaque
      data:
        APP_KEY: "{{ .speedtest_api_key }}"
  dataFrom:
    - extract:
        key: speedtest
      rewrite:
        - regexp:
            source: "(.*)"
            target: "speedtest_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: speedtest-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: speedtest-db
    template:
      type: Opaque
      data:
        DB_CONNECTION: "pgsql"
        DB_HOST: "{{ .host }}"
        DB_PORT: "{{ .port }}"
        DB_DATABASE: "{{ .dbname }}"
        DB_USERNAME: "{{ .user }}"
        DB_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres-pguser-speedtest
