---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speedtest-secret
spec:
  dataFrom:
    - extract:
        key: speedtest
      rewrite:
        - regexp:
            source: "(.*)"
            target: "speedtest_$1"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: speedtest-secret
    template:
      data:
        APP_KEY: "{{ .speedtest_api_key }}"
      type: Opaque
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speedtest-db
spec:
  dataFrom:
    - extract:
        key: postgres-pguser-speedtest
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: speedtest-db
    template:
      data:
        DB_CONNECTION: "pgsql"
        DB_DATABASE: "{{ .dbname }}"
        DB_HOST: "{{ .host }}"
        DB_PASSWORD: "{{ .password }}"
        DB_PORT: "{{ .port }}"
        DB_USERNAME: "{{ .user }}"
      type: Opaque
