apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
  labels:
    encrypted-by: sops
    encryption-method: age
data:
  cloudflare-token: ENC[AES256_GCM,data:Pec6dxjAjzo5DWZbb7dCtOOPaFLLesjuZNvN5X33+9Im8iy12jiITYoM/VRlXWydt3Aol/64jCk=,iv:XS52TvGIjkdi1aNK+WvGdouN7Mkcw78KpNDAMhQeRZo=,tag:1zELUU+0F9J0m3Rz9NXfZA==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19654hupmjy08ge0xu43mynjca5wmrd3kmlt7wsja582waanvf4uqvv65ya
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bXZ5Vnl2dEtWaWdXYmVk
        ZGs3cXh2R3F6c3p3cFVGcUcyUDh4bXd3ekZNCmVDSWxnMzExTURhUllFQUZNQUFC
        OVh4Y0pnM3U2S05HZlhIVVdCVy9lV28KLS0tIGZxbENoSnpUcDRVTGcwTU04MEcx
        N0tIY241OEd3cEpjbERDYlNDV2ljbUUKbszjT930pD+y1isZmrszLy8POoL5xdi0
        ZHPe1u79PDefDzXPp/1m93EFLsJRQ728fnBoelLX+IJyGW43FO0Vcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-11-02T20:40:36Z'
  mac: ENC[AES256_GCM,data:fZL2m7ciWIk21TpqUTC4Bv7Y92rZKrKJPRwojtCHJ6HVsD83PFCw+VCGRQD5CYy1b0yIrrlc/m2YyqtxvPUYXmbI9TsEGDJVjmSi2qV9143hZ30JIUs9JJw3FMreLX02tJ+VONl1PDwPuwcTF9YK//BRnWtBb7KhYhE11UqUWxk=,iv:jWI298pTqlnl3Z4jqmM5IXb1jS3STQklWR3ZCYuT6Pg=,tag:gYU1eW+OLh1Ox0cHIgnyCg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
