apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
data:
  cloudflare-token: ENC[AES256_GCM,data:Lg3r19kP8wi+86E8U3zdg1afUrkw/8LaovxJV+MGcb2HNyixIg==,iv:dwcrIbBtsJE/GUo16PRs4R4d/dojZNh8Lezhruh2LM4=,tag:SsBOtaibABtQ4A+Vlfs5Og==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYnhGOEN6d1ZyTzVOeWxO
        WHFKdDJpencxTlZQUjF3SzV4N1RDaW9iajBZCjI1cGk0K1dCemY1b21CdDRuclZ3
        RVRZbDE4YjJYcEVVN1lxSFNuQ3lZZTQKLS0tIDRGOTlBR1VrRUN6NEF0TmZBYXla
        Uk10VlgvSTlUVHFPTXpGL1VBN0FiL2cKheYhfgGwTePitnlfAA9HjlllVGlB1qQy
        KVy9lhN1xjZ3vmUcvVu2dI8w8yTyPr9cP6LWiR8i7BixyBKlkp6+fQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-11-30T14:22:55Z'
  mac: ENC[AES256_GCM,data:hFXussmLKGUPLi0wEx8nm2M4ADV3IWMhg6Q/CghtnKXNA10aRr+PsYMkNs9bLIsf9255GKrM42nFrmW8He80lEgxxHR7yHW8LPM1uw0ZuU+ZOcWbv6qIJgN797SkZZEQ/iNTW0CFxSbI+C0rlZyDXS4AOZr9P3Hl4X/GqCJfx+g=,iv:lElbJnxMSLPpOCDqPO6Y4mQwydDVmAiOTrRmife6V/w=,tag:sO+T4don9zVAYjncvAbcKw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
