apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
stringData:
    api_key: ENC[AES256_GCM,data:iM8wmbnxnxjzqVdw47v+tWgYnl3IPnmyOORBtGQBnzM=,iv:M61ccNPPPzdHJUTTsDRQXDbQerqpIC/equ2LWWG6DVM=,tag:uJhn9yYHy0KKyhoL66eJ9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2KzV1eU1SNWxIS1plTFNX
            WHhtaVlBY0RjUVZMcWVUWFU0REV6d3pXcnhZCkxrbjd2NGlkUjVsVHc2bW9haVZS
            c1dxUXdZeHZmWk84aUpJWjdDanFTYkEKLS0tIHJTdjQzdzRra2FWZm5kUDR5M3hD
            UzAvbnowWEl3eWRRanZlQ3F5d2h6aUEKS8NxVAezFA23CxchKN6/6/flkl48Xdzj
            exyBcRqbH10S67QA0OAq0ZtS2PHqj/lDkax6Gf1pCcXCZ4KkzorVVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T07:05:39Z"
    mac: ENC[AES256_GCM,data:/uYW1DPH6QZ66RFl0dojbTS3JSRPS3QXNaaBRytE6xMXanUrzVlva502ZK8pFbXjiSTpzDXIwRhltAJsBBD815FYjvIwDNfZZ4fY4/B8M0H1ItQJHXJL+5jO9mMES3ewAiVm+ItZWB+YnviFAuCw2ZqWLPWZIPxTMDvd08OSMYY=,iv:Dme28KpBjExeiGLWQ45zyNMI4LTHmP+2ic6d7yXToNc=,tag:iSpxwzuqTIcGi6P9fFyExw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
