apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:VDFAmOcx6W0t,iv:mDNV1te2ZFYZJjpK5J6jKKHpcDIc8H8KxkwmY5VlCYw=,tag:B8pRneGHiMXmqAXHyRwBhA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:0Gz5DBJTGKRA,iv:WS04qFguXngPw3Qbtoj97cs3C7QS+0PgRZLOTE3CptI=,tag:qn/b23RLCJ3D/1MDvFuFXQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:etYpfkntr8gYZGk9HrOh47T6pPeAoCvees9ZOWJsEHfPKzubGXJpX/4nE9zuehNl,iv:5g7e38l4RDkjCN5c7H9W0piJsYG/dE9EM9HiVeSusts=,tag:cCdIauwhJB2l/GEF7OD6nQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:PFudVcmJpFATKzSadWHgr1CjeF7iTR2UUKProIBYJYRTJqkCtT53Nq/FJpRfr24H,iv:/Bnbva8vX2eMuHyJWnpkMUtgY4O+RX39LDMTZ4cC7EI=,tag:IK4P4DlCNEEWnEX70b+Q7A==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:sil9TIPMheBm8A==,iv:nh840KOGvMNchttwD1RJuAAANUDZU1DyeKWqL72gdis=,tag:ZgPNqg4faV+xXmPwGK1zLA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:AnY/ojBGQe3n,iv:rvu2bSLZ5RsmiGz+wsuclZbRmbhFE0C2wDgYMFTglbQ=,tag:zYXKCdcLhg89mKF8gqq4gg==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:uiIOtZI3QXrh,iv:Y7LlQLWk9z9sdai+TXrxT1Kiwr15XVgIijuYy4Hu6XE=,tag:nIH9sygZOOxy0onWGeW+yA==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:HQpC07t/Y2d04gD1xUaWzxy1HvHQKHjTPUvuZfmSmsJhmsK9YHhdwnjYb38QdmT4Y9b05ZPyHcn/6egt2xV2Pk1cn94J6ajZNZ5cdMz6n2s=,iv:rdVHtFcKOvA8FxitUxx0gKIuuQX0ljP7Su9WAn9j5bI=,tag:hpvoDRyl9875xnoKhaY5Ug==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:AjO/9g==,iv:mbPvaHFRHhZviltGyJtOM+8X1MZdyI+rAuGxJvqRG+o=,tag:kQN5HK+vaNqwnYYyNM3E3w==,type:bool]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:dvzS72TxIotoSnewP00D,iv:oU29t0ttcgyyAkUPj7bJJZUxnn7OZZmu/0FwbQ9d2lY=,tag:zA0BwY81XIs/x7IJaBKXJg==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:N8xK,iv:NVFDUyeTZT5pgj/cb7Vhm8oMD9uJZPXIDOq/v4QElnA=,tag:ufDvVfgiRbfYTxe00XpLIA==,type:int]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:NLMhT5fa,iv:d6mqHocbSKwJNdaUNXnjzXuXBaFku5X6q7YWX/XbNtk=,tag:PoMO/N9cw8nngd8B75E49Q==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:DYxPkWU025NTq0/5x5bIf4axzeVaklIILhi08xZTqZlCK9Dk,iv:63dsH0sbB2QKOcl4n5nXf9B510RNsdjjy0sELTekpOw=,tag:nqpEW12VGSbA0mZsx/MUBg==,type:str]
    AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:toKvlw==,iv:CYVxhK6Fjzc4fDoUR8lP0Z1GwkG0pomdFVq+C2Tu2PY=,tag:CD1rJ2fxAtlkkyCoGy8/nQ==,type:bool]
    AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:9RZ3ETI=,iv:j1auOOgyilJj8unbWIraFLW/GgTWOXZaZ7AWgqWVqv0=,tag:FwNolEy1kL14ix8Isukpzw==,type:bool]
    AUTHENTIK_EMAIL__TIMEOUT: ENC[AES256_GCM,data:xeI=,iv:PbdO19ZWXz/LmEMCbZ7u77R2n/o5Zi7Y6V9JLx7fTLM=,tag:xI1fVvzedM61khAgAgUXEg==,type:int]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:F+nb1bbgWEaov/DSWezxOTIhPxc=,iv:a2uMOIdlo+zKfUH8iUqq57unbxABYft+osU43eTiUxk=,tag:B88CVNMSGtUdM3IvL/COTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19654hupmjy08ge0xu43mynjca5wmrd3kmlt7wsja582waanvf4uqvv65ya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTzFxbnFMTWhUM3h6NlRI
            ODQ0L2RqU1REQ0djcVcwMjBYOVZlZHVPUDI4CkgyQVI2VGpGOWVFdUZDYlppQkhk
            dVFwOWFlYWgyUGgrYmQ5MUtVQTl4Q00KLS0tIFJ3UTNLZjdnaE1XL0VoMDY5UExk
            V3I1RG5JVmEyNnhyVTVFa1RrYzZpN28Kp134UvX8godxPGxHzPF/swvFfmj/+w1B
            9JoNSt3UHJXYvQ3tnFJFbGr5MZ/fRQiwbpwW7r9ltoovtQhGaw3oFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T23:57:45Z"
    mac: ENC[AES256_GCM,data:fepYIq5gnPhCt4D7st/b7XF5OsQw4/RtNKOs1ECB9Sb86RxbM+ZT5xSjhrek4j/qt8MHgqJmtVWE9yKK13EIpAJx+RF6TgPLisjKlgiirG6ksnVQPd1sFa3pLZbTN8rDpswFkL8OGAe5HRHBZZ/QzchHIsubvjEM52v6ogaNdrs=,iv:bBkiKhTVHNbT7FeTjc/Si/kUTK7GfU8PlcKbqr6z7gU=,tag:PL1eRq2vmjAdtcWS8FPSGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
