apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:HQpC07t/Y2d04gD1xUaWzxy1HvHQKHjTPUvuZfmSmsJhmsK9YHhdwnjYb38QdmT4Y9b05ZPyHcn/6egt2xV2Pk1cn94J6ajZNZ5cdMz6n2s=,iv:rdVHtFcKOvA8FxitUxx0gKIuuQX0ljP7Su9WAn9j5bI=,tag:hpvoDRyl9875xnoKhaY5Ug==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:TsTyMA==,iv:sDf1Ie09id2nLKrFzN3FZrVcqZSPLPyVXrLT4tQLNJY=,tag:MS7o+ktlQYqHX4+/Ng8GlQ==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:dvzS72TxIotoSnewP00D,iv:oU29t0ttcgyyAkUPj7bJJZUxnn7OZZmu/0FwbQ9d2lY=,tag:zA0BwY81XIs/x7IJaBKXJg==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:4aVo,iv:bblfKpBW9AVsOY229scXNG1lCe4PlK3LVHw9cX0nqhM=,tag:FrZiQYxaxpPCgHtJTlK+/g==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:NLMhT5fa,iv:d6mqHocbSKwJNdaUNXnjzXuXBaFku5X6q7YWX/XbNtk=,tag:PoMO/N9cw8nngd8B75E49Q==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:DYxPkWU025NTq0/5x5bIf4axzeVaklIILhi08xZTqZlCK9Dk,iv:63dsH0sbB2QKOcl4n5nXf9B510RNsdjjy0sELTekpOw=,tag:nqpEW12VGSbA0mZsx/MUBg==,type:str]
    AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:10TqJQ==,iv:8vGf4E+UzXmbQivFXlIrreNiwY7jQIxmVHMO6F0aQ20=,tag:d00tD2agwFNY5/nAETgfyA==,type:str]
    AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:BEZHv1g=,iv:Pt3t2GGyaCOYg8obnUabaECCI4JRfB6ExsOPwDmzo1o=,tag:bBKVR1YHLvRcCVpO8KQguw==,type:str]
    AUTHENTIK_EMAIL__TIMEOUT: ENC[AES256_GCM,data:Gps=,iv:150vdHW4lH5Rvq4PS6cok8U2MxMg6FdxKvwvk+4e9Rw=,tag:13scJDy1Me6dLH8uHyVPsw==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:F+nb1bbgWEaov/DSWezxOTIhPxc=,iv:a2uMOIdlo+zKfUH8iUqq57unbxABYft+osU43eTiUxk=,tag:B88CVNMSGtUdM3IvL/COTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19654hupmjy08ge0xu43mynjca5wmrd3kmlt7wsja582waanvf4uqvv65ya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTzFxbnFMTWhUM3h6NlRI
            ODQ0L2RqU1REQ0djcVcwMjBYOVZlZHVPUDI4CkgyQVI2VGpGOWVFdUZDYlppQkhk
            dVFwOWFlYWgyUGgrYmQ5MUtVQTl4Q00KLS0tIFJ3UTNLZjdnaE1XL0VoMDY5UExk
            V3I1RG5JVmEyNnhyVTVFa1RrYzZpN28Kp134UvX8godxPGxHzPF/swvFfmj/+w1B
            9JoNSt3UHJXYvQ3tnFJFbGr5MZ/fRQiwbpwW7r9ltoovtQhGaw3oFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T06:34:15Z"
    mac: ENC[AES256_GCM,data:skDS7KPfjw8c+83R41fG5xE2V57vu2xdoqH6f+VhQo7KxAzv55Su9tPtbJNtLZTruZReIzi2udBjiP23i9BlGQEe8rSggLDM5YPWveGTz3SluL3U2VbQ440awoMSm0+xOIwt8cYfyn/HL928X4DGhA8XYmSABcsK0nnR2/39+0c=,iv:Ksp9wDPZMDolxOFCY83ElhPHCo/FBbzoYzTb718k+1k=,tag:Tp/JM23W2VRfVjng0isRYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
