apiVersion: v1
kind: Secret
metadata:
    name: immich-env
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:1qkuIcJhfADtEvDcM2ajU0+j8tLMK/A4ADo5Mrdf94xWsl9Ueys5qEGJDLZgEb8oEblJVyZKHmFjXJM+Gd1Vt9MSMD0gC4T7P5Z5CU5VVA5rhQui+y1Rd4KvBeH4CG/FbJo074p7D7IlcQ+Ldr0mwByFKNXRiBGmS+8bGLdwzKx74EdGGCE=,iv:3KMRujLE0UY7k8H+FkWsseDcKJt+f3uAC6boAqtD5Fc=,tag:PtaAHXzJ5xeMO+RfQmMlfw==,type:str]
    DB_VECTOR_EXTENSION: ENC[AES256_GCM,data:FjMrJo8TrTc=,iv:8CIGt/OCRhAr4Ui6aqSaHH/gdwXCDKn1KD/w0qK0BMU=,tag:TdBXPLi1trk0bKUhefS7sw==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:ieIfJU46qeAOGeIC9TV7eHWlw9UToC9AaPXa0F77jxKR1kSibK0/Ar8=,iv:A+Gv+0cSRIF7OXjv6rCOVHd7PP6Ih0Aq5XJI0zRDGyI=,tag:Gn+SDpG4yTpwU1eGSQfwJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcXVSZmVRNXkzYWlwaEhK
            TjFVaWhOVjRDVVg3L21oQjRqa21UVkczd1RRCk5QYnlKYUlzcCtYV3Z0eWp3TklQ
            ZGdGMnlzNnI0QWhxMXVTby9ScndnNjQKLS0tIEhvUCtoRXR1SmVlK2Y2d3dOOEFL
            VldidXZmMmNiV1BEQ2FWdHBwZDVBUWsK28Z2Am2rZNLlSJERQ1bnGqvrM3rmUhnH
            uHO2AYU9HLYFxsPirjqXSzI3RwCDNnwSLxgbwe8OyW/4ueoT8KG70w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-15T13:00:49Z"
    mac: ENC[AES256_GCM,data:162497UjVVDhMFBEWcNfHRoAKWiWJnfDCMzMtjoQ4u/7Eb9jku5JIMCE3m+bWxCwSEJaNLnSUAbFIQnzJWy2/MMARY38JKlg2C9xw1Bbyssy1RmVEQnF3wo+91fb5OLmi91687HwyczN++1H4IgBzXMsC7yQ8iHxxn3rw0ZhlDI=,iv:fM0Do9gG5W35jomqu5UUsZJqKG3cemRthr6IA2g/UjU=,tag:M/rtw+W6LCHbHvRszsK7GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
