---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name percona-postgres-secret
spec:
  dataFrom:
    - extract:
        key: percona-postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "percona_postgres_$1"
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: *name
    template:
      data:
        encryption.conf: |
          [global]
          repo2-cipher-pass={{ .percona_postgres_backup_encryption_cipher }}
        s3.conf: |
          [global]
          repo1-s3-key={{ .percona_postgres_wasabi_cpgo_access_id }}
          repo1-s3-key-secret={{ .percona_postgres_wasabi_cpgo_access_key }}
