# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name percona-postgres
spec:
  chart:
    spec:
      chart: pg-db
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: flux-system
      version: 3.0.0
  interval: 30m
  values:
    autoCreateUserSchema: true
    backups:
      pgbackrest:
        configuration:
          - secret:
              name: percona-postgres-secret
        global:
          archive-async: "y"
          archive-push-queue-max: 5GiB
          compress-level: "9"
          ## Wasabi
          #repo1-bundle: "y"
          #repo1-block: "y"
          #repo1-path: /percona-pgo
          #repo1-retention-full: "7" # days
          #repo1-retention-full-type: time
          #repo1-s3-uri-style: path
          compress-type: bz2
        jobs:
          ttlSecondsAfterFinished: 21600
        #restore:
        #  enabled: true
        manual:
          options: [--type=full]
          repoName: repo1
        metadata:
          labels:
            app.kubernetes.io/name: percona-postgres-backup
        repos:
          - name: repo1 # Wasabi
            s3:
              bucket: "luffy"
              endpoint: s3.ap-northeast-1.wasabisys.com
              region: "ap-northeast-1"
            schedules:
              differential: "0 1 * * 1-6" # Mon-Sat at 01:00
              full: "0 1 * * 0" # Sunday at 01:00
              incremental: "0 2-23 * * *" # Every hour except 01:00

    dataSource:
      pgbackrest:
        configuration:
          - secret:
              name: percona-postgres-secret
        global:
          archive-async: "y"
          archive-push-queue-max: 5GiB
          compress-level: "9"
          # Wasabi
          compress-type: bz2
          repo1-block: "y"
          repo1-bundle: "y"
          repo1-path: /crunchy-pgo
          repo1-retention-full: "7" # days
          repo1-retention-full-type: time
          repo1-s3-uri-style: path
        repo:
          name: "repo1"
          s3:
            bucket: "luffy"
            endpoint: s3.ap-northeast-1.wasabisys.com
            region: "ap-northeast-1"
      #pgbackrest:
      #  stanza: "db"
      #  configuration: *backupConfig
      #  global: *backupFlag
      #  repo:
      #    name: "repo1"
      #    s3: *r2
        stanza: "db"
    expose:
      annotations:
        lbipam.cilium.io/ips: 10.0.1.10

      type: LoadBalancer
    extensions:
      builtin:
        pg_audit: true
        pg_stat_monitor: true
        pg_stat_statements: true
        pgvector: true

    #   storage:
    #     type: s3
    #     bucket: pg-extensions
    #     region: eu-central-1
    #     endpoint: s3.eu-central-1.amazonaws.com
    #     secret:
    #       name: cluster1-extensions-secret
    #   builtin:
    #     pg_stat_monitor: true
    #     pg_stat_statements: false
    #     pg_audit: true
    #     pgvector: false
    #     pg_repack: false
    #   custom:
    #   - name: pg_cron
    #     version: 1.6.1
    image: perconalab/percona-postgresql-operator:2.7.0-ppg16-postgres
    instances:
      - dataVolumeClaimSpec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 50Gi
          storageClassName: openebs-hostpath
        metadata:
          labels:
            app.kubernetes.io/name: percona-postgres
        name: *name
        replicas: &replica 3
        topologySpreadConstraints:
          - labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: *name
                postgres-operator.crunchydata.com/data: postgres
                postgres-operator.crunchydata.com/instance-set: *name
            maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
    monitoring:
      pgmonitor:
        exporter:
          resources:
            limits:
              memory: 512M
            requests:
              cpu: 10m
              memory: 64M
    patroni: # turn on sync writes to at least 1 other replica
      dynamicConfiguration:
        postgresql:
          max_wal_size: 5GB
          pg_hba:
            - hostnossl all all 172.16.0.0/12 md5
            - hostssl all all all md5
          synchronous_commit: "on"
        synchronous_mode: true
    pmm:
      enabled: false
    postgresVersion: 16
    proxy:
      pgBouncer:
        config:
          global:
            client_tls_sslmode: prefer
            pool_mode: transaction # pgBouncer is set to transaction for Authentik. Grafana requires session https://github.com/grafana/grafana/issues/74260#issuecomment-1702795311. Everything else is happy with transaction
        metadata:
          labels:
            app.kubernetes.io/name: percona-postgres-pgbouncer
        port: 5432
        replicas: *replica
        topologySpreadConstraints:
          - labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: *name
                postgres-operator.crunchydata.com/instance-set: *name
                postgres-operator.crunchydata.com/role: pgbouncer
            maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
    users:
      # Superuser
      - databases: [postgres]
        name: vijay
        options: SUPERUSER
        password:
          type: AlphaNumeric
      # Applications
      - databases: [authentik]
        name: authentik
        password:
          type: AlphaNumeric
      - databases: [immich]
        name: immich
        password:
          type: AlphaNumeric
      - databases: [linkwarden]
        name: linkwarden
        password:
          type: AlphaNumeric
      - databases: [speedtest]
        name: speedtest
        password:
          type: AlphaNumeric
      - databases: [freshrss]
        name: freshrss
        password:
          type: AlphaNumeric
