---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Fly.io Apps on Dependency Updates
"on":
  push:
    paths: [fly.io/**]
    branches: ['master']

jobs:
  deploy-fly-app:
    runs-on: ubuntu-latest
    # if: >
    #   github.event.commits[0].author.name == 'renovate[bot]' ||
    #   github.event.commits[0].author.email == 'bot@renovateapp.com'
    strategy:
      matrix:
        app: [authfly, baovault, gotifyfly, vaultfly]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Install Flyctl
        uses: https://github.com/superfly/flyctl-actions/setup-flyctl@ed8efb33836e8b2096c7fd3ba1c8afe303ebbff1 # 1.6
      - name: Determine Modified Files
        id: changes
        run: |-
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')
          echo "MODIFIED_FILES=$MODIFIED_FILES" >> "$GITHUB_ENV"
          echo "Modified Files: $MODIFIED_FILES"
      - name: Deploy ${{ matrix.app }}
        if: contains(env.MODIFIED_FILES, format('fly.io/{0}/', matrix.app))
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |-
          echo "Deploying ${{ matrix.app }} to Fly.io..."
          flyctl -a ${{ matrix.app }} deploy --remote-only --now --no-public-ips --strategy immediate --no-cache fly.io/${{ matrix.app }}/
