---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Fly.io Apps on Dependency Updates
"on":
  push:
    paths: ['fly.io/**']
    branches: ['master']

jobs:
  deploy-fly-app:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: authfly
            account: main
          - app: baovault
            account: main
          - app: gotifyfly
            account: main
          - app: vaultfly
            account: main
          - app: atticfly
            account: secondary
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Install Flyctl
        uses: https://github.com/superfly/flyctl-actions/setup-flyctl@ed8efb33836e8b2096c7fd3ba1c8afe303ebbff1 # 1.6

      - name: Determine Modified Files
        id: changes
        run: |
          echo "Modified Files:"
          git diff --name-only HEAD~1 HEAD

          if git diff --name-only HEAD~1 HEAD | grep -q "^fly.io/${{ matrix.app }}/"; then
            echo "modified=true" >> "$GITHUB_OUTPUT"
          else
            echo "modified=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Deploy
        if: steps.changes.outputs.modified == 'true'
        env:
          FLY_API_TOKEN: ${{ matrix.account == 'secondary' && secrets.FLY_API_TOKEN_ACCOUNT_2 || secrets.FLY_API_TOKEN }}
        run: |-
          echo "Deploying ${{ matrix.app }} to ${{ matrix.account }} account..."
          flyctl -a ${{ matrix.app }} deploy --now \
            --remote-only \
            --no-public-ips \
            --strategy immediate \
            --no-cache \
            --config fly.io/${{ matrix.app }}/fly.toml \
            fly.io/${{ matrix.app }}/
