---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #  # production
  - ./production/home-vijayakumar-xyz.yaml
  # staging
  # - ./issuers/letsencrypt-staging.yaml
  # - ./staging/home-vijayakumar-xyz.yaml
