apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: sops-age
spec:
  externalSecretName: sops-age
  externalSecretSpec:
    dataFrom:
      - extract:
          key: sops-age
    refreshInterval: 5m
    secretStoreRef:
      kind: ClusterSecretStore
      name: flux-system-secrets
    target:
      creationPolicy: Owner
      name: sops-age
  namespaceSelectors:
    - matchLabels: {} # deploy to every namespace
  refreshTime: 1h
