apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: flux-system-secrets
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-read-secrets
          namespace: flux-system
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          namespace: database
          type: ConfigMap
