kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bao-role-secret
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    secret-id: ENC[AES256_GCM,data:XnaLVf2ClFCwuc//Bib+NhlQ/Gw6PTChdUnllPMzJjUzwBrZ,iv:jd5on/AffG3UGhNSEGSNXcm+jhH+rPlGunDTSr0mQJ4=,tag:OXAFIahGssftxhTyCH6CJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UDhma3gvQTJrRXpSWmt5
            SU85eG1oelV4a2srVTVrTlVWdGovMWJJeTFFCnZKZmpEK0lNV3N5OFhEc0hSSUhq
            cENva3Q3VXJaeDF4YnFVeEJSemFSb0kKLS0tIEs1S3JUakw1SjJibDlFS2J4Uktl
            bVpkaWw1SUhHTUZkbS9pUU5OVkxBUXcKDm0lZgx692ZIw4NabYbEN440NeaacJ+6
            xyyyXUOelk7IYcu7m6FLGnb7kNkRmvesymwpvCZtAgerAxUiAiNwUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-18T18:20:39Z"
    mac: ENC[AES256_GCM,data:YX3+YqHLFxDEWHjrKki0fzZwUfu6XD0elr30h+SIZZ5hs+uBMocUXewzz2qjKDryukKap8JjRl1kYyPCPEri9Uu8uKhFR4w9IZk/PAukiTZOKWZd8v93bqemNd2zsNd2Dap4eYsZ+Cj5G86uGKFVse4y6B9NDhpJcRuvjXBBSiA=,iv:k9Ne24I1PfVYuoqKi1m+niq9+M/yH0boLhMdCBSASdI=,tag:maC8pOpOC9WMEPZsmHdYYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
