kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bao-role-secret
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    secret-id: ENC[AES256_GCM,data:lkF1TVZi5fMUlK7OqrE0QQmqM57OPu0dxlH22rZD2ogwe9ua,iv:Yw1ero4zPrY1SSaPvNkRrcJ5DkdLQjEzkTUK5Ds7mxs=,tag:hzU9C9qdeQBW6vzfJAlnPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UDhma3gvQTJrRXpSWmt5
            SU85eG1oelV4a2srVTVrTlVWdGovMWJJeTFFCnZKZmpEK0lNV3N5OFhEc0hSSUhq
            cENva3Q3VXJaeDF4YnFVeEJSemFSb0kKLS0tIEs1S3JUakw1SjJibDlFS2J4Uktl
            bVpkaWw1SUhHTUZkbS9pUU5OVkxBUXcKDm0lZgx692ZIw4NabYbEN440NeaacJ+6
            xyyyXUOelk7IYcu7m6FLGnb7kNkRmvesymwpvCZtAgerAxUiAiNwUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-26T17:30:24Z"
    mac: ENC[AES256_GCM,data:qsYISQ/0zAtZwc9CoIcYbHiOJO48E6GRubmOKSYc9IpGIL55HTJ+xRyfNpuYVFkZO7Fe4uD057OZOSOYP+htEDh/rJuPkNQZWS5+12W9BPbNc0TdAZR7p9gOU0/NZL6FGKIkEf6JAA+/tD2mLIL58bmy4lRo8p9l0sUdNhoPrDs=,iv:IMzAr1fqGz9Y8ZHwvYJzYetfSauvptzU6fewdyHD4kI=,tag:0TyJlLl2zgwqRY/6hEIqwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
