---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bao
spec:
  provider:
    vault:
      server: ${BAO_ADDR}
      path: luffy
      version: v2
      auth:
        appRole:
          path: approle
          roleId: ${BAO_ROLE_ID}
          secretRef:
            name: bao-role-secret
            key: secret-id
            namespace: security
