---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bao
spec:
  provider:
    vault:
      server: https://bao.robin.vjlab.dev
      path: luffy
      version: v2
      auth:
        appRole:
          path: approle
          roleId: 4690b4ac-a04c-4071-8b98-89729474efd1
          secretRef:
            name: bao-role-secret
            key: secret-id
            namespace: security
