---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: karakeep-secret
    template:
      data:
        NEXTAUTH_SECRET: "{{ .karakeep_nextauth_secret }}"
        MEILI_MASTER_KEY: "{{ .karakeep_meilisearch_master_key }}"
        OAUTH_WELLKNOWN_URL: "{{ .karakeep_oauth_wellknown_url }}"
        OAUTH_CLIENT_SECRET: "{{ .karakeep_oauth_client_secret }}"
        OAUTH_CLIENT_ID: "{{ .karakeep_oauth_client_id }}"
        OAUTH_AUTO_REDIRECT: "true"
        OAUTH_PROVIDER_NAME: "Pocket-ID"
        OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"
        SMTP_HOST: "{{ .karakeep_smtp_host }}"
        SMTP_PORT: "{{ .karakeep_smtp_port }}"
        SMTP_USER: "{{ .karakeep_smtp_user }}"
        SMTP_PASSWORD: "{{ .karakeep_smtp_password }}"
        SMTP_FROM: "{{ .karakeep_smtp_user }}"
        #OLLAMA_BASE_URL: http://10.0.2.2:11434
        #OLLAMA_KEEP_ALIVE: "30m"
        OPENAI_API_KEY: "{{ .karakeep_openai_api_key }}"
        OPENAI_BASE_URL: https://openrouter.ai/api/v1
        INFERENCE_TEXT_MODEL: "nvidia/nemotron-nano-12b-v2-vl:free"
        #"gemma3:4b"
        INFERENCE_IMAGE_MODEL: "nvidia/nemotron-nano-12b-v2-vl:free"
        # "gemma3:4b"
        # EMBEDDING_TEXT_MODEL: "embeddinggemma"
        INFERENCE_CONTEXT_LENGTH: "30000"
        INFERENCE_MAX_OUTPUT_TOKENS: "30000"
        INFERENCE_ENABLE_AUTO_SUMMARIZATION: "true"
        INFERENCE_JOB_TIMEOUT_SEC: "3600"
        INFERENCE_FETCH_TIMEOUT_SEC: "3600"
  dataFrom:
    - extract:
        key: karakeep
      rewrite:
        - regexp:
            source: "(.*)"
            target: "karakeep_$1"
