---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-idrive"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: "${APP}-volsync-idrive"
    creationPolicy: Owner
    template:
      data:
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        RESTIC_REPOSITORY: "{{ .IDRIVE_REPOSITORY_TEMPLATE }}/${CLUSTER_NAME}/${APP}"
        AWS_ACCESS_KEY_ID: "{{ .IDRIVE_AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .IDRIVE_AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-template
