apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-share-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /media
    server: 10.0.0.3
