kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-share-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: media-share-pv
