---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: outline-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secret_key }}"
        UTILS_SECRET: "{{ .utils_secret }}"
        # OIDC configuration
        OIDC_DISPLAY_NAME: PocketID
        OIDC_ISSUER_URL: "{{ .oidc_issuer_url }}"
        OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        OIDC_LOGOUT_URI: "{{ .oidc_logout_uri }}"
        # S3 configuration
        FILE_STORAGE: "s3"
        AWS_REGION: "us-east-2"
        AWS_S3_FORCE_PATH_STYLE: "true"
        AWS_S3_UPLOAD_BUCKET_NAME: "{{ .aws_s3_upload_bucket_name }}"
        AWS_S3_UPLOAD_BUCKET_URL: "{{ .aws_s3_upload_bucket_url }}"
        AWS_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
        # SMTP configuration
        SMTP_NAME: Outline
        SMTP_HOST: "{{ .smtp_server }}"
        SMTP_PORT: "465"
        SMTP_USERNAME: "{{ .smtp_user }}"
        SMTP_PASSWORD: "{{ .smtp_password }}"
        SMTP_FROM_EMAIL: "{{ .smtp_from }}"
        SMTP_REPLY_EMAIL: "{{ .smtp_reply_email }}"
  dataFrom:
    - extract:
        key: outline

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: outline-db-secret
    template:
      type: Opaque
      data:
        DATABASE_URL: "{{ .uri }}"
  dataFrom:
    - extract:
        key: postgres-pguser-outline
