apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: kanidm-tls-policy
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: kanidm-web
      sectionName: http
  validation:
    hostname: idm.${LAB_DOMAIN}
    wellKnownCACertificates: System
