---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-mail-sender
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: kanidm-mail-sender
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: kanidm-mail-sender-tpl
            items:
              - key: mail_sender.toml
      data:
        client-config: |
          uri = "https://idm.${LAB_DOMAIN}"
  dataFrom:
    - extract:
        key: kanidm
      rewrite:
        - regexp:
            source: "(.*)"
            target: "kanidm_$1"
