---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kanidm
spec:
  interval: 30m
  timeout: 1m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      kanidm:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        type: statefulset
        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 2000
            runAsNonRoot: true
            runAsUser: 2000
        containers:
          server:
            image:
              repository: docker.io/kanidm/server
              tag: 1.9.3
            env:
              KANIDM_CONFIG: /config/server.toml
              KANIDM_ADMIN_BIND_PATH: /var/run/kanidmd.sock
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]
          tools:
            image:
              repository: docker.io/kanidm/tools
              tag: 1.9.2
            command: ["/bin/bash", "-c", "tail -f /dev/null"]
            probes:
              liveness: &healthcheck
                enabled: false
              readiness: *healthcheck
            resources:
              requests:
                cpu: 20m
                memory: 250Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]
    service:
      web:
        controller: kanidm
        ports:
          http:
            port: &port 8443
      kanidm:
        controller: kanidm
        type: NodePort
        ports:
          ldap:
            port: 3636
            nodePort: 32626

    route:
      server:
        hostnames:
          - idm.${LAB_DOMAIN}
        parentRefs:
          - name: envoy
            namespace: network
        rules:
          - backendRefs:
              - identifier: web
                port: *port
    persistence:
      certs:
        type: secret
        name: ${LAB_DOMAIN}-tls
        defaultMode: 0400
        globalMounts:
          - path: /certs
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /var/run
            subPath: var-run
      config:
        type: configMap
        name: kanidm-config
        defaultMode: 0400
      data:
        existingClaim: kanidm
        globalMounts:
          - path: /data
            subPath: data
