---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - ./config/server.toml
    name: kanidm-server-config
  - files:
      - ./config/mail_sender.toml
    name: kanidm-mail-sender-tpl
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./backendpolicy.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./certificate.yaml
