---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ente-secret
spec:
  dataFrom:
    - extract:
        key: ente
      rewrite:
        - regexp:
            source: "(.*)"
            target: "ente_$1"

  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: ente-secret
    template:
      data:
        # Apps
        ENTE_APPS_ACCOUNTS: "https://accounts.${CLUSTER_DOMAIN}"
        ENTE_APPS_CAST: "https://cast.${CLUSTER_DOMAIN}"
        ENTE_APPS_CUSTOM_DOMAIN_CNAME: "ente.${CLUSTER_DOMAIN}"
        ENTE_APPS_EMBED_ALBUMS: "https://embed.${CLUSTER_DOMAIN}"
        ENTE_APPS_PUBLIC_ALBUMS: "https://albums.${CLUSTER_DOMAIN}"
        ENTE_APPS_PUBLIC_LOCKER: "https://share.${CLUSTER_DOMAIN}"
        ENTE_APPS_PUBLIC_MEMORIES: "https://memories.${CLUSTER_DOMAIN}"
        ENTE_APPS_PUBLIC_PASTE: "https://paste.${CLUSTER_DOMAIN}"

        # Origins
        ENTE_ALBUMS_ORIGIN: "https://albums.${CLUSTER_DOMAIN}"
        ENTE_API_ORIGIN: "https://ente.${CLUSTER_DOMAIN}"
        ENTE_PHOTOS_ORIGIN: "https://photos.${CLUSTER_DOMAIN}"

        # Internal & JWT
        ENTE_INTERNAL_ADMIN: "1580559962386438"
        ENTE_JWT_SECRET: "{{ .ente_jwt_secret }}"
        ENTE_KEY_ENCRYPTION: "{{ .ente_encryption_key }}"
        ENTE_KEY_HASH: "{{ .ente_encryption_hash }}"

        # S3
        ENTE_S3_ARE_LOCAL_BUCKETS: "false"
        ENTE_S3_B2_EU_CEN_BUCKET: "ente"
        ENTE_S3_B2_EU_CEN_ENDPOINT: "{{ .ente_iDrive_endpoint }}"
        ENTE_S3_B2_EU_CEN_KEY: "{{ .ente_iDrive_key }}"
        ENTE_S3_B2_EU_CEN_REGION: "us-west-1"
        ENTE_S3_B2_EU_CEN_SECRET: "{{ .ente_iDrive_secret }}"
        ENTE_S3_USE_PATH_STYLE_URLS: "true"

        # SMTP
        ENTE_SMTP_EMAIL: "{{ .ente_smtp_username }}"
        ENTE_SMTP_HOST: "{{ .ente_smtp_host }}"
        ENTE_SMTP_PASSWORD: "{{ .ente_smtp_password }}"
        ENTE_SMTP_PORT: "587"
        ENTE_SMTP_SENDER_NAME: "Ente"
        ENTE_SMTP_USERNAME: "{{ .ente_smtp_username }}"

        # WebAuthn
        ENTE_WEBAUTHN_RPID: "${CLUSTER_DOMAIN}"
        ENTE_WEBAUTHN_RPORIGINS: "https://accounts.${CLUSTER_DOMAIN}"

      type: Opaque
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ente-db
spec:
  dataFrom:
    - extract:
        key: postgres-pguser-ente
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: ente-db-secret
    template:
      data:
        ENTE_DB_HOST: "{{ .host }}"
        ENTE_DB_NAME: "{{ .dbname }}"
        ENTE_DB_PASSWORD: "{{ .password }}"
        ENTE_DB_PORT: "{{ .port }}"
        ENTE_DB_SSLMODE: "require"
        ENTE_DB_USER: "{{ .user }}"
      type: Opaque
