---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ente
spec:
  interval: 30m
  timeout: 1m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      ente:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        containers:
          web:
            image:
              repository: ghcr.io/ente-io/web
              tag: latest@sha256:c74f9b7066db161f6b6fe5af6f6cd6e19d31f8324b57a2c7fee203a3fdebc451
            envFrom:
              - secretRef:
                  name: ente-secret
              - secretRef:
                  name: ente-db-secret
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
          server:
            image:
              repository: ghcr.io/ente-io/server
              tag: latest@sha256:e1b615b261391b79a9d27f00783f70b909a18c67960cc038846a9e928fe79903
            envFrom:
              - secretRef:
                  name: ente-secret
              - secretRef:
                  name: ente-db-secret
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
    service:
      api:
        controller: ente
        ports:
          http:
            port: 8080
      photos:
        controller: ente
        ports:
          http:
            port: 3000
      accounts:
        controller: ente
        ports:
          http:
            port: 3001
      public-albums:
        controller: ente
        ports:
          http:
            port: 3002
      cast:
        controller: ente
        ports:
          http:
            port: 3004
      share:
        controller: ente
        ports:
          http:
            port: 3005
      embed:
        controller: ente
        ports:
          http:
            port: 3006

    route:
      photos: &route
        parentRefs:
          - name: envoy
            namespace: network
        rules:
          - backendRefs:
              - identifier: photos
                port: http
        hostnames:
          - photos.${CLUSTER_DOMAIN}

      api:
        <<: *route
        hostnames:
          - ente.${CLUSTER_DOMAIN}
        rules:
          - backendRefs:
              - identifier: api
                port: http

      accounts:
        <<: *route
        hostnames:
          - accounts.${CLUSTER_DOMAIN}
        rules:
          - backendRefs:
              - identifier: accounts
                port: http

      public-albums:
        <<: *route
        hostnames:
          - albums.${CLUSTER_DOMAIN}
        rules:
          - backendRefs:
              - identifier: public-albums
                port: http

      cast:
        <<: *route
        hostnames:
          - cast.${CLUSTER_DOMAIN}
        rules:
          - backendRefs:
              - identifier: cast
                port: http

      share:
        <<: *route
        hostnames:
          - share.${CLUSTER_DOMAIN}
        rules:
          - backendRefs:
              - identifier: share
                port: http

      embed:
        <<: *route
        hostnames:
          - embed.${CLUSTER_DOMAIN}
        rules:
          - backendRefs:
              - identifier: embed
                port: http

#    persistence:
#      museum-yaml:
#        enabled: true
#        type: secret
#        name: museum-yaml
#        globalMounts:
#          - path: /museum.yaml
#
