# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik.yaml
  - ./cilium.yaml
  - ./fluxcd-kustomize-mutating-webhook.yaml
  - ./gitlab.yaml
  - ./intel.yaml
  - ./kite.yaml
  - ./metallb.yaml
  - ./nginx.yaml
  - ./percona.yaml
  - ./rook-ceph.yaml
