---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: grafana-oauth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_AUTH_OAUTH_AUTO_LOGIN: "true"
        GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
        GF_AUTH_GENERIC_OAUTH_NAME: "Pocket ID"
        GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email groups
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .grafana_client_id }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .grafana_client_secret }}"
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: "{{ .grafana_oauth_auth_url }}"
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "{{ .grafana_oauth_token_url }}"
        GF_AUTH_GENERIC_OAUTH_API_URL: "{{ .grafana_oauth_api_url }}"
        GF_AUTH_SIGNOUT_REDIRECT_URL: "{{ .grafana_signout_redirect_url }}"
        GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(groups, 'admin')&& 'Admin' || contains(groups, 'editors') && 'Editor' || 'Viewer'
  dataFrom:
    - extract:
        key: grafana
      rewrite:
        - regexp:
            source: (.*)
            target: grafana_$1
