---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotosocial-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: gotosocial-secret
    template:
      data:
        GTS_OIDC_ADMIN_GROUPS: admin
        GTS_OIDC_CLIENT_ID: gotosocial
        GTS_OIDC_CLIENT_SECRET: "{{ .gotosocial_oidc_client_secret }}"
        GTS_OIDC_ENABLED: "true"
        GTS_OIDC_IDP_NAME: "PocketID"
        GTS_OIDC_ISSUER: "https://auth.${CLUSTER_DOMAIN}"
        GTS_OIDC_LINK_EXISTING: "true"
  dataFrom:
    - extract:
        key: gotosocial
      rewrite:
        - regexp:
            source: "(.*)"
            target: "gotosocial_$1"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotosocial-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: gotosocial-db
    template:
      data:
        GTS_DB_POSTGRES_CONNECTION_STRING: "{{ .uri }}"
      type: Opaque
  dataFrom:
    - extract:
        key: postgres-pguser-gotosocial
