---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname kopia
  namespace: flux-system
spec:
  targetNamespace: &namespace system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *appname
      namespace: *namespace
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  timeout: 10m
  path: './kubernetes/luffy/apps/system/kopia/app'
  postBuild:
    substitute:
      APP: *appname
  prune: true
  dependsOn:
    - name: volsync
