---
replicaCount: 3
image:
  repository: ghcr.io/goauthentik/server
  pullPolicy: IfNotPresent
  tag: 2024.12.0
nameOverride: ''
args: [server]
selectorLabels: [app.kubernetes.io/component=server]
serviceAccountName: rbac-authentik-remote-cluster
deploymentStrategy:
  rollingUpdate:
    maxUnavailable: 1
  type: RollingUpdate
configs:
  - name: authentik-config
    data:
      AUTHENTIK_REDIS__HOST: redis-app.authentik.svc.cluster.local
      AUTHENTIK_DISABLE_STARTUP_ANALYTICS: 'true'
      AUTHENTIK_AVATARS: initials
      AUTHENTIK_DISABLE_UPDATE_CHECK: 'true'
envFrom:
  - secretRef:
      name: authentik-secrets
  - configMapRef:
      name: authentik-config
env:
  - name: AUTHENTIK_POSTGRESQL__PASSWORD
    valueFrom:
      secretKeyRef:
        name: authentik-db-app
        key: password
  - name: AUTHENTIK_POSTGRESQL__USER
    valueFrom:
      secretKeyRef:
        name: authentik-db-app
        key: username
  - name: AUTHENTIK_POSTGRESQL__HOST
    valueFrom:
      secretKeyRef:
        name: authentik-db-app
        key: host
  - name: AUTHENTIK_POSTGRESQL__NAME
    valueFrom:
      secretKeyRef:
        name: authentik-db-app
        key: dbname
service:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
    - name: https
      port: 9443
    - name: metrics
      port: 9300
persistentVolumes: []
ingress:
  enabled: false
probes:
  liveness:
    httpGet:
      path: /-/health/live/
      port: 9000
    failureThreshold: 5
    periodSeconds: 30
    timeoutSeconds: 10
  readiness:
    httpGet:
      path: /-/health/ready/
      port: 9000
    failureThreshold: 5
    periodSeconds: 30
    timeoutSeconds: 10
resources:
  limits:
    memory: 600Mi
  requests:
    cpu: 10m
    memory: 400Mi
