kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: crunchy-postgres-secret
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    s3.conf: ENC[AES256_GCM,data:yiSRfohMqzY4MOlOiNeSbN6uNitm0dt6OMQV80norzgtoI6Zoqq/mpr6hsO3LrOe/UL6q6iuyz45MJoNpM4YrKNx4EifrBLSQR0eXIB5uSNCDA+xaYI3av0sZ3UfNpX4vSFCoktx3lN7zIT4NdUQNWajs7KkgN7LYy36Up0KMLcl7fO2s1q5PD/vrUHqK/2ElRQiGlklvNYnb7/5ZuKKp3KLFyUDafGZEbegH/wEV6snjXAVIm31iFigHbBhhP1Z0N0xNOJqCNF1TmnbZr0TawA1WITOqXTz2mK8y+b/O2hb0XZw7BX10ZIK7g==,iv:B7VFdk5fVrVMBeebShXLnB4wIUrCmiXLTh+SJOFoafA=,tag:A2eCv1EWuRJiVI1Ft4f23w==,type:str]
    encryption.conf: ENC[AES256_GCM,data:X3sP9s71JjP+Ar/VxkN7WDFVXA0+qzkAkft6rYydMytHTPg5TPdB68jsmuibn9qG1LX9LJsKMVTniv2gWwj0gvPaZXk=,iv:skz470DmL5rrADrEbaPvxCyR7KUzdH2ku2CuCBkv2cA=,tag:JCfI4Nge6pjTta7j6wy15Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQW9ldWU1QnIxaVJNRmh4
            SGk0WFU2ZUwvcys4R2F2RjBqVnEzVzFGZTNRCmZDMVI3bWlNMC9sekw1ZjNtRUdJ
            RHJ6UEkvcmM2UzBXQjh6Sy9uUkVGUDQKLS0tIGhYSHBnVG8wTUd1Q0VwUDVyc2o4
            SFpUQzAzSFNLR3liRkcrYTJFWEJJMncKIkJJGdtBEi4F++oKhtNBbKMQRD0R9Wlr
            r3VCfqQ/3A3mqub+aGUDa74ECEBhQDg9c4h7MAM76tnlKXcNJVa6KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-15T14:10:52Z"
    mac: ENC[AES256_GCM,data:7/wR1nPfyhZA6FxPPdZ/GGlxGHzYeUO/lPLV5MT1t+88QFXM7ts38JCIpZa+6kThj/CbMjPkdfminiZdCSw4ZKUBmbM+UXY4J5c2oHLL9x7t6e6PEySKd1/SKzzILBWvW3MLzMVpx3RWhu1rcwFzbhp81egk1vcx7FJbWhy1JE8=,iv:8YD8hFvOqGtTGQCAGUjY4Nvv+OwcXxXWWl2dljBs52c=,tag:Nu4kH53Wj6zkTomUVUPX0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: crunchy-postgres-config
data:
    init.sql: ENC[AES256_GCM,data:A5Hllf0qO7m92JtpdsKMZjdU0QcTGb48,iv:0Zn9ZzmRErcS/lq0kAWU4zkGN1DJdd5Yj0xZfABJMto=,tag:za0maeivQ4JasdOcGUpC6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQW9ldWU1QnIxaVJNRmh4
            SGk0WFU2ZUwvcys4R2F2RjBqVnEzVzFGZTNRCmZDMVI3bWlNMC9sekw1ZjNtRUdJ
            RHJ6UEkvcmM2UzBXQjh6Sy9uUkVGUDQKLS0tIGhYSHBnVG8wTUd1Q0VwUDVyc2o4
            SFpUQzAzSFNLR3liRkcrYTJFWEJJMncKIkJJGdtBEi4F++oKhtNBbKMQRD0R9Wlr
            r3VCfqQ/3A3mqub+aGUDa74ECEBhQDg9c4h7MAM76tnlKXcNJVa6KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-15T14:10:52Z"
    mac: ENC[AES256_GCM,data:7/wR1nPfyhZA6FxPPdZ/GGlxGHzYeUO/lPLV5MT1t+88QFXM7ts38JCIpZa+6kThj/CbMjPkdfminiZdCSw4ZKUBmbM+UXY4J5c2oHLL9x7t6e6PEySKd1/SKzzILBWvW3MLzMVpx3RWhu1rcwFzbhp81egk1vcx7FJbWhy1JE8=,iv:8YD8hFvOqGtTGQCAGUjY4Nvv+OwcXxXWWl2dljBs52c=,tag:Nu4kH53Wj6zkTomUVUPX0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-pguser-vijay
    labels:
        postgres-operator.crunchydata.com/cluster: postgres
        postgres-operator.crunchydata.com/pguser: vijay
stringData:
    password: ENC[AES256_GCM,data:Binqbu0tseClyrg=,iv:kK/7jujXcgOPY3k2KMf+FvufrX0O2b6VuMBOck+Cu/c=,tag:MDFGzlyCNEwc6JpzMq8uSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQW9ldWU1QnIxaVJNRmh4
            SGk0WFU2ZUwvcys4R2F2RjBqVnEzVzFGZTNRCmZDMVI3bWlNMC9sekw1ZjNtRUdJ
            RHJ6UEkvcmM2UzBXQjh6Sy9uUkVGUDQKLS0tIGhYSHBnVG8wTUd1Q0VwUDVyc2o4
            SFpUQzAzSFNLR3liRkcrYTJFWEJJMncKIkJJGdtBEi4F++oKhtNBbKMQRD0R9Wlr
            r3VCfqQ/3A3mqub+aGUDa74ECEBhQDg9c4h7MAM76tnlKXcNJVa6KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-15T14:10:52Z"
    mac: ENC[AES256_GCM,data:7/wR1nPfyhZA6FxPPdZ/GGlxGHzYeUO/lPLV5MT1t+88QFXM7ts38JCIpZa+6kThj/CbMjPkdfminiZdCSw4ZKUBmbM+UXY4J5c2oHLL9x7t6e6PEySKd1/SKzzILBWvW3MLzMVpx3RWhu1rcwFzbhp81egk1vcx7FJbWhy1JE8=,iv:8YD8hFvOqGtTGQCAGUjY4Nvv+OwcXxXWWl2dljBs52c=,tag:Nu4kH53Wj6zkTomUVUPX0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
