kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: crunchy-postgres-secret
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    s3.conf: ENC[AES256_GCM,data:PFG/bu0UchhPAlXCjK2AqrTNBZfhHY/lvuZ+8WzjTcuJTUxi143Awo6i0riUtCx8mZXaXnll6i+p99vJKHcgpu+sz2Otr4h/2WGd3vw6DJdQhw72dPwyFV3NNKqOUJgIcKQ4xQ1raIwvajP3V4poFiBtugsy4627rjR0118slQD2yU7rUWkk7Vb99Ps=,iv:Rvb4UshSrL1Dj2MaVq3PrRnLXMbVxZc0hN0ZPj4QaJo=,tag:jU5HecLp9kWBt7CGSo+eDA==,type:str]
    encryption.conf: ENC[AES256_GCM,data:71A7w9SklRFiHNURX1LU0UR++wuhMHEG5aA1aaAi3ZD5IdI3bPg=,iv:M/c6m1VdeEyLpv1KUcPCMIAcbVqrDI+ecWslQuxh6UA=,tag:GTeYsBGHM+PJ+uF8wxbVXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQW9ldWU1QnIxaVJNRmh4
            SGk0WFU2ZUwvcys4R2F2RjBqVnEzVzFGZTNRCmZDMVI3bWlNMC9sekw1ZjNtRUdJ
            RHJ6UEkvcmM2UzBXQjh6Sy9uUkVGUDQKLS0tIGhYSHBnVG8wTUd1Q0VwUDVyc2o4
            SFpUQzAzSFNLR3liRkcrYTJFWEJJMncKIkJJGdtBEi4F++oKhtNBbKMQRD0R9Wlr
            r3VCfqQ/3A3mqub+aGUDa74ECEBhQDg9c4h7MAM76tnlKXcNJVa6KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-15T12:48:55Z"
    mac: ENC[AES256_GCM,data:Z6FvLGyjc7vkOWu6vtTSIP6H8o+kJUMQa/NY8InO7+8Q4OD/xHW9mR/uFbxvFXuA51c3B16gPoyifg07/VxlD8ReK6wOVuRqcu0d1zPYwUSnZmfb7gNvN7Y43W5qh4B7isnCJ0UsRS32ybtWdtjaUdnDMLolZCcI/WaVZQYfJW4=,iv:jdVdvZiAbBm5mq2cit+IRH500/5BB/9dKZ5szwk8U34=,tag:ImolsDlpPk63yP4DyNzKuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: crunchy-postgres-config
data:
    init.sql: ENC[AES256_GCM,data:A5Hllf0qO7m92JtpdsKMZjdU0QcTGb48,iv:0Zn9ZzmRErcS/lq0kAWU4zkGN1DJdd5Yj0xZfABJMto=,tag:za0maeivQ4JasdOcGUpC6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQW9ldWU1QnIxaVJNRmh4
            SGk0WFU2ZUwvcys4R2F2RjBqVnEzVzFGZTNRCmZDMVI3bWlNMC9sekw1ZjNtRUdJ
            RHJ6UEkvcmM2UzBXQjh6Sy9uUkVGUDQKLS0tIGhYSHBnVG8wTUd1Q0VwUDVyc2o4
            SFpUQzAzSFNLR3liRkcrYTJFWEJJMncKIkJJGdtBEi4F++oKhtNBbKMQRD0R9Wlr
            r3VCfqQ/3A3mqub+aGUDa74ECEBhQDg9c4h7MAM76tnlKXcNJVa6KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-15T12:48:55Z"
    mac: ENC[AES256_GCM,data:Z6FvLGyjc7vkOWu6vtTSIP6H8o+kJUMQa/NY8InO7+8Q4OD/xHW9mR/uFbxvFXuA51c3B16gPoyifg07/VxlD8ReK6wOVuRqcu0d1zPYwUSnZmfb7gNvN7Y43W5qh4B7isnCJ0UsRS32ybtWdtjaUdnDMLolZCcI/WaVZQYfJW4=,iv:jdVdvZiAbBm5mq2cit+IRH500/5BB/9dKZ5szwk8U34=,tag:ImolsDlpPk63yP4DyNzKuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-pguser-vijay
    labels:
        postgres-operator.crunchydata.com/cluster: postgres
        postgres-operator.crunchydata.com/pguser: vijay
stringData:
    password: ENC[AES256_GCM,data:Binqbu0tseClyrg=,iv:kK/7jujXcgOPY3k2KMf+FvufrX0O2b6VuMBOck+Cu/c=,tag:MDFGzlyCNEwc6JpzMq8uSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQW9ldWU1QnIxaVJNRmh4
            SGk0WFU2ZUwvcys4R2F2RjBqVnEzVzFGZTNRCmZDMVI3bWlNMC9sekw1ZjNtRUdJ
            RHJ6UEkvcmM2UzBXQjh6Sy9uUkVGUDQKLS0tIGhYSHBnVG8wTUd1Q0VwUDVyc2o4
            SFpUQzAzSFNLR3liRkcrYTJFWEJJMncKIkJJGdtBEi4F++oKhtNBbKMQRD0R9Wlr
            r3VCfqQ/3A3mqub+aGUDa74ECEBhQDg9c4h7MAM76tnlKXcNJVa6KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-15T12:48:55Z"
    mac: ENC[AES256_GCM,data:Z6FvLGyjc7vkOWu6vtTSIP6H8o+kJUMQa/NY8InO7+8Q4OD/xHW9mR/uFbxvFXuA51c3B16gPoyifg07/VxlD8ReK6wOVuRqcu0d1zPYwUSnZmfb7gNvN7Y43W5qh4B7isnCJ0UsRS32ybtWdtjaUdnDMLolZCcI/WaVZQYfJW4=,iv:jdVdvZiAbBm5mq2cit+IRH500/5BB/9dKZ5szwk8U34=,tag:ImolsDlpPk63yP4DyNzKuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
