kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: crunchy-postgres-secret
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    s3.conf: ENC[AES256_GCM,data:PFG/bu0UchhPAlXCjK2AqrTNBZfhHY/lvuZ+8WzjTcuJTUxi143Awo6i0riUtCx8mZXaXnll6i+p99vJKHcgpu+sz2Otr4h/2WGd3vw6DJdQhw72dPwyFV3NNKqOUJgIcKQ4xQ1raIwvajP3V4poFiBtugsy4627rjR0118slQD2yU7rUWkk7Vb99Ps=,iv:Rvb4UshSrL1Dj2MaVq3PrRnLXMbVxZc0hN0ZPj4QaJo=,tag:jU5HecLp9kWBt7CGSo+eDA==,type:str]
    encryption.conf: ENC[AES256_GCM,data:71A7w9SklRFiHNURX1LU0UR++wuhMHEG5aA1aaAi3ZD5IdI3bPg=,iv:M/c6m1VdeEyLpv1KUcPCMIAcbVqrDI+ecWslQuxh6UA=,tag:GTeYsBGHM+PJ+uF8wxbVXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQW9ldWU1QnIxaVJNRmh4
            SGk0WFU2ZUwvcys4R2F2RjBqVnEzVzFGZTNRCmZDMVI3bWlNMC9sekw1ZjNtRUdJ
            RHJ6UEkvcmM2UzBXQjh6Sy9uUkVGUDQKLS0tIGhYSHBnVG8wTUd1Q0VwUDVyc2o4
            SFpUQzAzSFNLR3liRkcrYTJFWEJJMncKIkJJGdtBEi4F++oKhtNBbKMQRD0R9Wlr
            r3VCfqQ/3A3mqub+aGUDa74ECEBhQDg9c4h7MAM76tnlKXcNJVa6KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T07:21:59Z"
    mac: ENC[AES256_GCM,data:kWD3R1AVNQ2gIz/iL719rChb0D53WyzWBV9bO+djRrlINF95Uw8J1QD1RV51fjIeX2/+Tl34oSyJ38AmNrsT+tZJG+OX19yZi0JGerICu1OkGbpmWnKqxN2Gv4qRMZdDbKIAeWF1ag4gXgVKJxXZtr06pkpQpOCXq3yWmz6XXQE=,iv:ErBEM6QdYN3RzNtH6Y6W3ZkP11ezzvKNAQ970j39QKU=,tag:DL1Hvd1lv3PFm/TaR6AM/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
