---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crunchy-postgres
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: crunchy-postgres-secret
    template:
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .crunchy_postgres_r2_cpgo_access_id }}
          repo1-s3-key-secret={{ .crunchy_postgres_r2_cpgo_access_key }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .crunchy_postgres_backup_encryption_cipher }}
  dataFrom:
    - extract:
        key: Crunchy postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "crunchy_postgres_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-pguser-vijay
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: postgres-pguser-vijay
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          postgres-operator.crunchydata.com/cluster: postgres
          postgres-operator.crunchydata.com/pguser: vijay
      data:
        password: "{{ .crunchy_postgres_vijay_password }}"
  dataFrom:
    - extract:
        key: Crunchy postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "crunchy_postgres_$1"
