---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name crunchy-postgres
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: crunchy-postgres-secret
    template:
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .CPGO_MINIO_ACCESS_KEY }}
          repo1-s3-key-secret={{ .CPGO_MINIO_SECRET_KEY }}
          repo2-s3-key={{ .CPGO_CLOUDFLARE_ACCESS_ID }}
          repo2-s3-key-secret={{ .CPGO_CLOUDFLARE_ACCESS_KEY }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .CPGO_BACKUP_ENCRYPTION_CIPHER }}
          repo2-cipher-pass={{ .CPGO_BACKUP_ENCRYPTION_CIPHER }}
  dataFrom:
    - find:
        path: CPGO_
