---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  nfs:
    path: "/mnt/tank/Kubernetes/Backup/CPGO"
    server: ${NFS_STORAGE_SERVER}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-nfs
