apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: postgres-upgrade
spec:
  postgresClusterName: postgres
  fromPostgresVersion: 17
  toPostgresVersion: 18

# kubectl -n database annotate postgrescluster postgres postgres-operator.crunchydata.com/allow-upgrade="postgres-upgrade"
# edit the spec.shutdown field to true
