---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1
kind: PostgresCluster
metadata:
  name: &name postgres
spec:
  # shutdown: true
  backups:
    pgbackrest:
      configuration: &backupConfig
        - secret:
            name: crunchy-postgres-secret
      global: &backupFlag
        archive-async: "y"
        archive-push-queue-max: 5GiB
        compress-level: "9"
        # R2
        compress-type: bz2
        repo1-block: "y"
        repo1-bundle: "y"
        repo1-path: /crunchy-pgo/luffy
        repo1-retention-full: "7" # days
        repo1-retention-full-type: time
        repo1-s3-uri-style: path
      # # Wasabi
      # repo2-bundle: "y"
      # repo2-block: "y"
      # repo2-path: /crunchy-pgo
      # repo2-retention-full: "7" # days
      # repo2-retention-full-type: time
      # repo2-s3-uri-style: path
      manual:
        options: [--type=full]
        repoName: repo1
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-backup
      repos:
        - name: repo1 # R2
          s3: &r2
            bucket: "backup"
            endpoint: ${R2_ENDPOINT}
            region: "us-east-1"
          schedules:
            differential: "0 1 * * 1-6" # Mon-Sat at 01:00
            full: "0 1 * * 0" # Sunday at 01:00
            incremental: "0 2-23 * * *" # Every hour except 01:00
  # - name: repo2 # Wasabi
  #  s3: &wasabi
  #    bucket: "luffy"
  #    endpoint: s3.ap-northeast-1.wasabisys.com
  #    region: "ap-northeast-1"
  #  schedules:
  #    full: "0 1 * * 0" # Sunday at 01:00
  #    differential: "0 1 * * 1-6" # Mon-Sat at 01:00
  #    incremental: "0 2-23 * * *" # Every hour except 01:00
  config:
    parameters:
      max_wal_size: 5GB
      shared_preload_libraries: timescaledb
  dataSource:
    pgbackrest:
      configuration: *backupConfig
      global: *backupFlag
      repo:
        name: "repo1"
        s3: *r2
      stanza: "db"
  instances:
    - dataVolumeClaimSpec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 50Gi
        storageClassName: openebs-hostpath
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres
      name: postgres
      replicas: &replica 3
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/data: postgres
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
  metadata:
    labels:
      crunchy-userinit.drummyfloyd.github.com/enabled: "true"
      crunchy-userinit.drummyfloyd.github.com/superuser: vijay
  monitoring:
    pgmonitor:
      exporter:
        resources:
          limits:
            memory: 512M
          requests:
            cpu: 10m
            memory: 64M
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - hostnossl all all 172.16.0.0/12 md5
          - hostssl all all all md5
        synchronous_commit: "on"
      synchronous_mode: true  # turn on sync writes to at least 1 other replica
  postgresVersion: 18
  proxy:
    pgBouncer:
      config:
        global:
          client_tls_sslmode: prefer
          pool_mode: transaction # pgBouncer is set to transaction for Authentik. Grafana requires session https://github.com/grafana/grafana/issues/74260#issuecomment-1702795311. Everything else is happy with transaction
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-pgbouncer
      port: 5432
      replicas: *replica
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/role: pgbouncer
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
  service:
    metadata:
      annotations:
        lbipam.cilium.io/ips: 10.0.1.2
    type: LoadBalancer
  users:
    # Superuser
    - databases: [postgres]
      name: vijay
      options: SUPERUSER
    # Applications
    - databases: [authentik]
      name: authentik
      password:
        type: AlphaNumeric
    - databases: [freshrss]
      name: freshrss
      password:
        type: AlphaNumeric
    - databases: [immich]
      name: immich
      password:
        type: AlphaNumeric
    - databases: [kite]
      name: kite
      password:
        type: AlphaNumeric
    - databases: [paperless]
      name: paperless
      password:
        type: AlphaNumeric
    - databases: [seerr]
      name: seerr
      password:
        type: AlphaNumeric
    - databases: [speedtest]
      name: speedtest
      password:
        type: AlphaNumeric
