---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smbcreds
  namespace: default
spec:
  encryptedData:
    password: AgB7JO167vCJQjFmasxtspNcLBeEDcLKQH27F4okcegbD4VDNrA7AF4ltYbrppkFUQI9loriyL4wD84N3OUqWCKm1ePcPet7DVKeQjTl9Chka7K9pF/isRmpVeJPIeKl799QgVrNaNaxClIv1oI0B+8I1iQOTswIaqII1gnTuhtP2KOSGG7miiSUfd+Ndx5Z7jOkOq+8IWMluhlqrkYwqGcf4j14Pd/izn0dviXaRRTgCBA69mYL+i4U/zEWt+2k+PapNZ6+2oNNnrEoa2IQNMQeIAfcoOxB3Arw4uFIz5Fk5lbw5TFF46xsTLdszzUsCDfxmvkHiUlW9bbJa1yvZDIypASoRl9Z8GLUw4HqrzzHf+3jGrjsmq7hCMo34a2U8wIYfYNHNYDRscb0g7Y/cPzDBVID4k4N9NJdVNd+5fpTyOgTdVCR2Y0QJDDbKQ5wnwRr2pk4f+n2WMExbn3js7PL6FsTZ9DCvgFSRuEUKcqgeh46FP95W0MMSeEIZGFXGZjtbh297PGr4LVksRiY5iLIlBuQ+TEY/MtHpOIeUV7Ucx/7M/6IRsckitV41AfCqDu/DHdwlnWfblLiuRJML/fws3GZt5+wzYutu4hbpKJWXazFbiTfh8GDA7MJrrFgYtqp6fuO0G7wV+xawbo1hsBzHVjZbG1A578s7WQrbTYMEpsN8+aR29028wSTjZeHs6rQdOXa+KZhs4/tPQ==
    username: AgAGd342yntlWCryYYWhxhzU5Bu+efm8QHn6f2HkCcKRU5oS4/IM+UJpGAyN490ob3Fh/IeeVXdsw84nLjYCIdwuevyjSuCZCAGXBv/IO1JN+uvXANHio0rZH4/dJ6TpbjPpYQHT52mHo6/p+cWafsdbigD/gmy16GVwYIxOokCmJglXMS8k51mxpfvvTuo65jBvLkLj0y2yVONFR0PchSNVfYVgr7H1H1TBWjJUBOLyMOF/6VkHnaQzOwap9bHakygHtG9FdXAO3hYTiAAPiT3vbtbXYBhoWQsNmBKpJtb7sqQ0/PQ8+3ePJKVn+JgbRYtvwDMKAQdz/u/9TUoVIJP/JgHWLDrDTbFPDjEGkag0iCqyTy7ugWmWOF2Wg9EqfWTdklCDaH/6OyYouMMiM4px9CYVd6Emcirhi0VatblcO8Uklpe8qHd6Adn0UMA9cRVwzbCUvcIiYiY3WN/T8qY53lRw7YM3y9HaVPGk49nLJ1bIJSNIgTXYxAh/ktQKHAZUcx/QgXH4Vdet1tK5PRyKQmWIhSwtpiMSwcQsN71cb5TRQYod1OkCsMwTlR2C5b9W+KIPWLBHNTc6ymndGU3NWMygARCWWmTk9e7wL2G/UZSFx/Lfxi2L2SQQ4X5KvGgA4J8Mp+7QYeacyzDdelxi6vdSv/X9Gj3UdAs78bDBKulYntsFQnuaZIWPyXmMaMlBm4jL
  template:
    metadata:
      creationTimestamp: null
      name: smbcreds
      namespace: default
    type: Opaque
