kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bitwarden-secret
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    BW_HOST: ENC[AES256_GCM,data:F/Ql0N9A/TXUUcpOOWuvNEvKzq2UJkbChPo=,iv:yPyuNShNjpS46nSEQ4SL25VRbRhgodJ6yMsWsBixeLU=,tag:UWldfIa+2rRCghNQwMeYuw==,type:str]
    BW_USERNAME: ENC[AES256_GCM,data:BdUoxHAqh07Prhy5cG6f,iv:lwjZS8nX6HOhx14DwqhyVMe9hFH8CFWxDhtHPTa0XE4=,tag:B6ZJP9tAl215T6E3tG71fQ==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:9uO70mxCm3iCPzPAQsgLdcxJ8w==,iv:yh/+ekpSu0jEG4MYcTULlLwsiIkafjO6WaWey9NyaGo=,tag:Mm/pS5J6Hn4c3OLOiggOFw==,type:str]
    BW_CLIENTID: ENC[AES256_GCM,data:di1L/MvDufF2POr+YSEpRCNvqT8lOvt3Vxn2LiNydCvmo3GTFmjDIFI=,iv:7y6ifRsk3pxPNtItigbk3g5L7IKhPxN7F7gAufEpAEs=,tag:RXVzOXGZnJT3TNsq8OePFg==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:EAC1MtAZTFcjfjBDOqg2yC+9MAs8dZkokQqM8XOi,iv:/IG05b88anLA2IrCcmBbqBtb8/z2HUgVUB9HeEyl+tI=,tag:d+lYttbNVy+RSxW5Y1SIQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTlc0dWRCM0U3VXhYZi83
            MFhabGFhcWcwdmNPSU12MkYxd0dKR2thaUc0Cmowai8vQ0dIYzkxMEFDZytLWkNs
            NkRzK2xObXA4MDBGSldoUVl1MnkreG8KLS0tIEF5d2hYZytYOGVGYW9wQUtoM1ZW
            YXA2a3ZxWUNWdWgycEtrb3MxUjNDWk0KEbicnO/dH+oxtbLGp9IaOueiaYFO15VX
            MQ/bqtJTN9PxjxWdmwVoOY2pUMtOpCHY9ZBTvlVSlqnP9hb0X1Xb/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T20:02:08Z"
    mac: ENC[AES256_GCM,data:DXyHMPvKQqu8hbNhpHyd7/KWmm51tylDzwHdqVDWCI0Dyvpiq31vir207w1EdYezk2k5d3kkEpIEoCZuKMVw5imTmHHndPViHkS6i/z3ZgMTXh0dezCUlOWPB3lTloiG0yU2uj8NkF5IpFjBbLW0TRUNPpoIVhGLYXFs/Y23iOU=,iv:TwtVYYIFGHBoy/+xbQn5hGiSwid/NnAhbx0WwvB9TjI=,tag:aorJdBTM/g9amK4nFVD/TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
