---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
      - secretKey: admin-user
        remoteRef:
          key: grafana-admin-secret
          property: username
      - secretKey: admin-password
        remoteRef:
          key: grafana-admin-secret
          property: password
