---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana
        property: username
    - secretKey: admin-password
      remoteRef:
        key: grafana
        property: password
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-oauth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_AUTH_OAUTH_AUTO_LOGIN: 'true'
        GF_AUTH_GENERIC_OAUTH_ENABLED: 'true'
        GF_AUTH_GENERIC_OAUTH_NAME: authentik
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: '{{ .grafana_client_id }}'
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: '{{ .grafana_client_secret }}'
        GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://auth.home.vijayakumar.xyz/application/o/authorize/
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://auth.home.vijayakumar.xyz/application/o/token/
        GF_AUTH_GENERIC_OAUTH_API_URL: https://auth.home.vijayakumar.xyz/application/o/userinfo/
        GF_AUTH_SIGNOUT_REDIRECT_URL: https://auth.home.vijayakumar.xyz/application/o/grafana/end-session/
        GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(groups, 'Grafana Admins')
          && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
  dataFrom:
    - extract:
        key: grafana
      rewrite:
        - regexp:
            source: (.*)
            target: grafana_$1
