# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chartRef:
    kind: OCIRepository
    name: grafana
    namespace: flux-system
  interval: 30m
  values:
    annotations:
      configmap.reloader.stakater.com/reload: grafana
      secret.reloader.stakater.com/reload: grafana-oauth-secret
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - disableDeletion: false
            editable: true
            folder: ''
            name: default
            options:
              path: /var/lib/grafana/dashboards/default
            orgId: 1
            type: file
          - disableDeletion: false
            editable: true
            folder: Ceph
            name: ceph
            options:
              path: /var/lib/grafana/dashboards/ceph
            orgId: 1
            type: file
          - disableDeletion: false
            editable: true
            folder: Flux
            name: flux
            options:
              path: /var/lib/grafana/dashboards/flux
            orgId: 1
            type: file
          - disableDeletion: false
            editable: true
            folder: Kubernetes
            name: kubernetes
            options:
              path: /var/lib/grafana/dashboards/kubernetes
            orgId: 1
            type: file
          - disableDeletion: false
            editable: true
            folder: Nginx
            name: nginx
            options:
              path: /var/lib/grafana/dashboards/nginx
            orgId: 1
            type: file
          - disableDeletion: false
            editable: true
            folder: database
            name: database
            options:
              path: /var/lib/grafana/dashboards/database
            orgId: 1
            type: file
          - disableDeletion: false
            editable: true
            folder: logs
            name: logs
            options:
              path: /var/lib/grafana/dashboards/logs
            orgId: 1
            type: file
    dashboards:
      ceph:
        ceph-cluster:
          # renovate: dashboardName="Ceph Cluster"
          datasource: Prometheus
          gnetId: 2842
          revision: 18
        ceph-osd:
          # renovate: dashboardName="Ceph - OSD (Single)"
          datasource: Prometheus
          gnetId: 5336
          revision: 9
        ceph-pools:
          # renovate: dashboardName="Ceph - Pools"
          datasource: Prometheus

          gnetId: 5342
          revision: 9
      database:
        crunchy-pgbackrest:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/pgbackrest.json
        crunchy-pod-details:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/pod_details.json
        crunchy-postgresql-details:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/postgresql_details.json
        crunchy-postgresql-overview:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/postgresql_overview.json
        crunchy-postgresql-service_health:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/postgresql_service_health.json
        crunchy-prometheus-alerts:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/prometheus_alerts.json
        crunchy-query-statistics:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/query_statistics.json
        dragonfly:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/dragonflydb/dragonfly/main/tools/local/monitoring/grafana/provisioning/dashboards/dragonfly.json
      default:
        cert-manager:
          # renovate: depName="Cert-manager-Kubernetes"
          datasource: Prometheus
          gnetId: 20842
          revision: 3
        external-secrets:
          datasource: Prometheus

          url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
        node-exporter-full:
          # renovate: dashboardName="Node Exporter Full"
          datasource: Prometheus
          gnetId: 1860
          revision: 37
        openbao:
          # renovate: dashboardName="OpenBao"
          datasource: Prometheus
          gnetId: 23725
          revision: 1
        smartctl-exporter:
          # renovate: depName="SMARTctl Exporter Dashboard"
          datasource:
            - {name: DS_PROMETHEUS, value: Prometheus}
          gnetId: 22604
          revision: 2
        volsync:
          # removate: dashboardName="VolSync Dashboard"
          datasource:
            - name: DS_PROMETHEUS
              value: Prometheus
            - name: VAR_REPLICATIONDESTNAME
              value: .*-bootstrap
          gnetId: 21356
          revision: 3
        zfs:
          # renovate: dashboardName="ZFS"
          datasource: Prometheus
          gnetId: 7845
          revision: 4
      flux:
        flux-cluster:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/cluster.json
        flux-control-plane:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/control-plane.json
        flux-logs:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/logs.json
      kubernetes:
        k8s-system-api-server:
          # renovate: dashboardName="Kubernetes / System / API Server"
          datasource: Prometheus
          gnetId: 15761
          revision: 17
        k8s-views-global:
          # renovate: dashboardName="Kubernetes / Views / Global"
          datasource: Prometheus
          gnetId: 15757
          revision: 42
        k8s-views-namespaces:
          # renovate: dashboardName="Kubernetes / Views / Namespaces"
          datasource: Prometheus
          gnetId: 15758
          revision: 41
        k8s-views-nodes:
          # renovate: dashboardName="Kubernetes / Views / Nodes"
          datasource: Prometheus
          gnetId: 15759
          revision: 32
        k8s-views-pods:
          # renovate: dashboardName="Kubernetes / Views / Pods"
          datasource: Prometheus
          gnetId: 15760
          revision: 34
        k8s-volumes:
          # renovate: dashboardName="K8s / Storage / Volumes / Cluster"
          datasource: Prometheus
          gnetId: 11454
          revision: 14
      logs:
        container-logs:
          # renovate: dashboardName="Container Log Dashboard"
          datasource: VictoriaLogs

          gnetId: 16966
          revision: 1
      nginx:
        nginx:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
        nginx-request-handling-performance:
          datasource: Prometheus
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/request-handling-performance.json
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - access: proxy
            isDefault: true
            jsonData:
              prometheusType: Prometheus
            name: Prometheus
            type: prometheus
            url: http://prometheus-operated.monitoring.svc.cluster.local:9090
          - access: proxy
            name: VictoriaLogs
            type: victoriametrics-logs-datasource
            url: http://victoria-logs-server.monitoring.svc.cluster.local:9428
          - access: proxy
            jsonData:
              implementation: prometheus
            name: Alertmanager
            type: alertmanager
            url: http://alertmanager.monitoring.svc.cluster.local:9093
        deleteDatasources:
          - name: Alertmanager
            orgId: 1
          - name: Prometheus
            orgId: 1
          - name: VictoriaLogs
            orgId: 1
    env:
      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_AUTH_BASIC_ENABLED: false
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /tmp/dashboards/home.json
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
      GF_EXPLORE_ENABLED: true
      GF_FEATURE_TOGGLES_ENABLE: publicDashboards
      GF_LOG_MODE: console
      GF_NEWS_NEWS_FEED_ENABLED: false
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: natel-discrete-panel,pr0ps-trackmap-panel,panodata-map-panel
      GF_SECURITY_COOKIE_SAMESITE: grafana
      GF_SERVER_ROOT_URL: https://grafana.${CLUSTER_DOMAIN}
    envFromSecret: grafana-oauth-secret
    grafana.ini:
      analytics:
        check_for_plugin_updates: false
        check_for_updates: false
        reporting_enabled: false
      news:
        news_feed_enabled: false
    imageRenderer:
      enabled: true
    persistence:
      enabled: false
    plugins:
      - grafana-clock-panel
      - grafana-piechart-panel
      - grafana-worldmap-panel
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - vonage-status-panel
      - victoriametrics-logs-datasource
    rbac:
      pspEnabled: false
    replicas: 1
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi
    route:
      main:
        enabled: true
        hostnames:
          - grafana.${CLUSTER_DOMAIN}
        parentRefs:
          - name: envoy
            namespace: network

    serviceAccount:
      autoMount: true
      create: true
    serviceMonitor:
      enabled: true
    sidecar:
      dashboards:
        enabled: true
        folderAnnotation: grafana_folder
        label: grafana_dashboard
        provider:
          disableDelete: true
          foldersFromFilesStructure: true
        searchNamespace: ALL
      datasources:
        enabled: true
        labelValue: ''
        searchNamespace: ALL
    testFramework:
      enabled: false
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: grafana
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
