uptime-kuma: cd /app && node server/server.js
tailscale-daemon: /usr/local/bin/tailscaled --port 41641 --state=mem: --tun=userspace-networking
tailscale: /usr/local/bin/tailscale up --accept-routes --advertise-exit-node --hostname=${FLY_APP_NAME} --advertise-tags=tag:fly-exit --authkey=${OAUTH_CLIENT_SECRET}?preauthorized=true && tail -f /dev/null
