---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-env
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: immich-env
    template:
      type: Opaque
      data:
        DB_URL: '{{ index . "uri" }}?sslmode=require&sslmode=no-verify'
        DB_VECTOR_EXTENSION: pgvector
        REDIS_HOSTNAME: immich-redis.media.svc.cluster.local
  dataFrom:
    - extract:
        key: postgres-pguser-immich
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-config-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: immich-config-tpl
            items:
              - key: immich.config.json
  dataFrom:
    - extract:
        key: immich
      rewrite:
        - regexp:
            source: "(.*)"
            target: "immich_$1"
