# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-env
spec:
  dataFrom:
    - extract:
        key: postgres-pguser-immich
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: immich-env
    template:
      data:
        DB_URL: '{{ index . "uri" }}'
        DB_VECTOR_EXTENSION: pgvector
        REDIS_DBINDEX: "0"
        REDIS_HOSTNAME: "dragonfly.database.svc.cluster.local"
      type: Opaque
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-config
spec:
  dataFrom:
    - extract:
        key: immich
      rewrite:
        - regexp:
            source: "(.*)"
            target: "immich_$1"
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: immich-config-secret
    template:
      templateFrom:
        - configMap:
            items:
              - key: immich.config.json
            name: immich-config-tpl
