---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Funnel Resources
  - ./proxyclass.yaml
  - ./luffy-exit-node.yaml
  - ./luffy-app-connector.yaml
