apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: &name luffy-exit-node
spec:
  exitNode: true
  hostname: *name
  subnetRouter:
    advertiseRoutes:
      - "10.0.0.0/16"
      - "172.16.0.0/12"
