apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-funnel
  namespace: selfhosted
  annotations:
    tailscale.com/funnel: "true"
    tailscale.com/proxy-class: "luffy-ts-proxy"
spec:
  defaultBackend:
    service:
      name: vaultwarden
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - vault
