---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-secret
  namespace: utils
  labels:
    encrypted-by: sops
    encryption-method: age
stringData:
  GOTIFY_DEFAULTUSER_NAME: ENC[AES256_GCM,data:e9Aokok=,iv:NKJO/NcW3KlVvmt7aUuqElq374ywm8VuzinRg/4aQ1U=,tag:R9AcdL3XrH98iFqXRZuBMg==,type:str]
  GOTIFY_DEFAULTUSER_PASS: ENC[AES256_GCM,data:ZaMt9/FF/KB+tS4=,iv:joufbVYPmsUmPZf/q9cy5BADpckUSVSw8uoqdIPw4NY=,tag:2xm/8KK5y7RgdqVuztXsYg==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArN0c1eno4eGR4VEgrTTBW
        OTllODlkSThrRzMreTQvVXphZVFDVG4yZTAwCmc4TUp6d1ZDMitaZkFWU0djTTlF
        a2t4MlpoWUQ3QUgxQVp4eVRrSXBpRjQKLS0tIHdIbGNRVnlpakcxR0dKVy9KVTBn
        RVhWb0Zlc3AwRkRacldBZm5VcENKNEkKSyqra8JC4dHv1sARSeM+Wh4WZLg0vF5+
        tBzNgCY9HX08RQ/VQ3BCYgUpj9J3xAO93plEe2nm15/Mr/IoE5bM+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-11-30T15:44:59Z'
  mac: ENC[AES256_GCM,data:ebfN91/iiF311RuSRIpSichdACyYXrsfp1T9DoDG59pC0/KlKZ+NMf0x5cz35CDMqdbqSwCkfwoC5cQ/bo+Shw/Dlo5xKOmeecVk2tk7dD5oblxh+cNh5QdwwdxE9Uw3tRMBmPlzN61CQhFRJ8EXKEtqfkLuf+Px606yGZZg0EE=,iv:btbDCvDGOl6ROQac0cv9pgmuhIbzkYGrtWVJ9Ipp1Ss=,tag:bs8qVBnMVzqlg72xdNSQFw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
