apiVersion: v1
kind: Secret
metadata:
    name: gotify-secret
    namespace: utils
    labels:
        encrypted-by: sops
        encryption-method: age
data:
    GOTIFY_DEFAULTUSER_NAME: ENC[AES256_GCM,data:vWoPrOc=,iv:GLkZ1eXUL18nTpg382lhMXgMmeq8ccE9RFY3kgqub+g=,tag:he6RnX2SurnmShJElmZgBA==,type:str]
    GOTIFY_DEFAULTUSER_PASS: ENC[AES256_GCM,data:JTXraVNcep6oVhA=,iv:2ZfZtDIF6HdESOGmRBEgIB5T0SmXR2RauiauHnJpELo=,tag:Myys2v7g+bLQ+GKdwqJqFA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArN0c1eno4eGR4VEgrTTBW
            OTllODlkSThrRzMreTQvVXphZVFDVG4yZTAwCmc4TUp6d1ZDMitaZkFWU0djTTlF
            a2t4MlpoWUQ3QUgxQVp4eVRrSXBpRjQKLS0tIHdIbGNRVnlpakcxR0dKVy9KVTBn
            RVhWb0Zlc3AwRkRacldBZm5VcENKNEkKSyqra8JC4dHv1sARSeM+Wh4WZLg0vF5+
            tBzNgCY9HX08RQ/VQ3BCYgUpj9J3xAO93plEe2nm15/Mr/IoE5bM+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T15:16:32Z"
    mac: ENC[AES256_GCM,data:JcCoLksPY6KcndlmhasiCP262GX8I/7n7alkzdIUcKXOZEtMocWVYFMUANQdi+VJ96BDUo6Oe+4+fuPXvox+AFQgHivi5tpPWblCvAzHbRWp2lSTzsMKwSBdKOJ8p4NZXfCGH/sgG+Bup9q5t8A/AaWxaZ7Rp3g5W6oyU+i49UQ=,iv:O6n+p5iyg3I1mt0sCAceNWA9YrxUzQHncJF2cl4TLM4=,tag:1pygpwR8RwGv/FQNDsTqug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
