apiVersion: v1
kind: Secret
metadata:
  name: gotify-secret
  namespace: utils
  labels:
    encrypted-by: sops
    encryption-method: age
data:
  GOTIFY_DEFAULTUSER_NAME: ENC[AES256_GCM,data:vi/yFlhWtvQ=,iv:gmvpyfLYv/3I22iPV2IkezQx4RiU2IXz0u53v2Ac7U4=,tag:qXUjVfIItnRfRx45QW1viw==,type:str]
  GOTIFY_DEFAULTUSER_PASS: ENC[AES256_GCM,data:EVSv27UoVNs=,iv:17qrGOJaKsqSZR6/RH2S9JqZPfG6bVEd+A7C9SLXSkA=,tag:6MfzTsUGhXvR7N6OLyNSJw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19654hupmjy08ge0xu43mynjca5wmrd3kmlt7wsja582waanvf4uqvv65ya
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM2hlNllRazZiYjJrV0Yv
        b2RwMW1PRHI2Tmh0TlBBZGRLKzdMR3RsdGg0CldYNjB0cnlWK0ZsTktKaDNCdkVq
        WlBOUjk2K3BLd1VmSTBQRmdQdi9lK0EKLS0tIENIZjgwR0RteTRLTVFsVHRZT0dL
        RWdzME5vZ2c4a1hpMGF4dVEySDFESEkK3oc/kCv+xnhlZ34mCuZvSzcgsa0ORKYW
        jz/seRFJYiko/HnSRLxgUB2MTLMtFVgB+3I+RnPwAt/wvaCUHjkEew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-11-02T20:57:06Z'
  mac: ENC[AES256_GCM,data:HwD/XGUeTrs0qi5BoI7G+bI8WVBFXbExLcKTsnanz8VCi7z6m9PDU8aO93ABfpcquWF453sEPulp/ztzqV6LV00s1v/yi/vOXkgWN5GtRDiutJlXR1Oh0qMTbVskNOIS28319GENuAW7Gk80z8M4bAS9+S6og+V7AR5pQ25QWgc=,iv:kFG09yCakEzWfZVkP8mIl1nfNNXiJvY+fcbPhOJkB28=,tag:3g2iwTtfg3GF3hZoZgoIzw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
