apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitors
stringData:
    admin-user: ENC[AES256_GCM,data:x3Vq1oc=,iv:vKr0VyCOr83e3McAnstDc9ifg/ZHR3a6N1lmWuQvwuo=,tag:mNu3447pvi59KwocJ5VTxg==,type:str]
    admin-password: ENC[AES256_GCM,data:gUkgYpDuXpZJhVw=,iv:g8IfTeRAF+w96LIKt9nPFdeVL4wro3efsGv9Jd2akLk=,tag:5KFqBgmuH3/YLSYDrRmUcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cndyqzwsajzxrhkj2l04hrnde90gj26klkl85emck3zc28fzlfys8cta9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoejhPSUUxQnVzSXg1Z3VE
            NGNUOXZrNkhEbjZjaW1SZ2Z5b2lwbWtlMm5rCnVLSnpIOTM2L2Q5MGtTZjB4Y2xm
            c21rcFQ1NmppL05XK1FaT21Vb0RsK28KLS0tICtvNUQ0eGErQ3VUTnE4blBTei9K
            V2ZLaW1JR3ovUWgwRVJhZWlhblNpTW8Ky+6PTit0a+W9gCAE9nJOXavFPyJfo2mj
            EEPi0nsUUHC9tubEiyhotg4rDhnySKyTNIDq+NFh0m/JWQnShcT4MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T12:52:31Z"
    mac: ENC[AES256_GCM,data:wBe6x7+fhAPG0AQl/UmlIXQrqV+PmtEiDVu0Y5zUpc6kwI9HfIZzk09E+La8Qo0T/l2eix8S7L337NUftpC3q3mbNlH1mmSp9kpcmpLgKMT4pHp15LsSzhUIlJulBOy5f/RlxNPIm+WnsutY2nRJs2Zop33KVUG+lnucBylUEro=,iv:qH1NS5MoAt/RErow0cNxAlh20yWJMjYi7Cl+xa/8LPM=,tag:FbTl5pQOnlgwd1ZKOhOczA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
