---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitors
spec:
  encryptedData:
    admin-password: AgC0XRSKUY0IL/JnCkGj1bJYhFRkW6sSkqtM3zAHTmnoCr9nwhzupf7xjfYwIL5GUS5IMDh3WTFfEGObGtGwCSWNMqAk/wEE/CMAISx1hMJXvfYx/23xEeIcoA3HiJFP/KF+08PqJukhFdy642HQ8e/Uw1baEPQwahX2nlIJpfMW69vhFYwP+BmQ1KkshHWDsCHLoVfnMltDkClDr3/1moz4pHFmtk8cGBCq7GtRjPdTJL6u57n8IleM+CBJsp8pqCzx+hvVcEa0hQg/ULDnUNJ6Kb1iZfuerLxVLf4PwBHinbmXOQ1bNh+8kC+IWJPueVZN/76poBZaTaWYwG+OGA6i01t/6WC9Sc2Cw9Z1iJQNhZkOxkPX7OCott4sYDN0Vpj4q7LtkxSMaNIUqUSoEZ0cJo6UgckKCozn0Ikh0XV+Z+vU30HvL6Nw+B/asvlNGyGjTneVaMmZpptfLTVSx0oslH55NS4rRw4p8nZMho2egXMjPQ/lMWs4uZXyw6tzr7GjB+OWGAUItRqS0aOGK8CkBMbAq/8MelUjnXsVycKjT2l/RYHITDN3sSV+Ke648FaMsqWaGCpic8vuwBZZ0Sor/NPKd2MTiDU7C5ektnHNHGcdarrajbeoqLN+eYE7vwdC8B2jTNGk979qoIdlofb/45kUGd4/fnG1nth9HBWcUwTaPJtDAJzcLf6tlv7KedoholFp+9MTHl4EkQ==
    admin-user: AgAN2mMUDlS4pI/nlDuz9vBE1OC6I8TNbVm+y3jro3bfGH1tC/LzSLG9CVRZ05MGESDYcJZj98knq7I+uFCaay8oWCjAEKQE7LIcbwjOPMvPMQem9r9qexIUbMDdeKbyj9RJFWbsu4FNL00OhxMKXo8fK10Qz/NjLih4rpzc93H2d9W8vudL3esN8FIMG7fE0C+jRQ495aW+6a7VwE33JQkFR9Pml9K4Y7lyGuBwvbMOUuRT0b3qHRigfEzseCZxXsBx2SIBMHri7VpBnypE5Qd4Wb+FSvNYKLEpUhf+WaST8jEYRx9EmW/7gjwCfS0/6obaD5QHuITXT4/8a0rpUURfn+Kav+a/lyFw49dBnHBm2l91HBLU5OazkG3H2s1cKqv4j4AzZgxtHgHjffhRGxPrHTGRfgEbmWe5jUACFxoPQ9Ax7VoA3n/A7b0n7E4UYSot1UWKGhQVwnZV0k8rjL3uuXjHuGVvHfBBHEQdFcjvvaAKyeJDnKnAsAh0qmr8A/ZhPFlrNWKFkJHUM7fvzZHn5+0KSbcjoE8DMjcXbQJ0Uyky1LleK1niCXmI9SE0VJLyI2lIAIocRg7Go80XC8eh092cuZwds8+Lr5sG39Xl7fP3BeW3jfgPR/iFbyMg8yX1uJyliNSLlq/wayrD5V8UTji92iLCHYznZmIfk67whw1dztiaRphuTcvroCGOguPSlRHbnw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitors
