---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-secret
spec:
  data:
    - remoteRef:
        key: radarr
        property: api_key
      secretKey: RADARR_API_KEY
    - remoteRef:
        key: sonarr
        property: api_key
      secretKey: SONARR_API_KEY
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: recyclarr-secret
