apiVersion: v1
kind: Secret
metadata:
    name: recyclarr--secret
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:LtDv0ZBbCkvBr9L0SfOioGORLfDShap8q5qPOep4lMA=,iv:gvsa2nelf6Pp34i+Fjt7SxVNzSvMwouT7BRoKkUmsds=,tag:s+/JQ1lNgwnBWPE3ZxvydA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:x8ETqf2tmrHLjA0LtljsqVjVWFmGGCI6I1v9FOmMpWU=,iv:fWTkKndGNL1rcXh0QC/JxgtK+KrhyevMcBYJAOtTWtg=,tag:jwCq9ompxCjwPS6iDDENyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbDZ6N3NlSGU2NmJNWUJz
            YlE1d0xTU1NFNjNmVjV3dzdEOVZOSklkN0VnCjlFcGtYNTNVSHlmM3E0bHRZNFNw
            cU1IeGxWYTNDckcrbFZSL29Rai90aFUKLS0tIGtNYWN4MERiQTR1NDhoV1ZLdXY2
            YnBWSDhTa1Rqcy9YVmdWMERBeFBMWjgKHyzWFAU8d9yOmxt+ORTTWqLiv9pPDhbI
            vG9oM3fRKTfoSy1fhdU1qcLVRMJN1HWykqFoCRjq3SjBbuEId+OiXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-03T17:50:06Z"
    mac: ENC[AES256_GCM,data:JvpaVyCZ/rSsGGddlZsdDQbd1pbF+BvcAxI7UKFjQm8mKJGPPZdmx7IBstshY15kpAnKXUjSw7i3gkv+YjSLmTEzkCNXEy1duXea81Uzdpd10kwUqx/bNt9YhaV4tAotdT+jRkbunA7e6W+o5bX5rwxMqq/26lpIL0PEYAjJXig=,iv:n/tnMFtJGlOc4/0AgWm7QRGCT14PCWQcYlTW+JMf+Wg=,tag:valtxBSgWHpY2fLCJjH6aQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
