apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:f4r93ZgPuXZPC+9E989+WF9HoQJu9a+fNQxXx+8isAM=,iv:g9V2nj+lOLGKrQ7sfdl9MXltZanHHUhx7vGuot3bCas=,tag:pw+F5qLQSsRED5O3RNk4Gg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:x8ETqf2tmrHLjA0LtljsqVjVWFmGGCI6I1v9FOmMpWU=,iv:fWTkKndGNL1rcXh0QC/JxgtK+KrhyevMcBYJAOtTWtg=,tag:jwCq9ompxCjwPS6iDDENyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbDZ6N3NlSGU2NmJNWUJz
            YlE1d0xTU1NFNjNmVjV3dzdEOVZOSklkN0VnCjlFcGtYNTNVSHlmM3E0bHRZNFNw
            cU1IeGxWYTNDckcrbFZSL29Rai90aFUKLS0tIGtNYWN4MERiQTR1NDhoV1ZLdXY2
            YnBWSDhTa1Rqcy9YVmdWMERBeFBMWjgKHyzWFAU8d9yOmxt+ORTTWqLiv9pPDhbI
            vG9oM3fRKTfoSy1fhdU1qcLVRMJN1HWykqFoCRjq3SjBbuEId+OiXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-03T18:48:23Z"
    mac: ENC[AES256_GCM,data:eFSjR9iizEs2KlHT63tu088jEza1yIpu2rVXpiaDJs24cZJkH7A2fg0ElU5Np8/CQXbeJFCpYywlxuJv1qeHvhiQWI6tgaB7w9XZlulDS4bFITcPfoJwmdX20k55cbOV+0irEQjBFeYeZQ/4GzKKj4GI/2W1+PUM99rxzbPEFAs=,iv:0N2Yub8xzAynpa57tByoIx7VYKpAJ4DqFAnZkE2gRWA=,tag:mRsivdgyTYSz3C6Z+obD+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
