---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-rest"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: "${APP}-volsync-rest"
    creationPolicy: Owner
    template:
      data:
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        RESTIC_REPOSITORY: "{{ .RESTIC_REST_REPOSITORY_TEMPLATE }}/${APP}"
        RESTIC_REST_USERNAME: "{{ .RESTIC_REST_USERNAME }}"
        RESTIC_REST_PASSWORD: "{{ .RESTIC_REST_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-template
