---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dnsproxy-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: dnsproxy-config
    template:
      type: Opaque
      data:
        config.yaml: |
          bootstrap: ["1.1.1.1:53"]
          fallback: ["1.1.1.1:53"]
          listen-addrs: ["0.0.0.0"]
          listen-ports: [53]
          max-go-routines: 0
          ratelimit: 0
          ratelimit-subnet-len-ipv4: 24
          ratelimit-subnet-len-ipv6: 64
          udp-buf-size: 0
          timeout: 10s
          cache: true
          http3: true
          upstream: [{{ .dnsproxy_upstreams }}]
  dataFrom:
    - extract:
        key: dnsproxy
      rewrite:
        - regexp:
            source: '(.*)'
            target: 'dnsproxy_$1'
