---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./default.yaml
  - ./namespace.yaml
  - ./helmrelease.yaml
  - ./dashboard/traefik-dashboard-auth.sops.yaml
  - ./dashboard/ingress.yaml
  - ./dashboard/middleware.yaml
