---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miroir
spec:
  chartRef:
    kind: OCIRepository
    name: miroir
  interval: 30m
  values:
    nodes:
      chopper: &node_cfg
        backend: lvmthin
        device: /dev/sda
      usopp: *node_cfg
      zoro: *node_cfg
    replicatedStorageClass:
      create: true
      isDefault: true
      name: miroir-replicated
      quorum: last-man-standing
    storageClass:
      create: true
      isDefault: false
      name: miroir-local
    volumeSnapshotClass:
      create: true
      name: miroir-snap
