---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chart:
    spec:
      chart: cilium
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.20.1
  interval: 30m
  values:
    externalIPs:
      enabled: false
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList: ["10.244.0.0/16"]
        clusterPoolIPv4MaskSize: 24
        clusterPoolIPv6PodCIDRList: ["fd10:244::/56"]
        clusterPoolIPv6MaskSize: 64
    ipv4:
      enabled: true
    ipv6:
      enabled: true
    k8sServiceHost: "127.0.0.1"
    kubeProxyReplacementHealthzBindAddr: "[::]:10256"
    l2announcements:
      enabled: false
    dashboards:
      annotations:
        grafana_folder: Cilium
      enabled: true
    endpointRoutes:
      enabled: true
    envoy:
      enabled: false
    gatewayAPI:
      enabled: false
    hubble:
      enabled: false
    k8sClientRateLimit:
      burst: 32
      qps: 28
    k8sServicePort: 7445
    kubeProxyReplacement: true
    loadBalancer:
      algorithm: maglev
    operator:
      replicas: 1
      dashboards:
        annotations:
          grafana_folder: Cilium
        enabled: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    rollOutCiliumPods: true
    securityContext:
      seLinuxOptions:
        type: spc_t
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - PERFMON
          - BPF
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    socketLB:
      hostNamespaceOnly: true
