---
title: Vijay's Homepage
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50
favicon: https://vijayakumar.xyz/favicon.png
theme: dark
color: slate
target: _blank
layout:
  - Dashboards:
  - Services:
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
hideVersion: true
showStats: true
providers:
  longhorn:
    url: http://longhorn-frontend.longhorn-system.svc.cluster.local
