apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
stringData:
    api_key: ENC[AES256_GCM,data:iM8wmbnxnxjzqVdw47v+tWgYnl3IPnmyOORBtGQBnzM=,iv:M61ccNPPPzdHJUTTsDRQXDbQerqpIC/equ2LWWG6DVM=,tag:uJhn9yYHy0KKyhoL66eJ9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2KzV1eU1SNWxIS1plTFNX
            WHhtaVlBY0RjUVZMcWVUWFU0REV6d3pXcnhZCkxrbjd2NGlkUjVsVHc2bW9haVZS
            c1dxUXdZeHZmWk84aUpJWjdDanFTYkEKLS0tIHJTdjQzdzRra2FWZm5kUDR5M3hD
            UzAvbnowWEl3eWRRanZlQ3F5d2h6aUEKS8NxVAezFA23CxchKN6/6/flkl48Xdzj
            exyBcRqbH10S67QA0OAq0ZtS2PHqj/lDkax6Gf1pCcXCZ4KkzorVVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-03T17:16:55Z"
    mac: ENC[AES256_GCM,data:ULPrl+4JY6Vj00exoTOUelx8x2Gx+skkvYHHHxZV5B3mZOZpzlU8XqpN/JCe2R9gyDsof7AWCBg+JClEAkuE1JNZT2Kzoy4LtvQBiuXkG8ShnG0TuszkretpD9OT9bmc/4hgHzi++08LfTgZfnJcyhDG4nT0/FhgxwRncLnVimw=,iv:RJpLZ6bjaxsOY6eQofBmzGOapNU+0UCnLv6b0gi5OEk=,tag:bbEoyIqNS249RYuo9Uzulw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
