---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc
  namespace: downloads
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
