apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./issuers/sealed-secret.yaml
  - ./helmrelease.yaml
  # # production
  # - ./issuers/letsencrypt-production.yaml
  # - ./certificates/production/home-vijayakumar-xyz.yaml
  # - ./certificates/production/certificate-reflector.yaml
  # staging
  - ./issuers/letsencrypt-staging.yaml
  - ./certificates/staging/home-vijayakumar-xyz.yaml
