# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-secret
spec:
  dataFrom:
    - extract:
        key: forgejo
      rewrite:
        - regexp:
            source: "(.*)"
            target: "FORGEJO_$1"
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: forgejo-secret
    template:
      data:
        # App
        FORGEJO__security__INTERNAL_TOKEN: "{{ .FORGEJO_INTERNAL_TOKEN }}"
        # S3
        FORGEJO__security__SECRET_KEY: "{{ .FORGEJO_SECRET_KEY }}"
        FORGEJO__storage__MINIO_ACCESS_KEY_ID: "{{ .FORGEJO_AWS_ACCESS_KEY_ID }}"
        FORGEJO__storage__MINIO_BUCKET: "forgejo"
        FORGEJO__storage__MINIO_ENDPOINT: "{{ .FORGEJO_AWS_ENDPOINT }}"
        FORGEJO__storage__MINIO_LOCATION: "us-east-1"
        FORGEJO__storage__MINIO_SECRET_ACCESS_KEY: "{{ .FORGEJO_AWS_SECRET_ACCESS_KEY }}"
        FORGEJO__storage__MINIO_USE_SSL: "true"
        FORGEJO__storage__STORAGE_TYPE: minio
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db-secret
spec:
  dataFrom:
    - extract:
        key: postgres-pguser-forgejo
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: forgejo-db-secret
    template:
      data:
        FORGEJO__database__DB_TYPE: "postgres"
        FORGEJO__database__HOST: "{{ .host }}"
        FORGEJO__database__NAME: "{{ .dbname }}"
        FORGEJO__database__PASSWD: "{{ .password }}"
        FORGEJO__database__USER: "{{ .user }}"
      type: Opaque
