---
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: flux-system
data:
  address: ENC[AES256_GCM,data:5VXnpTsXM1ou06eHwiuJUZenaYBRrFlXq5DBIpA/NIzkPaHUxO8pvVIaMi+7cOY59BPtkiifj/A5/zHOoMXFyl6Up27q3F0YaM9MKlNPQGwpcyEWZkgYUp7byA6LzFLhClRAWnCEWRYFzkM3SqKUIP1RlLi8RQ2Xuw2/NIp8X1E93bRDFbJbGYitSmxtPwvCs20yRb47Vk62ynp87txBbOEzS+k=,iv:XuoZ1AeGJC5q7fxzQGwqVhIrvVunn+SPICpF59s3RqA=,tag:RvrLl1CoIfbKtnVsNy3NeA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OHNoR2dZd0JsejJkMVk2
        ZXFyMjB5cVUweFd1Q3NnY2tKSDdaQnYzODJVClpXMFovZzh5Y0VhZ3h0WTVhTWtV
        RGpWMCtIYkV0VXU4YzRpNGF3anJMNWcKLS0tIGpyZkJuMHdodTl6RU9hei9yN3dW
        aVV3WHlZajNKaXI2WXlaaC9lbjdiMzAKOKVcEt6E6KbcO51PUQRtB8GoX8HGkijY
        Rziiv72RY750KJ4oiAdPtdXBCbBCL3v/TdZ6cQFyrp2yZWXcteSGsg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-12-27T17:20:31Z'
  mac: ENC[AES256_GCM,data:JprGXQSSCYXZ88yOPoxBkvkPuHNNz1KPYDp6DpiLrH3h3Nn68lZqfkdM21Qz5B0hsWN7jDCEPvBPTAnecxumhxeyksIYT26wLUs2TBawtpKT2sB1lrf2xc40wdSaI5XOnTcaelp5Rq1iO1VASX94SFvGVXAyRB9iVuLrMU8RM7U=,iv:LyJtr849Sd07q8GZqJBz3GuNmKnV78l1VmRNfDWDaCc=,tag:YQylB1VElRy9IgomhzHpdA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
