---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - notification.yaml
  - notification.sops.yaml
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: flux-system
      namespace: flux-system
    patch: |-
      [
        {
          "op": "add",
          "path": "/spec/decryption",
          "value": {
            "provider": "sops",
            "secretRef": {
              "name": "sops-keys"
            }
          }
        },
        {
          "op": "add",
          "path": "/spec/interval",
          "value": "60m0s"
        },
        {
          "op": "add",
          "path": "/spec/timeout",
          "value": "60m0s"
        },
        {
          "op": "add",
          "path": "/spec/retryInterval",
          "value": "2m0s"
        },
        {
          "op": "add",
          "path": "/spec/wait",
          "value": true
        }
      ]
