---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 90.0.0
  install:
    crds: Skip
  interval: 30m
  timeout: 15m
  upgrade:
    crds: Skip
  values:
    alertmanager:
      enabled: false

    cleanPrometheusOperatorObjectNames: true

    # ##
    # ## Component values
    # ##
    crds:
      enabled: false
    grafana:
      enabled: false
      forceDeployDashboards: true
      sidecar:
        dashboards:
          annotations:
            grafana_folder: Kubernetes

    # ##
    # ## Prometheus operator values
    # ##
    kubeApiServer:
      enabled: true
      serviceMonitor:
        metricRelabelings:
          # Drop high cardinality labels
          - action: drop
            regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket
            sourceLabels: ["__name__"]
          - action: drop
            regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket)

            sourceLabels: ["__name__"]
    kubeControllerManager:
      enabled: false

    kubeEtcd:
      enabled: false

    kubeProxy:
      enabled: false

    kubeScheduler:
      enabled: false

    kubeStateMetrics:
      enabled: false

    kubelet:
      enabled: true
      serviceMonitor:
        metricRelabelings:
          # Drop high cardinality labels
          - action: labeldrop
            regex: (uid)
          - action: labeldrop
            regex: (id|name)
          - action: drop
            regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)

            sourceLabels: ["__name__"]
    nodeExporter:
      enabled: false

    prometheus:
      prometheusSpec:
        alertingEndpoints:
          - apiVersion: v2
            name: alertmanager
            namespace: monitoring
            port: 9093
        enableAdminAPI: true
        enableFeatures:
          - auto-gomaxprocs
          - memory-snapshot-on-shutdown
          - new-service-discovery-manager
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        replicaExternalLabelName: "__replica__" # must match with thanos value `.query.replicaLabel[0]`
        replicas: 1
        resources:
          limits:
            memory: 2000M
          requests:
            cpu: 100m
        retention: 14d
        retentionSize: 50GB
        ruleSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        scrapeInterval: 1m # Must match interval in Grafana Helm chart
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 55Gi
              storageClassName: ceph-block
        walCompression: true
      route:
        main:
          enabled: true
          hostnames:
            - prometheus.${CLUSTER_DOMAIN}
          parentRefs:
            - name: envoy
              namespace: network

    prometheusOperator:
      prometheusConfigReloader:
        # resource config for prometheusConfigReloader
        resources:
          limits:
            memory: 32M

          # ##
          # ## Prometheus instance values
          # ##
          requests:
            cpu: 5m
            memory: 32M
      resources:
        limits:
          memory: 326M

        requests:
          cpu: 35m
          memory: 273M
