---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: luffy.vijayakumar.xyz
spec:
  secretName: luffy.vijayakumar.xyz-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.luffy.vijayakumar.xyz"
  dnsNames: ["*.luffy.vijayakumar.xyz"]
