---
kind: ConfigMap
apiVersion: v1
metadata:
  name: vaultwarden-env
data:
  ADMIN_SESSION_LIFETIME: "3"
  DATABASE_MAX_CONNS: "10"
  DB_CONNECTION_RETRIES: "15"
  DOMAIN: "https://vault.luffy.vijayakumar.xyz"
  DOMAIN_NAME: "vault.luffy.vijayakumar.xyz"
  EMAIL_ATTEMPTS_LIMIT: "3"
  EMAIL_CHANGE_ALLOWED: "true"
  EMAIL_TOKEN_SIZE: "6"
  EMERGENCY_ACCESS_ALLOWED: "true"
  EXTENDED_LOGGING: "true"
  ICON_BLACKLIST_NON_GLOBAL_IPS: "true"
  ICON_DOWNLOAD_TIMEOUT: "20"
  ICON_SERVICE: "bitwarden"
  INVITATIONS_ALLOWED: "true"
  IP_HEADER: "X-Forwarded-For"
  LOGIN_RATELIMIT_MAX_BURST: "5"
  LOGIN_RATELIMIT_SECONDS: "60"
  LOG_FILE: "/data/vaultwarden.log"
  LOG_LEVEL: "info"
  ORG_CREATION_USERS: "all"
  ORG_EVENTS_ENABLED: "false"
  ORG_GROUPS_ENABLED: "false"
  PASSWORD_HINTS_ALLOWED: "true"
  PUSH_ENABLED: "true"
  RELOAD_TEMPLATES: "false"
  REQUIRE_DEVICE_EMAIL: "true"
  ROCKET_ADDRESS: "0.0.0.0"
  ROCKET_PORT: "8080"
  ROCKET_PROFILE: "release"
  ROCKET_WORKERS: "50"
  SENDS_ALLOWED: "true"
  SHOW_PASSWORD_HINT: "true"
  SIGNUPS_ALLOWED: "false"
  SIGNUPS_DOMAINS_WHITELIST: "vijayakumar.xyz"
  SIGNUPS_VERIFY: "true"
  SIGNUPS_VERIFY_RESEND_LIMIT: "3600"
  SIGNUPS_VERIFY_RESEND_TIME: "3600"
  SMTP_AUTH_MECHANISM: "login"
  SMTP_FROM: "no-reply@vijayakumar.xyz"
  SMTP_FROM_NAME: "Vaultwarden"
  SMTP_PORT: "587"
  SMTP_TIMEOUT: "15"
  SSL_CERT_DIR: "/etc/ssl/certs"
  TZ: "Asia/Kolkata"
  USE_SYSLOG: "false"
  WEBSOCKET_ENABLED: "true"
  WEB_VAULT_ENABLED: "true"
  EXPERIMENTAL_CLIENT_FEATURE_FLAGS: "fido2-vault-credentials,ssh-agent,ssh-key-vault-item,autofill-v2,autofill-overlay"
