---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: vaultwarden-db
    template:
      type: Opaque
      data:
        DATABASE_URL: '{{ index . "uri" }}?sslmode=require'
  dataFrom:
    - extract:
        key: postgres-pguser-vaultwarden
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: vaultwarden-secrets
    template:
      type: Opaque
      data:
        ADMIN_TOKEN: "{{ .vaultwarden_admin_token }}"
        DUO_HOST: "{{ .vaultwarden_duo_host }}"
        DUO_IKEY: "{{ .vaultwarden_duo_ikey }}"
        DUO_SKEY: "{{ .vaultwarden_duo_skey }}"
        SMTP_HOST: "{{ .vaultwarden_smtp_host }}"
        SMTP_PASSWORD: "{{ .vaultwarden_smtp_password }}"
        SMTP_USERNAME: "{{ .vaultwarden_smtp_username }}"
        PUSH_INSTALLATION_ID: "{{ .vaultwarden_push_installation_id }}"
        PUSH_INSTALLATION_KEY: "{{ .vaultwarden_push_installation_key }}"
  dataFrom:
    - extract:
        key: vaultwarden
      rewrite:
        - regexp:
            source: "(.*)"
            target: "vaultwarden_$1"
