# fly.toml app configuration file generated for authfly on 2025-05-28T09:46:34+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'authfly'
primary_region = 'syd'
kill_signal = 'SIGINT'
kill_timeout = '5s'
swap_size_mb = 512

[experimental]
auto_rollback = true

[build]
dockerfile = 'Dockerfile'
[env]
PGID = "1000"
PUID = "1000"
UI_CONFIG_DISABLED = "true"
DB_PROVIDER = "postgres"
ANALYTICS_DISABLED = "true"
TRUST_PROXY = "true"
EMAILS_VERIFIED = "true"
ACCENT_COLOR = "#0089E9"
SMTP_TLS = "starttls"
SMTP_PORT = "587"
EMAIL_LOGIN_NOTIFICATION_ENABLED = "true"
EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED = "true"
LDAP_ENABLED = "true"
LDAP_URL = "ldap://localhost:3890"

LDAP_SKIP_CERT_VERIFY = "true"
LDAP_SOFT_DELETE_USERS = "true"
LDAP_ATTRIBUTE_USER_UNIQUE_IDENTIFIER = "uuid"
LDAP_ATTRIBUTE_USER_USERNAME = "user_id"
LDAP_ATTRIBUTE_USER_EMAIL = "mail"
LDAP_ATTRIBUTE_USER_FIRST_NAME = "first_name"
LDAP_ATTRIBUTE_USER_LAST_NAME = "last_name"
LDAP_ATTRIBUTE_USER_PROFILE_PICTURE = "avatar"
LDAP_ATTRIBUTE_GROUP_MEMBER = "member"
LDAP_ATTRIBUTE_GROUP_UNIQUE_IDENTIFIER = "uuid"
LDAP_ATTRIBUTE_GROUP_NAME = "cn"
LDAP_ATTRIBUTE_ADMIN_GROUP = "lldap_admin"

[[mounts]]
source = 'id_data'
destination = '/app/data'
snapshot_retention = 60

[http_service]
internal_port = 5000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
