---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /media
    server: 10.0.0.3
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-pvc
  namespace: immich
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Gi
  volumeName: immich-pv
  storageClassName: ''
# Immich Machine Learning Persistent Volume Claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-cache-pvc
  namespace: immich
  labels:
    app: immich-machine-learning
    app.kubernetes.io/instance: immich-machine-learning
    app.kubernetes.io/name: immich-machine-learning
spec:
  accessModes: [ReadWriteMany]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
