---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: pgadmin
  namespace: database
spec:
  dataVolumeClaimSpec:
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 1Gi
  serverGroups:
    - name: supply
      postgresClusterSelector: {}
  config:
    settings:
      AUTHENTICATION_SOURCES: ["oauth2"]
      OAUTH2_AUTO_CREATE_USER: true
    oauthConfigurations:
      - name: "pocketid"
        secret:
          name: pgadmin-oauth
          key: 00-pocketid.json
