---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  values:
    defaultPodOptions:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
    controllers:
      home-assistant:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 65533
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 65533
            runAsUser: 65534
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.5.1
            env:
              VENV_FOLDER: /venv
            resources:
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.0.1.5
        ports:
          http:
            appProtocol: kubernetes.io/wss
            port: 8123
          bridge:
            port: 21064

    route:
      app:
        hostnames:
          - hass.${CLUSTER_DOMAIN}
        parentRefs:
          - name: envoy
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 8123

    persistence:
      config:
        existingClaim: home-assistant-config
        advancedMounts:
          home-assistant:
            app:
              - path: /config
      hass-cache:
        existingClaim: hass-cache
        advancedMounts:
          home-assistant:
            app:
              - path: /venv
                subPath: hass-venv
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /tmp
                subPath: hass-tmp
