apiVersion: v1
kind: Secret
metadata:
  name: bao-role-secret
  labels:
    encrypted-by: sops
    encryption-method: age
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UDhma3gvQTJrRXpSWmt5
        SU85eG1oelV4a2srVTVrTlVWdGovMWJJeTFFCnZKZmpEK0lNV3N5OFhEc0hSSUhq
        cENva3Q3VXJaeDF4YnFVeEJSemFSb0kKLS0tIEs1S3JUakw1SjJibDlFS2J4Uktl
        bVpkaWw1SUhHTUZkbS9pUU5OVkxBUXcKDm0lZgx692ZIw4NabYbEN440NeaacJ+6
        xyyyXUOelk7IYcu7m6FLGnb7kNkRmvesymwpvCZtAgerAxUiAiNwUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-03-05T04:34:31Z"
  mac: ENC[AES256_GCM,data:H/BMgdWm3JRJY5trWLIg5QUH+bakcqDXlHEOplXH9i7SPMV8dAcSAOUIYlUCRxsg5eXqCclNFESqW6UVRMOrV+6328x6HFEj/k1YZi+aVVi9H4W7KDzh/+UVvOcCemgQtmEIzChZ2ZTR6ywbPm9tvwWdHO6uptgVhpc1ZSx4WX8=,iv:P7rQpKT5rXa+KioR/xzbHX+z8cPqoHA1cyvxqN9AWRM=,tag:Yg2RiMYfvMytP1xoNkns2Q==,type:str]
  version: 3.11.0
stringData:
  secret-id: ENC[AES256_GCM,data:5mDkcNWTHxpp8C7sqkzfeODckbDU0zpcbkA5el1Dm9H5JYmV,iv:zvYjfWiWLuj8BwZgotL00G06htIpQDdK4r5yN0TTVd4=,tag:ir1dc3ohic5I4nwbys+S4Q==,type:str]
type: Opaque
