apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bao
spec:
  provider:
    vault:
      auth:
        appRole:
          path: approle
          roleId: ${BAO_ROLE_ID}
          secretRef:
            key: secret-id
            name: bao-role-secret
            namespace: security
      path: thousand-sunny
      server: ${BAO_ADDR}
      version: v2
