---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: alertmanager-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        pushover_api_token: "{{ .ALERTMANAGER_PUSHOVER_API_TOKEN }}"
        pushover_api_userkey: "{{ .ALERTMANAGER_PUSHOVER_API_USERKEY }}"
  dataFrom:
    - find:
        path: ALERTMANAGER_
