# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
spec:
  data:
    - remoteRef:
        key: pushover
        property: alertmanager_token
      secretKey: pushover_api_token
    - remoteRef:
        key: pushover
        property: userkey_vijay
      secretKey: pushover_api_userkey
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: alertmanager-secret
