---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname percona-postgres-operator
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  path: ./kubernetes/luffy/apps/database/percona-postgres-operator/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: database
  timeout: 10m
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname percona-postgres-cluster
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: percona-postgres-operator
    - name: external-secrets
    - name: miroir
  interval: 30m
  path: ./kubernetes/luffy/apps/database/percona-postgres-operator/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: database
  timeout: 10m
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname percona-postgres-secretstore
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: percona-postgres-cluster
    - name: external-secrets
  interval: 30m
  path: ./kubernetes/luffy/apps/database/percona-postgres-operator/clustersecretstore
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: database
  timeout: 10m
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname percona-postgres-userinit-controller
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: percona-postgres-cluster
  interval: 30m
  path: ./kubernetes/luffy/apps/database/percona-postgres-operator/userinit-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: database
  timeout: 10m
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname percona-postgres-pgadmin
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: percona-postgres-cluster
    - name: miroir
  interval: 30m
  path: ./kubernetes/luffy/apps/database/percona-postgres-operator/pgadmin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: database
  timeout: 10m
  wait: true
