---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kite-secret
spec:
  dataFrom:
    - extract:
        key: kite
      rewrite:
        - regexp:
            source: "(.*)"
            target: "kite_$1"
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: kite-secret
    template:
      data:
        JWT_SECRET: "{{ .kite_jwt_secret }}"
        KITE_ENCRYPT_KEY: "{{ .kite_encrypt_key }}"
        KITE_PASSWORD: "{{ .kite_auth_password }}"
        KITE_USERNAME: "{{ .kite_auth_username }}"
      type: Opaque
