---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kite-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: kite-secret
    template:
      type: Opaque
      data:
        JWT_SECRET: "{{ .kite_jwt_secret }}"
        KITE_ENCRYPT_KEY: "{{ .kite_encrypt_key }}"
      templateFrom:
        - configMap:
            name: kite-config-tpl
            items:
              - key: config.yaml
  dataFrom:
    - extract:
        key: kite
      rewrite:
        - regexp:
            source: "(.*)"
            target: "kite_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name kite-db
spec:
  dataFrom:
    - extract:
        key: postgres-pguser-kite
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: *name
    template:
      data:
        DB_DSN: "{{ .uri }}"
      type: Opaque
