---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kite
spec:
  chart:
    spec:
      chart: kite
      sourceRef:
        kind: HelmRepository
        name: kite
        namespace: flux-system
      version: 0.12.2
  interval: 30m
  values:
    db:
      sqlite:
        persistence:
          pvc:
            enabled: true
            size: 1Gi
      type: sqlite
    gateway:
      className: envoy
      enabled: true
      httpRoutes:
        - hostnames:
            - kite.${CLUSTER_DOMAIN}
          name: kite
          rules:
            - backendRefs:
                - name: kite
                  port: 8080
              matches:
                - path:
                    type: PathPrefix
                    value: /
      name: envoy
      namespace: network
    secret:
      existingSecret: kite-secret
