---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kite
spec:
  chart:
    spec:
      chart: kite
      sourceRef:
        kind: HelmRepository
        name: kite
        namespace: flux-system
      version: 0.15.0
  interval: 30m
  values:
    host: "https://kite.${CLUSTER_DOMAIN}"
    podAnnotations:
      reloader.stakater.com/auto: "true"
    secret:
      existingSecret: kite-secret
    config:
      enabled: true
      existingSecret: "kite-secret"
    db:
      type: postgres
    extraEnvs:
      - name: DB_TYPE
        value: "postgres"
      - name: DB_DSN
        valueFrom:
          secretKeyRef:
            name: kite-db
            key: DB_DSN
    gateway:
      enabled: true
      name: envoy
      namespace: network
      className: envoy
      httpRoutes:
        - hostnames:
            - kite.${CLUSTER_DOMAIN}
          name: kite
          rules:
            - backendRefs:
                - name: kite
                  port: 8080
              matches:
                - path:
                    type: PathPrefix
                    value: /
