apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-env
    namespace: immich
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:aozTg4Gg,iv:IIqphOsmSCs70m2pxyt2fRg1OJoKlVKsZkjkDooC/ks=,tag:3k9dTa/gHVZEtsSmEDBWnw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:EtzIK/y5,iv:BG34/71tnUk5GQZNHTdiQ3kigfEe+oGByJaVAbGOp0k=,tag:RrUBiWHyYDoFHpPMM/1teA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:KFF9jo1t,iv:x0GwC9E5dicuXxJRaTQQ/3fXz0X7T92JPHKpSSGJs6E=,tag:gj7cVfp2/SiqnjsQQ0sKjQ==,type:str]
    TZ: ENC[AES256_GCM,data:4OnQ/p7Zufjy7Cfr,iv:xxSTaoVlAD95QWeICU60we3zcXiAUXPM54f0rYvniPw=,tag:r/0/tmDM0Fj7Xrlt54wxRg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaklJcUdtZDhpTURqV3c4
            TTg5bFlHZTY2MERPTTJoT2I0MDlMemY4ZUdRCktMNU5GVktha2ZFbUtxdmJPTEZG
            YWIwbUhMVUt5MnRlTTRCS1JSZmVLT2MKLS0tIGpjcjVnUS9qUEwyTkczR2RrNFg4
            MFMxNFFvRVRCbGloYTZBU2RSUUc5MncKFwA9iei1rRgVeSR0+tkaZDL9O3SLF2CD
            I3bBwFSnM0YjyrjCuH10gfaqibnCSwoJ62DnCy+IqtbyhgUGwSTPCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T20:34:09Z"
    mac: ENC[AES256_GCM,data:5RO84aVG6YOnv53KKj1r0uDzYzLwJ8u6kxw18xb+33s1RFp0uEEXcNKGJnnkY8b0PeQd6c1OpfsDWtkqVWPDhTZTgN9vTVYXwn8poAi28R39ERoJPb/Uo0Jq+2LPM+W7HJZocsJpxIWO8lVdBe0bgq1zFYQPTkyPk2TVSKGW+b4=,iv:Q0j4iGNJgW3TgK2xnsEk0133EJwcf1QJBjNfhsYQn9E=,tag:kE4T1VJzbM2h8ZgixIgiOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-server-env
    namespace: immich
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:2KMIuLhX,iv:4NKOnvHCc6DRFB2QIEu0FdC660Sid3o+U+BL1xFxblo=,tag:C1N9j5eSUOHoRNbkNHpHJA==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:ZB+Ter5iNes=,iv:XqEjHZIFC1GqI2Leu2F7MMsdnlQfDhjS1TBmHrhJihU=,tag:9z/CX/l/lpHQ8zMHnNxhEQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:hHazznEU,iv:tPyq5dWmD4kQn7mbL5mzDq+IesULQK5D+HlueLVV5JI=,tag:lraG7hYYPLLTpR+G8qWuBw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:BG9aSi8V,iv:z18JslxnxzU5OiIoR1/d7qgwD45UsvUWQP1tUhlvV4E=,tag:RYKYcvEALUlrfdWGYVm+Ow==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:npxNTVQTtec86r6k,iv:+pT9AF8gndG/OrVksyGkf/rCH1+kWbaD+9Gj79mSpr0=,tag:DrD+61kLbBY443uvk1kC/w==,type:str]
    REDIS_PORT: null
    TZ: ENC[AES256_GCM,data:4OnQ/p7Zufjy7Cfr,iv:xxSTaoVlAD95QWeICU60we3zcXiAUXPM54f0rYvniPw=,tag:r/0/tmDM0Fj7Xrlt54wxRg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaklJcUdtZDhpTURqV3c4
            TTg5bFlHZTY2MERPTTJoT2I0MDlMemY4ZUdRCktMNU5GVktha2ZFbUtxdmJPTEZG
            YWIwbUhMVUt5MnRlTTRCS1JSZmVLT2MKLS0tIGpjcjVnUS9qUEwyTkczR2RrNFg4
            MFMxNFFvRVRCbGloYTZBU2RSUUc5MncKFwA9iei1rRgVeSR0+tkaZDL9O3SLF2CD
            I3bBwFSnM0YjyrjCuH10gfaqibnCSwoJ62DnCy+IqtbyhgUGwSTPCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T20:34:09Z"
    mac: ENC[AES256_GCM,data:5RO84aVG6YOnv53KKj1r0uDzYzLwJ8u6kxw18xb+33s1RFp0uEEXcNKGJnnkY8b0PeQd6c1OpfsDWtkqVWPDhTZTgN9vTVYXwn8poAi28R39ERoJPb/Uo0Jq+2LPM+W7HJZocsJpxIWO8lVdBe0bgq1zFYQPTkyPk2TVSKGW+b4=,iv:Q0j4iGNJgW3TgK2xnsEk0133EJwcf1QJBjNfhsYQn9E=,tag:kE4T1VJzbM2h8ZgixIgiOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
