apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
    name: db-credentials
    namespace: immich
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    username: ENC[AES256_GCM,data:IaE3YoiE,iv:kZNdm8wZqn1qy6IPp1BJZA8UTqjQ2IxMGXqhc/pls3k=,tag:XUh945D5ISuPKCJ35PCQGQ==,type:str]
    password: ENC[AES256_GCM,data:etn4Nrmw,iv:pK9rT4SfAi81/EcbUABt6xZdt/a6bRR4S8YHqfRsJ4I=,tag:v6Dac/X9vNd5bfOJgowNTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaklJcUdtZDhpTURqV3c4
            TTg5bFlHZTY2MERPTTJoT2I0MDlMemY4ZUdRCktMNU5GVktha2ZFbUtxdmJPTEZG
            YWIwbUhMVUt5MnRlTTRCS1JSZmVLT2MKLS0tIGpjcjVnUS9qUEwyTkczR2RrNFg4
            MFMxNFFvRVRCbGloYTZBU2RSUUc5MncKFwA9iei1rRgVeSR0+tkaZDL9O3SLF2CD
            I3bBwFSnM0YjyrjCuH10gfaqibnCSwoJ62DnCy+IqtbyhgUGwSTPCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T05:01:41Z"
    mac: ENC[AES256_GCM,data:/+Cf8PCO0bywqOy6Zl/BazfWSlLy5HHF/0JHYFFOj+T2hPPTgzBtFNOZJDq77PQJ4uiQ2dKR3/+Bx9VVLnDM/KBcqiPu2mu8qWpvSRCtq4a3KBTnotXVgywm7/1EMtOLP3J/CAZOdvScbtSoXGWmclzYVDZMr6lWPAtZ9Wns4DU=,iv:ZT2Lbln5gFbBcFBEjk4aK4AM9iq5hI28PLwvLNNH0MA=,tag:zkYhvC1Jgp7kt4T/syVNjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: barman-credentials
    namespace: immich
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    access-key-id: ENC[AES256_GCM,data:+w+KyO15ztBuwSfO6/K/4TIaoBT1wOV1YQHo2RVHC3g=,iv:/644rrak+68DVWZayGa4m4Xp2ttComZWZqk9IuLtWiQ=,tag:rJN4NZyjjZ0wCmLQStCGgw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:Lf5N+u3kkoh8/xzNPQNAk2+Q8l5lUZfysJdCMskep9uYvA4u1rX1DX013gwEmTWpkoIq6xumos8H7YDdJuqh/w==,iv:H/4wj8Ju8HtqeeiUiOxwTse1aNR/kLa5Zr+jrlub/PI=,tag:rOlqtg7s8KlgjoSQG/XFQg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaklJcUdtZDhpTURqV3c4
            TTg5bFlHZTY2MERPTTJoT2I0MDlMemY4ZUdRCktMNU5GVktha2ZFbUtxdmJPTEZG
            YWIwbUhMVUt5MnRlTTRCS1JSZmVLT2MKLS0tIGpjcjVnUS9qUEwyTkczR2RrNFg4
            MFMxNFFvRVRCbGloYTZBU2RSUUc5MncKFwA9iei1rRgVeSR0+tkaZDL9O3SLF2CD
            I3bBwFSnM0YjyrjCuH10gfaqibnCSwoJ62DnCy+IqtbyhgUGwSTPCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T05:01:41Z"
    mac: ENC[AES256_GCM,data:/+Cf8PCO0bywqOy6Zl/BazfWSlLy5HHF/0JHYFFOj+T2hPPTgzBtFNOZJDq77PQJ4uiQ2dKR3/+Bx9VVLnDM/KBcqiPu2mu8qWpvSRCtq4a3KBTnotXVgywm7/1EMtOLP3J/CAZOdvScbtSoXGWmclzYVDZMr6lWPAtZ9Wns4DU=,iv:ZT2Lbln5gFbBcFBEjk4aK4AM9iq5hI28PLwvLNNH0MA=,tag:zkYhvC1Jgp7kt4T/syVNjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-server-env
    namespace: immich
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    #ENC[AES256_GCM,data:ytgV8GSB7by62IWCyO9mjyhUuuTeqcoZYg==,iv:KvmdlZmUn5lOwXw7cc6XM9qsXt2OcoURISvFsyjaUoA=,tag:dGdLIiRQ22woh0WjRfePPQ==,type:comment]
    #ENC[AES256_GCM,data:SfBHcp88qylo4nTCkYjJguJ2EmWmBpvD1IpNrAc=,iv:PBmYCbnzrm9tmGdBmmXETTfVeXKdqVkBolYNF3FQB+Q=,tag:PwlYDWFDfd6M1UDfTXZgEA==,type:comment]
    #ENC[AES256_GCM,data:ur78Er1judx9AYRYZ7r4jHdLZVQ=,iv:riM1C0D8Z+vMZ4CLOoc7vkMhc4kShdSUl9GpaVhp0Ck=,tag:Zo4OIC+zfwg78tq27i53kQ==,type:comment]
    #ENC[AES256_GCM,data:swkTax8i7CtGJ2B5hTy7t6fQ0dw=,iv:TQmD5FDkN4mJo8Jgp0bCHlgpYKa4NJco3wVSScw38R8=,tag:pn9UYYi2K/8B/4DMA5QvxQ==,type:comment]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:npxNTVQTtec86r6k,iv:+pT9AF8gndG/OrVksyGkf/rCH1+kWbaD+9Gj79mSpr0=,tag:DrD+61kLbBY443uvk1kC/w==,type:str]
    REDIS_PORT: null
    TZ: ENC[AES256_GCM,data:4OnQ/p7Zufjy7Cfr,iv:xxSTaoVlAD95QWeICU60we3zcXiAUXPM54f0rYvniPw=,tag:r/0/tmDM0Fj7Xrlt54wxRg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaklJcUdtZDhpTURqV3c4
            TTg5bFlHZTY2MERPTTJoT2I0MDlMemY4ZUdRCktMNU5GVktha2ZFbUtxdmJPTEZG
            YWIwbUhMVUt5MnRlTTRCS1JSZmVLT2MKLS0tIGpjcjVnUS9qUEwyTkczR2RrNFg4
            MFMxNFFvRVRCbGloYTZBU2RSUUc5MncKFwA9iei1rRgVeSR0+tkaZDL9O3SLF2CD
            I3bBwFSnM0YjyrjCuH10gfaqibnCSwoJ62DnCy+IqtbyhgUGwSTPCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T05:01:41Z"
    mac: ENC[AES256_GCM,data:/+Cf8PCO0bywqOy6Zl/BazfWSlLy5HHF/0JHYFFOj+T2hPPTgzBtFNOZJDq77PQJ4uiQ2dKR3/+Bx9VVLnDM/KBcqiPu2mu8qWpvSRCtq4a3KBTnotXVgywm7/1EMtOLP3J/CAZOdvScbtSoXGWmclzYVDZMr6lWPAtZ9Wns4DU=,iv:ZT2Lbln5gFbBcFBEjk4aK4AM9iq5hI28PLwvLNNH0MA=,tag:zkYhvC1Jgp7kt4T/syVNjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
