---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./default.yaml
  - ./immich-env.sops.yaml
  - ./volumes.yaml
  - ./postgresql.yaml
  - ./deployment.yaml
