apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
spec:
  instances: 3
  description: 'Immich DB'
  imageName: 'ghcr.io/tensorchord/cloudnative-pgvecto.rs:17.2'
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: db-credentials
      postInitSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
  # configure storage types used
  storage:
    storageClass: longhorn-local
    size: 10Gi
  walStorage:
    storageClass: longhorn-local
    size: 10Gi
  # prometheus
  monitoring:
    enablePodMonitor: true
  # see https://cloudnative-pg.io/documentation/1.22/kubernetes_upgrade/
  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead
  postgresql:
    shared_preload_libraries:
      - 'vectors.so'
  # otherwise postgres crashes with hugepages enabled
  resources:
    requests:
      memory: 100Mi
      hugepages-2Mi: 100Mi
    limits:
      memory: 1Gi
      hugepages-2Mi: 100Mi
  backup:
    retentionPolicy: '60d'
    barmanObjectStore:
      destinationPath: s3://databases/immich-db
      endpointURL: https://4fc118cc61e84408cd4335a7544714bd.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: barman-credentials
          key: access-key-id
        secretAccessKey:
          name: barman-credentials
          key: secret-access-key
      wal:
        compression: gzip # this saves a lot of storage
      data:
        compression: gzip
        jobs: 2
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich
  namespace: default
spec:
  immediate: true
  schedule: 0 */30 * * * *
  backupOwnerReference: self
  cluster:
    name: immich-db
