apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
spec:
  instances: 3
  description: "Immich DB"
  imageName: "ghcr.io/tensorchord/cloudnative-pgvecto.rs:14-v0.2.0"
  primaryUpdateStrategy: unsupervised
  bootstrap:
    # recovery:
    #   source: immich-db
    # # in case you're rebuilding
    initdb:
      database: immich
      owner: immich
      secret:
        name: db-credentials
      postInitApplicationSQL:
        - CREATE EXTENSION cube;
        - CREATE EXTENSION earthdistance;
        - CREATE EXTENSION vectors;
        - GRANT ALL ON SCHEMA vectors TO immich;
        - ALTER SCHEMA vectors OWNER to immich;
      dataChecksums: true
      encoding: 'UTF8'
  storage:
    storageClass: longhorn-local
    size: 10Gi
  walStorage:
    storageClass: longhorn-local
    size: 10Gi
  # prometheus
  monitoring:
    enablePodMonitor: true
  # see https://cloudnative-pg.io/documentation/1.22/kubernetes_upgrade/
  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  # otherwise postgres crashes with hugepages enabled
  resources:
    requests:
      memory: 100Mi
      hugepages-2Mi: 100Mi
    limits:
      memory: 1Gi
      hugepages-2Mi: 100Mi
  backup:
    retentionPolicy: '7d'
    barmanObjectStore:
      destinationPath: s3://databases/immich-db
      endpointURL: https://4fc118cc61e84408cd4335a7544714bd.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: barman-credentials
          key: access-key-id
        secretAccessKey:
          name: barman-credentials
          key: secret-access-key
      wal:
        compression: gzip # this saves a lot of storage
      data:
        compression: gzip
        jobs: 2
  externalClusters:
    - name: immich-db
      barmanObjectStore:
        destinationPath: s3://databases/immich-db
        endpointURL: https://4fc118cc61e84408cd4335a7544714bd.r2.cloudflarestorage.com
        s3Credentials:
          accessKeyId:
            name: barman-credentials
            key: access-key-id
          secretAccessKey:
            name: barman-credentials
            key: secret-access-key
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich
  namespace: immich
spec:
  immediate: true
  schedule: 0 */30 * * * *
  backupOwnerReference: self
  cluster:
    name: immich-db
