# Immich Machine Learning Persistent Volume Claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-model-cache
  namespace: immich
  labels:
    app: immich-machine-learning
    app.kubernetes.io/instance: immich-machine-learning
    app.kubernetes.io/name: immich-machine-learning
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

# Postgres Persistent Volume Claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgres-data
  namespace: immich
  labels:
    app: immich-postgres
    app.kubernetes.io/instance: immich-postgres
    app.kubernetes.io/name: immich-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
