---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maintainerr-overlay-helperr
spec:
  dataFrom:
    - extract:
        key: plex
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: maintainerr-overlay-helperr
    template:
      data:
        BACK_COLOR: '#B20710'
        BACK_RADIUS: '0'
        CRON_SCHEDULE: '5 */8 * * *'
        DATE_FORMAT: 'MMM d'
        ENABLE_DAY_SUFFIX: 'true'
        ENABLE_UPPERCASE: 'false'
        FONT_COLOR: '#ffffff'
        FONT_PATH: '/fonts/AvenirNextLTPro-Bold.ttf'
        FONT_SIZE: '3.2'
        HORIZONTAL_ALIGN: 'center'
        HORIZONTAL_OFFSET: ''
        IMAGE_SAVE_PATH: '/opt/data/overlay-helperr/images'
        LANGUAGE: 'en-US'
        MAINTAINERR_URL: 'http://maintainerr.media.svc.cluster.local:6246'
        ORIGINAL_IMAGE_PATH: '/opt/data/overlay-helperr/images/originals'
        OVERLAY_TEXT: 'Leaving'

        PADDING: '1.2'
        PLEX_TOKEN: '{{ index . "token" }}'
        PLEX_URL: http://plex.media.svc.cluster.local:32400
        REAPPLY_OVERLAY: 'true'
        REORDER_COLLECTIONS: 'Delete watched movies, Delete watched episodes'

        RUN_ON_CREATION: 'true'
        TEMP_IMAGE_PATH: '/opt/data/overlay-helperr/images/temp'

        VERTICAL_ALIGN: 'bottom'
        VERTICAL_OFFSET: '3'
      type: Opaque
