# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: botpunk-pem
spec:
  data:
    - remoteRef:
        key: Github
        property: botpunk_app_key
      secretKey: private_key_pem
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: botpunk-pem
