---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: renovate-secret
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: forgejo
        property: RENOVATE_TOKEN
    - secretKey: RENOVATE_GITHUB_COM_TOKEN
      remoteRef:
        key: Github
        property: pat_renovate_operator
    - secretKey: RENOVATE_GIT_PRIVATE_KEY
      remoteRef:
        key: forgejo
        property: RENOVATE_GIT_PRIVATE_KEY
