---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: botpunk-auth-token
spec:
  appID: "1211834"
  auth:
    privateKey:
      secretRef:
        key: private_key_pem
        name: botpunk-pem # reference secret from step 1.
  installID: "64304826"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: botpunk-vjlab-token
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: botpunk-auth-token
  refreshInterval: "30m0s"
  target:
    name: botpunk-vjlab-token
    template:
      data:
        GITHUB_COM_TOKEN: "{{ .token }}"
        GITHUB_COM_USER: VmlqYXlha3VtYXJSYXZpCg==
        RENOVATE_TOKEN: "{{ .token }}"
      engineVersion: v2
      type: Opaque
---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: vjlab
  namespace: selfhosted
spec:
  discoverTopics:
    - renovate
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: |-
        ["pnpm run bundle"]
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_PLATFORM_COMMIT
      value: true
  image: ghcr.io/renovatebot/renovate:43.195.1
  parallelism: 5
  provider:
    endpoint: ""
    name: github
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: botpunk-vjlab-token
  webhook:
    authentication:
      enabled: false
    enabled: true
