---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-secret
spec:
  data:
    - remoteRef:
        key: proton-vpn
        property: qbittorrent_vpn_endpoint_ip
      secretKey: WIREGUARD_ENDPOINT_IP
    - remoteRef:
        key: proton-vpn
        property: qbittorrent_wireguard_public_key
      secretKey: WIREGUARD_PUBLIC_KEY
    - remoteRef:
        key: proton-vpn
        property: qbittorrent_wireguard_private_key
      secretKey: WIREGUARD_PRIVATE_KEY
    - remoteRef:
        key: proton-vpn
        property: qbittorrent_wireguard_addresses
      secretKey: WIREGUARD_ADDRESSES
    - remoteRef:
        key: cross-seed
        property: api_key
      secretKey: xseed_api_key
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: qbittorrent-secret
