kind: Secret
apiVersion: v1
metadata:
    name: qbittorrent-secret
    labels:
        encrypted-by: sops
        encryption-method: age
type: Opaque
stringData:
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:3AxsEr2AXaRZ0KzYNZIs,iv:2uxB/gC98XS+b25ybMdv7E+A93CD3cXSKpdJOClAPGM=,tag:/Y7pfTe+hbyaIqXxQoX0Xw==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:U2Lk2I/Sdiy/xLYFEmVeDqmT5KRKP2PXh4+vnR0057zH63JroImdwOJkar8=,iv:qb3n6KVSV0yc1F4maq2OiJs+OTEGvI2Up9aboOM7YlU=,tag:UaHDYg7ITLIB/iFj/EyyUw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:MMhsyDJhCOn42veIqucZybAYJ5Vjp8g2Ck0fGRBzm90Uy2ldsPNGE2+KigY=,iv:oHJ+DdpTpgj1XKgEKgbosft0SRIY1/dG7owcXmGERYM=,tag:o3+Y0d256dbwM0hCO0XHug==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:dlr+9egnSoZ5DNE=,iv:H13givvpDx7Yypiy67SjKJYlChtbpVWIXnp0BVwY0p4=,tag:zONA8tYYccV8C976unQsOA==,type:str]
    xseed_api_key: ENC[AES256_GCM,data:aG7OgwU2fYaUeujE9MYCbG/UFdzm/vVGghNERl7E/QA=,iv:bG6VoS4SIcUljvJarnAXbRubTg2S4ouedpDJ1pJ8ofU=,tag:CSXWIMZJ9EiSiKxjjKAt5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WVFxNzNJMEp1Y0laakM1
            NnVYU0ZZQVVuWHgxSEIyYit2MGtBb3FiMUFZCkgyZ2hqUkduK2NkR2R1TFByeDlV
            M0c4RzZHcHo5ZEZGTXI5cit4OUJhVDgKLS0tIGh5ZktqVE1HN0VqaXlmWk53aFNT
            SGp4MEVoRjZPS3QwZUZNdzYzWHdxcWMK+WhjscvK3ZrDu4UZbX8bIT+Xq1G3eL85
            bXpofclVURhnROjw772j7oKOMLrJEHAY99OC7TCmBGZE6X97tXYDaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T16:42:01Z"
    mac: ENC[AES256_GCM,data:6aC+CHlp0/Xb8QlDgN3RhIL4ir6A9APhOKxG53/mQ6qR9PXJhsiolYGiAeDueB41ZgLdJmp3axYs5104vQ3vEHW5F8O94ZIWm1Ag455QwvymZkT7kmV6r2nQc3EAW3mbFyQ3tygzfKnC+yf/o4XeAyKXBWdYwDVCwVERtIAodGM=,iv:J/bK73XRDOabJ6bphCb8t/CKg58OdlVcMNZI877YNy8=,tag:WDy7Mz9WRT7I7gtc7o2y9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
