kind: Secret
apiVersion: v1
metadata:
    name: qbittorrent-secret
    labels:
        encrypted-by: sops
        encryption-method: age
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:sJHQ6f5ZDOC8Mkl4xyBJvUoOdOfFXa7Oygv19CtAOC+oTT5r8SSOvDUEmkw=,iv:0mK8SVtAnG9EgY6uYpEuK2UYWt8E+GKcgM6TDbhfmiw=,tag:16KyQ37lfQClqHzOxGoWXw==,type:str]
    xseed_api_key: ENC[AES256_GCM,data:aG7OgwU2fYaUeujE9MYCbG/UFdzm/vVGghNERl7E/QA=,iv:bG6VoS4SIcUljvJarnAXbRubTg2S4ouedpDJ1pJ8ofU=,tag:CSXWIMZJ9EiSiKxjjKAt5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WVFxNzNJMEp1Y0laakM1
            NnVYU0ZZQVVuWHgxSEIyYit2MGtBb3FiMUFZCkgyZ2hqUkduK2NkR2R1TFByeDlV
            M0c4RzZHcHo5ZEZGTXI5cit4OUJhVDgKLS0tIGh5ZktqVE1HN0VqaXlmWk53aFNT
            SGp4MEVoRjZPS3QwZUZNdzYzWHdxcWMK+WhjscvK3ZrDu4UZbX8bIT+Xq1G3eL85
            bXpofclVURhnROjw772j7oKOMLrJEHAY99OC7TCmBGZE6X97tXYDaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T12:16:20Z"
    mac: ENC[AES256_GCM,data:X5zhEq8rqvByQpzSdom0sD5z8od5SGKkJxs+yAEf34RRx6U+DZ1vjdnSaaFgpPKDYr+jjfzO45MC4j3Qk8bfwHiygqCf6s7Dam/mlpHjIjy6FTL0s8AFatL0lpLmH2OP4sq9LTyE9+C0R/cjGPwQOhuJXdi0WOg/Gzt4+m9s4Jk=,iv:TWASfit5WEG+L43WE5jVjs2bPFuegzaBUDBYwCMroII=,tag:miOhVYPzrbM21K8GARiGEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
