apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: utils
    labels:
        encrypted-by: sops
        encryption-method: age
data:
    WEBPASSWORD: ENC[AES256_GCM,data:4mTFyow=,iv:jIsOlNfbmbBS0sYqpye1jyU+z+sHpKSZpfw+/cQoBQE=,tag:5NEzbp6eXb9TDjdtgcQ7gw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETURhMjJiMk10aGJoUnlr
            VmtMejNQZm5aNE9jVWYrMGx3ZzQrc3hUd0U0ClowTVhCejBCTVU4OElzS2U0NklN
            UDFHQTZpRGEwSUhNZXlOTlFBK0FKMWcKLS0tIHQxdDFwY3hkRU90NG9HSnNFL2Mz
            TDE0WE51R0ZidUVmT0NOZ1E2Ymt6ZlUKwURHmizgVaVFn2TxfzoABqYlk2haF9vi
            VxNTgJUVWMRdlqYoujsUOM1vbAssjlki6TnDmqis+5ypHizN08Cgtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T15:16:32Z"
    mac: ENC[AES256_GCM,data:ecj0dvKFYSLv3wvFhYOrryBgZzJAsTwMG17DBUt+g1izB9N8Km7tUCfbMDtGSYFPMEAEkvAQ0zs/6mmHuglknd6MtFjeknH4+NlhMWxgIuMszhk/Qw8Rt382ecSbpWBKOaXWDcVkgBjjtG1Xi8x2FiSofCWph6DD6HWshH5U4rI=,iv:Ds7Kc3WOB1rn6nZnbQkodOxvBEh/N2OY5q2/l4YY+F4=,tag:jpSDBIO4TPnUQAMaUrWhpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
