---
apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
  namespace: utils
  labels:
    encrypted-by: sops
    encryption-method: age
stringData:
  WEBPASSWORD: ENC[AES256_GCM,data:y5pBjxs=,iv:yYnyniEMn+LjPd0dwX1/xIOG0/UJNpWFRKPXgJFvS9c=,tag:O43sL3yXzbzqXUkcFj6cAQ==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETURhMjJiMk10aGJoUnlr
        VmtMejNQZm5aNE9jVWYrMGx3ZzQrc3hUd0U0ClowTVhCejBCTVU4OElzS2U0NklN
        UDFHQTZpRGEwSUhNZXlOTlFBK0FKMWcKLS0tIHQxdDFwY3hkRU90NG9HSnNFL2Mz
        TDE0WE51R0ZidUVmT0NOZ1E2Ymt6ZlUKwURHmizgVaVFn2TxfzoABqYlk2haF9vi
        VxNTgJUVWMRdlqYoujsUOM1vbAssjlki6TnDmqis+5ypHizN08Cgtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-11-30T15:45:05Z'
  mac: ENC[AES256_GCM,data:IdqDA2ewOfzo11r9n1CMoLBuZup3aPFxwGz/cpKmIQS8LO52GX2tw9uc8aKM558zZt76qLyPOMLKC+IYkjFA6u0ZqE2m4KLKoblWgXBtdAoHP5tj5r1htMWFtnvCYKnBBgoYM77OWMnqzRG9KoLsPnkDlxcQh2K44j0RVU7XZPg=,iv:YxRa6joRl6ATyTvaunRK7TtLWDV2X5HHmn/MvPJW+y0=,tag:64T95mBdzG6U7oxUpT1X/A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
