apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: utils
data:
    WEBPASSWORD: ENC[AES256_GCM,data:GSyB4IP/MZs=,iv:xL3D/AN0zNf35jUZPLXiaTnWRNtNFzI05nIBqN7/je8=,tag:BiLbUx2TGDZpr6+W4fGM+g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19654hupmjy08ge0xu43mynjca5wmrd3kmlt7wsja582waanvf4uqvv65ya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaVRqZmZNU2hVaExxWG9n
            dXZzSTlSWDhPYWd0VG1GU29nYStvSDI0ZkRBCk1raTMrWDVXL29RLytHMFdXM2pz
            bjhLOXVPT2N3akZWWmQ5UXhoYlFxWGsKLS0tIDh3UVlrV0cwYzdhZWEzYlpkUVdV
            cDFVcjh3MG9raHBCUmt6Z2M5NnNWSHMKp9snuZgjTst1L4hMJfonOrjRH7SsQlH3
            WrpQxsmLFAMX9hrIBBvmaI1wvo9FPmB7fVvneqtN7cbv93PyHlTvMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T21:01:06Z"
    mac: ENC[AES256_GCM,data:fP5K5PlOIhVHH5251H/s1D0cGHWCcNjjqLtund7UAMmggRJXPFuoNqa125KNYnayCEr4Z4TDGXWDHkSWAaAIqo3Z/9spx/DFHXO7clnUYlfpQbB0Bniq0uwbhEqpyaTd0T0e4ri4nRtLfHBvG4ilu5i8y/H2ppIPCff2Vuj1Bs0=,iv:tp/5uNceZWl+9Ge9SCgrvQOYwtTt4d5GL1gKAsJBCe4=,tag:q7b8VLadVxSDFBG4x3R7/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
