apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./default.yaml

  - ./pihole/sealed-secret.yaml
  - ./pihole/middleware.yaml
  - ./pihole/manifest.yaml

  - ./gotify/sealed-secret.yaml
  - ./gotify/manifest.yaml

  - ./auto-delete-failed-pods/manifest.yaml
