apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./default.yaml
  - ./pihole/pihole-secret.sops.yaml
  - ./pihole/middleware.yaml
  - ./pihole/manifest.yaml
  - ./gotify/gotify-secret.sops.yaml
  - ./gotify/manifest.yaml
