---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-pvc
  namespace: media
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qbittorrent
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/name: qbittorrent
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
        app.kubernetes.io/name: qbittorrent
    spec:
      containers:
        - image: linuxserver/qbittorrent:20.04.1
          imagePullPolicy: IfNotPresent
          name: qbittorrent
          ports:
            - containerPort: 8080
              name: web-tcp
              protocol: TCP
            - containerPort: 8080
              name: web-udp
              protocol: UDP
            - containerPort: 6881
              name: torrent-tcp
              protocol: TCP
            - containerPort: 6881
              name: torrent-udp
              protocol: UDP
          env:
            - name: TZ
              value: Asia/Kolkata
            - name: TORRENTING_PORT
              value: '6881'
            - name: UMASK
              value: '002'
            - name: WEBUI_PORTS
              value: 8080/tcp,8080/udp
          volumeMounts:
            - mountPath: /config
              name: qbittorrent
              subPath: qbittorrent-config
            - mountPath: /media
              readOnly: false
              name: nfs
      volumes:
        - name: qbittorrent
          persistentVolumeClaim:
            claimName: qbittorrent-pvc
        - name: nfs
          persistentVolumeClaim:
            claimName: media-share-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qbittorrent
  name: qbittorrent
  namespace: media
spec:
  ports:
    - name: web-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: web-udp
      port: 8080
      protocol: UDP
      targetPort: 8080
    - name: torrent-tcp
      port: 6881
      protocol: TCP
      targetPort: 6881
    - name: torrent-udp
      port: 6881
      protocol: UDP
      targetPort: 6881
  selector:
    app: qbittorrent
  type: ClusterIP
  clusterIP: 10.43.157.103
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints: [websecure]
  tls:
    secretName: home-vijayakumar-xyz
  routes:
    - match: Host(`qbittorrent.home.vijayakumar.xyz`)
      kind: Rule
      services:
        - name: qbittorrent
          port: 8080
      middlewares:
        - name: default-headers
