---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: stalwart-config
    template:
      type: Opaque
      data:
        config.json: |
          {
            "@type": "MySql",
            "timeout": 15000,
            "useTls": true,
            "allowInvalidCerts": true,
            "maxAllowedPacket": null,
            "poolMaxConnections": 10,
            "poolMinConnections": 5,
            "readReplicas": {},
            "host": "{{ .mysql_host }}",
            "port": {{ .mysql_port }},
            "database": "stalwart",
            "authUsername": "{{ .msql_username }}",
            "authSecret": {
              "@type": "Value",
              "secret": "{{ .mysql_password }}"
            }
          }
  dataFrom:
    - extract:
        key: stalwart
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-registry-pull-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: docker-registry-pull-secret
    template:
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .docker_registry_server }}": {
                "username": "{{ .docker_registry_username }}",
                "password": "{{ .docker_registry_password }}",
                "auth": "{{ printf "%s:%s" .docker_registry_username .docker_registry_password | b64enc }}"
              }
            }
          }
  dataFrom:
    - extract:
        key: docker
      rewrite:
        - regexp:
            source: "(.*)"
            target: "docker_$1"
