---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redlib
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      redlib:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/redlib/redlib
              tag: latest@sha256:bd1b79a73fbfd66da155f0579bb16bedb35e05bed057210336fea301f987da80
            env:
              REDLIB_DEFAULT_COMMENT_SORT: "old"
              REDLIB_DEFAULT_HIDE_AWARDS: "on"
              REDLIB_DEFAULT_POST_SORT: "new"
              REDLIB_DEFAULT_SHOW_NSFW: "on"
              REDLIB_DEFAULT_THEME: "dark"
              REDLIB_DEFAULT_WIDE: "on"
              REDLIB_DEFAULT_SUBSCRIPTIONS: "1Password+AdGuardHome+ansible+archlinux+Authentik+aws+bangtan+Bitwarden+CloudFlare+commandline+cozy+debian+dllinks+docker+Dockerfiles+Fedora+homelab+HomeServer+immich+kubernetes+linux+linuxhardware+linuxmemes+linuxquestions+MCUMoviesHome+mkbhd+MobileWallpaper+neovim+NixOS+OnePiece+OpenMediaVault+opensource+opnsense+pihole+pop_os+Proxmox+raspberry_pi+scarystories+selfhosted+shortcuts+sololeveling+Tailscale+Traefik+truenas+unixart+unixporn+UnixWallpapers+usenet+vaultwarden+vim+vimplugins+vimporn+wallpaper+wallpapers+WireGuard"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /settings
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 12m
                memory: 64M
              limits:
                memory: 256M
    service:
      app:
        controller: redlib
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: nginx
        hosts:
          - host: reddit.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
