---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: linkwarden-db
    template:
      type: Opaque
      data:
        DATABASE_URL: '{{ index . "uri" }}?sslmode=require&sslmode=no-verify'
  dataFrom:
    - extract:
        key: postgres-pguser-linkwarden
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: linkwarden-env
    template:
      type: Opaque
      data:
        NEXTAUTH_SECRET: "{{ .linkwarden_nextauth_secret }}"
        NEXTAUTH_URL: https://linkwarden.${CLUSTER_DOMAIN}/api/v1/auth
        STORAGE_FOLDER: "config" # Will always end up as /data/STOREAGE_FOLDER so eg /data/config
        MAX_WORKERS: "3"
        ARCHIVE_TAKE_COUNT: "2"
        DISABLE_PRESERVATION: "false"
        NEXT_PUBLIC_RSS_POLLING_INTERVAL_MINUTES: "60"
        # DISABLE_NEW_SSO_USERS: "false"

        NEXT_PUBLIC_DISABLE_REGISTRATION: "false"
        NEXT_PUBLIC_AUTH0_ENABLED: "true"
        AUTH0_CUSTOM_NAME: "Auth0"
        AUTH0_ISSUER: "https://luffy.eu.auth0.com"
        AUTH0_CLIENT_SECRET: "{{ .linkwarden_auth0_client_secret }}"
        AUTH0_CLIENT_ID: "{{ .linkwarden_auth0_client_id }}"

        PDF_MAX_BUFFER: "10000"
        SCREENSHOT_MAX_BUFFER: "10000"
        READABILITY_MAX_BUFFER: "10000"
        PREVIEW_MAX_BUFFER: "10000"

        # # AWS S3 Settings
        # SPACES_KEY: "{{ .linkwarden_spaces_key }}"
        # SPACES_SECRET: "{{ .linkwarden_spaces_secret }}"
        # SPACES_ENDPOINT: "https://s3.${NFS_STORAGE_SERVER}"
        # SPACES_BUCKET_NAME: "linkwarden"
        # SPACES_FORCE_PATH_STYLE: "false"

        # Email
        NEXT_PUBLIC_EMAIL_PROVIDER: "true"
        EMAIL_FROM: "{{ .linkwarden_email_from }}"
        EMAIL_SERVER: "{{ .linkwarden_email_server }}"
  dataFrom:
    - extract:
        key: linkwarden
      rewrite:
        - regexp:
            source: "(.*)"
            target: "linkwarden_$1"
