---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tracearr-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        COOKIE_SECRET: "{{ .TRACEARR_COOKIE_SECRET }}"
        ENCRYPTION_KEY: "{{ .TRACEARR_ENCRYPTION_KEY }}"
        JWT_SECRET: "{{ .TRACEARR_JWT_SECRET }}"
        MAXMIND_LICENSE_KEY: "{{ .TRACEARR_MAXMIND_LICENSE_KEY }}"
  dataFrom:
    - extract:
        key: tracearr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "TRACEARR_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tracearr-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      type: Opaque
      data:
        DATABASE_URL: "{{ .uri }}"
  dataFrom:
    - extract:
        key: postgres-pguser-tracearr
