---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
stringData:
  cloudflare-token: ENC[AES256_GCM,data:Ia0TTvReleHlYGXDsW6Xxewc1AGb9mVhZftuhHObMlKDzVrR1QCzjQ==,iv:o4BCV5o/iJJL/u+dMe7COgmf/yp/P7ipe9zxlM8d87A=,tag:0MIA5Vet/7UpQFfLdSbQ+w==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYnhGOEN6d1ZyTzVOeWxO
        WHFKdDJpencxTlZQUjF3SzV4N1RDaW9iajBZCjI1cGk0K1dCemY1b21CdDRuclZ3
        RVRZbDE4YjJYcEVVN1lxSFNuQ3lZZTQKLS0tIDRGOTlBR1VrRUN6NEF0TmZBYXla
        Uk10VlgvSTlUVHFPTXpGL1VBN0FiL2cKheYhfgGwTePitnlfAA9HjlllVGlB1qQy
        KVy9lhN1xjZ3vmUcvVu2dI8w8yTyPr9cP6LWiR8i7BixyBKlkp6+fQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-12-01T18:02:06Z'
  mac: ENC[AES256_GCM,data:IjETtkBvorEmsMC0wuedYSA3YMnoJIL6hJ46Mq7KUlnrbWbmCPJfo/4uPC+FYbXzmJ4SbtmpkHjYR3ijB0g9U0iwivBYhXNFIl2iOpvKBHfej/mYbXw6hsk/xAkiiWMlDbD2vsQt9SFSzxJekNYR8Aj9mhM2KnulaKvdd0AnGQA=,iv:J6A650c+rQIEwlDSVY8JX0/aFGk8kSpH2hTYBt5upQ8=,tag:x6X8hGqcObpNL92bai2DkA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
