---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-oauth
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: pgadmin-oauth
    template:
      type: Opaque
      data:
        00-pocketid.json: |
          {
          "OAUTH2_NAME": "pocketid",
          "OAUTH2_DISPLAY_NAME": "Pocket ID",
          "OAUTH2_CLIENT_ID": "{{ .pgadmin_oauth_client_id }}",
          "OAUTH2_CLIENT_SECRET": "{{ .pgadmin_oauth_client_secret }}",
          "OAUTH2_TOKEN_URL": "{{ .pgadmin_oauth_domain }}/api/oidc/token",
          "OAUTH2_AUTHORIZATION_URL": "{{ .pgadmin_oauth_domain }}/authorize",
          "OAUTH2_API_BASE_URL": "{{ .pgadmin_oauth_domain }}",
          "OAUTH2_USERINFO_ENDPOINT": "{{ .pgadmin_oauth_domain }}/api/oidc/userinfo",
          "OAUTH2_SERVER_METADATA_URL": "{{ .pgadmin_oauth_domain }}/.well-known/openid-configuration",
          "OAUTH2_SCOPE": "openid email profile groups",
          "OAUTH2_ICON": "fa-openid",
          "OAUTH2_BUTTON_COLOR": "#fd4b2d"
          }
  dataFrom:
    - extract:
        key: pgAdmin
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pgadmin_$1"
