---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: pgadmin
  namespace: database
spec:
  users:
    - username: pg@admin.com
      role: Administrator
      passwordRef:
        name: pgadmin-password-secret
        key: pgadmin-password
  dataVolumeClaimSpec:
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 1Gi
  serverGroups:
    - name: supply
      postgresClusterSelector: {}
  config:
    settings:
      files:
        secret:
          key: pgadmin-config
          path: /etc/pgadmin/config_system.py
