apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-password-secret
    namespace: database
    labels:
        encrypted-by: sops
        encryption-method: age
type: Opaque
data:
    pgadmin-password: ENC[AES256_GCM,data:PE7Qx6kuqgiZvfps6xRUpw==,iv:E/CGBU7VSvCa0/K9DtNHalcZT4tJMEjwAs+w5W20ZIE=,tag:dR31WFclFrVOdZ81xYrxQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNWJqQ01TNTdWUDk0Y2Vs
            QmxDMlFXdjMrTFBTQ0t6UmJoenIxVHY0V0JJCkl2MWpLSkpZV1pTUG9xcS9OK1lU
            b2t3RDVTdnVHVDRyUGdKV1Y0TTFyMWsKLS0tIEozSDJYREEyU3R2bnZKQk5ibUlw
            RExSQ0tXRkw5dGhOT1Y1TzNzcVJKbWcKr8baoT9Pp+n0rtsgdltsmzTpadSdW5kR
            Hw7MYSC15EydEiaUCJd3bO0v5AOMt4pzX6cNc+wSMBKWBncT1ZESqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-15T06:35:07Z"
    mac: ENC[AES256_GCM,data:WY1h386zPA7ocqwU8gDKEyMu5ecI+M0HmY2S8LMq0/wD5ZnZ7ESemPl3K8+I/TO0PG0heMB/d/tln+GIX5zKkuerhIQIXrPQrDvhK8E8XyS+zzBLCpJ8AgT3Jm9SnGckLeg8sQ++LXO5xtymm/tH+SUSVdvV6SvDsGOOESXme/A=,iv:PcApMlqiHWo2wdpXDh3vDZ6YpWVZINI5gfcygkh0uRE=,tag:1Jl+q9iKAjdEizxlASirpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
