apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
stringData:
    api_key: ENC[AES256_GCM,data:a4/MCwH6S/uwX5UFptAJZ/3fs2fgo2wGVvIWX2J5HHY=,iv:NkBzeDPMme16rblebxLiNw5jHA9mO366xuOkBk9J6ok=,tag:cC7H0dRIAwvnb/xvBM6kfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUVc5cElsNnFBQnNpTzdu
            VzRSYWppN0hCL0VsUm9xdG8xT0NpLzdwdkNjCllPNlNXcmxQRGJrMElhcS80UGF6
            VC83Nkw1R2kvWUt2VitYRFMweUgvU2MKLS0tIGVQeEdLZk9OMHBZYXEweXVhWktR
            Y2lhVVMrQnZRakdyVnYxbVd1OGZVU0EKQ052iMDHjbn39WmSXX/72Opd2a1M9zrp
            aymzqahqNw//3EQJ2EHBxp1lelZMMCrDakyNYldDiSz+Wc9K58bXdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-03T18:23:00Z"
    mac: ENC[AES256_GCM,data:1v25zC6UKL+yZpaPXX6S08tv6M008ChhGq7NnfpXcaW+QCsXYTzkhLOZpU5uNgOHayrqYVxX8ecVStXIyoEYay9YIAlM9XtM7ZhppCAiFtj0XJjLxpXu2U4VxwxY5yqwlDrInT5OgVJUYu7G3Zt+hBqCsM56HmmKu70eQzUjfzA=,iv:1TMRMWTwkgN14x8v8jilNtta6KagRhrREf0IH8Bx3bg=,tag:8/LlBLDeqRz20AzoR6U6tQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
