---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sabnzbd
  name: sabnzbd
  namespace: media
spec:
  ports:
    - name: web-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: web-udp
      port: 8080
      protocol: UDP
      targetPort: 8080
  selector:
    app: sabnzbd
  type: ClusterIP
  clusterIP: 10.43.157.104
