# fly.toml app configuration file generated for vaultfly on 2025-02-09T08:53:49+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vaultfly'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '30s'
swap_size_mb = 1024
deploy = { strategy = 'rolling', max_unavailable = 1 }

[build]
dockerfile = 'Dockerfile'

[[vm]]
size = 'shared-cpu-1x'

[env]
ADMIN_SESSION_LIFETIME = '3'
DATABASE_MAX_CONNS = '10'
DB_CONNECTION_RETRIES = '15'
EMAIL_ATTEMPTS_LIMIT = '3'
EMAIL_CHANGE_ALLOWED = 'true'
EMAIL_TOKEN_SIZE = '6'
EMERGENCY_ACCESS_ALLOWED = 'true'
EXPERIMENTAL_CLIENT_FEATURE_FLAGS = 'ssh-agent,ssh-key-vault-item'
EXTENDED_LOGGING = 'true'
ICON_BLACKLIST_NON_GLOBAL_IPS = 'true'
ICON_DOWNLOAD_TIMEOUT = '20'
ICON_SERVICE = 'bitwarden'
INVITATIONS_ALLOWED = 'true'
IP_HEADER = 'X-Forwarded-For'
LOGIN_RATELIMIT_MAX_BURST = '5'
LOGIN_RATELIMIT_SECONDS = '60'
LOG_FILE = '/data/vaultwarden.log'
LOG_LEVEL = 'info'
ORG_CREATION_USERS = 'all'
ORG_EVENTS_ENABLED = 'false'
ORG_GROUPS_ENABLED = 'false'
PASSWORD_HINTS_ALLOWED = 'true'
PUSH_ENABLED = 'true'
RELOAD_TEMPLATES = 'false'
REQUIRE_DEVICE_EMAIL = 'true'
ROCKET_ADDRESS = '0.0.0.0'
ROCKET_PORT = '8080'
ROCKET_PROFILE = 'release'
ROCKET_WORKERS = '50'
SENDS_ALLOWED = 'true'
SIGNUPS_ALLOWED = 'false'
SIGNUPS_VERIFY = 'true'
SIGNUPS_VERIFY_RESEND_LIMIT = '3600'
SIGNUPS_VERIFY_RESEND_TIME = '3600'
SMTP_FROM_NAME = 'Vaultwarden'
SMTP_SECURITY = 'force_tls'
SMTP_PORT = '465'
SMTP_TIMEOUT = '15'
SSL_CERT_DIR = '/etc/ssl/certs'
TZ = 'Asia/Kolkata'
USE_SYSLOG = 'false'
WEBSOCKET_ENABLED = 'true'
WEB_VAULT_ENABLED = 'true'
TRASH_AUTO_DELETE_DAYS = '30'
[[mounts]]
source = 'vw_data'
destination = '/data'
snapshot_retention = 60

#[http_service]
#  internal_port = 8080
#  force_https = true
#  auto_stop_machines = 'stop'
#  auto_start_machines = true
#  min_machines_running = 1
#  processes = ['app']
#
#[[services]]
#  protocol = 'tcp'
#  internal_port = 8080
#  auto_stop_machines = 'off'
#  auto_start_machines = true
#  min_machines_running = 1
#  processes = ['app']
#
#  [[services.ports]]
#    port = 8080
#    handlers = ['http']
#    force_https = true
#
#  [services.concurrency]
#    type = 'connections'
#    hard_limit = 25
#    soft_limit = 20
#
#  [[services.tcp_checks]]
#    interval = '15s'
#    timeout = '2s'
#    grace_period = '10s'
