apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgB7Xb4GbYfwpZ503WW89Nxqtw6u8lMyJCSZH0ktyQBw1VrYgIWQxkVHk+UirdQdDv6TGZMvCMHPD8Jmk8EQL/LlBR5aQgUgw74O+LRJw9TUl28gmcAGTSw28pHSiHVG8TjdaLlQY4MC3dCWthBurjcMtDv0X+iZVGCgPyRDZ4ek04rzeZNmhNE1v3o4hl9eRWBbXJNQh8a50cCKx0Y4cTM2cAdBi3svnkRKXfZIj8vxbpQ2YqMou2u8xeeU9EZ+lmaCtuxeyS6xf8emSj6OslUeGnVPz1JLwUKIfBdhcniBOTmJmZh6Ztmf/KQ4Zm90MXyAd+IqN1q/pMTcIXy9yBb8dqKKgQaYtMTIkmtl3DgcwDyCtRgbQcF2hCVV0q/joPWv8AVe0zKVbREc2xwizB4YSFx38/8lLZVl3QRsXQBFg+0to2I7CI0PD2UnkFJsU1/UZ3CFMZJIuGyWvk3qluAYv18Qv1iFS52wbR/2GLqhbwkr7zgPv+e/nSg8WOztHJ9F5uAx8NKLR9ReXbtgU1558r2LbeoJOCnFKD0j5jysjOoSUoqqZPV3IQuuwXMmQ7O5XnQ1bGOGJjrwHYGTTPnV+sgoMXCAoyG87IV2r9D9LWyO9HSXxWeh5YDoJC+27sNzdYf/B62PbCibj6yxD9duQmOsq8vPv4tj9AFzw0qzqdIBpkHtJwBsIbFjfEUoxCToCd6K3sn3AbGKU6mZG5mBrzmmeFN7HdPEVkawPRqz4U4iVy/MkhHQ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
