apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: crunchy-pgo-secrets
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: external-secrets-pg
          namespace: database
      remoteNamespace: database
      server:
        caProvider:
          key: "ca.crt"
          name: "kube-root-ca.crt"
          namespace: database
          type: "ConfigMap"
