kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: cross-seed-secret
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    config.js: ENC[AES256_GCM,data:tEaSBPbr826hs/GwoafpPVw2nW4hTViBxAi/eR2eznDdycf8T8b1QxyC+3rNxC1O9zhUEQpXMWtV4eBNrsDxKh/DYURVjUUClo6I+u+ezqhQTHMac4AkozIvEfyOE1FynNvviATMCeg+EFMA32PR2U5koc13PY6fUrvECFG+d3rYXcH3XWX6ZLRhrNT5vGrOCr/IC+W0lHoTC0hhxP8MeKkYGIhpHizUlRE3sHtw9zUc/b2Os38P956JtHcQBf6ZtxKIPh8T1gAIGei5DBBf8tQDSsjnKh2hmHPFe9RT+5MeZgvfs5ISGlzAiPzxd2GzXfMC0K3/O2wKfMLlnj1Paw3heVMe/dG8IAE0yzGQWpyAjbj/wvOvD97IXbcspqIJLXm8T+fbwyTmRNQw9AC+APIn6ZBStcX3qiPZhc39F9c256nI/9SiWeXD5CrK1h84TxN3aZsGto1tImN/kNh8o1FrSR198zm0HJ4uY6WFjLFwBDfYLGwTCJWTMQefULbk7/KVdesnJrQnsfVnSF9UoXT7JnQBEwnJFlgsWVVDi4ZwIiRBfCkTnXjuYQtwlY5YX2XBw/4LHLbs/NBU4MVZwiXKqiZ9f7JqFE/6jOcqYy0+GbgmRV/JnSlwtJ1nphD/8acp1JCm+4JGxLJ3/8isT00PQFgAGmQ+2zlIrTec9B14fip7OXLZU3O+OAEWKs/5B94Kt9597L+GN2/+LyBcsZbsFnFCZ01td059qIUXCoqpqZcWN61Dq1WIh8xYDY2s6bOAjQfdUHstTZj7SFckX6NqaLg5Wgm31ZtbG3G04UtHljj1DldUCHgjnFYtnphcXIJ1Zc9RzSgAh1He0GwtOJIq6QvhLW52EOdPFqK9NcdwIAcLfl82QKylNZtBp2kcmbtccO8QXtqmvAxgjfAUYMy/ICludHaAbrjuW8VGR48liLOzZ7PJAteIk30PVhlFBNHsNbNvWPuyncrkJ3Zgt9y4V9bH00AgoqabDj4aSdy0JobdTgTgSapM4yHZ65eSY9CrVALQPXYLzyZiu2cMSXQGpjw3c48C+m0aJsY57xcHpZ8936hQlwoi76+RiXjOoE5bWOym1eKHm6iK8mhpQaxa+vjHGibLsiY676f+n9IKHqoH6eWU8xH/jaLfFvQfjYGhbwE2eiY/iBrRsy2TJRlOnjNxnm/TOncyQWvsG8qn,iv:p3Hk55EJHpndIL05lrlX5QBFnfQudUQX9GgxFF9xxM0=,tag:7Jyvj8QmkWsE7huR48UCVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMVJmd1RDaXM0enFsR0Jv
            RlVScTZVelczTHcxcUVUNmVldTlyZExwVW5ZCkhuWkJEbXlVT1BIZ00wVTNnU3M0
            V2craHk2SmV1VGUxV2xqTnh4QktZa3cKLS0tIEV6d2tqRjNnVnhuV0YvL2k5SVUr
            YmcwQnl5NUNjQVFvZzFpSmJWY1Y5Q2MK2IgIBTAR1uBQ+zUrQkRyN2F+7xM7f0EO
            Xxpo7ue1mo5qA8XeeKMjt1+5yRuq2sSwhZvY/UpZmsBBj+Hb5R5FaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T18:09:44Z"
    mac: ENC[AES256_GCM,data:tQ7BUrjvHKPpEM+B0rvpk9JgY6WImDinD9sA5GayXN/BGuL8HGzernsdLbHQ7dhPl67kbsTJ+X9nUvpExVsR5uBF0nfhVQkNQXEtd0F0jTLmmMLuVGmpEIhjMHcZZQeOjwLRp7EtHScQpFoFxyj0T3poah3uQc3azy2cTDSmNio=,iv:B4stQmmxqu5XHRozTCly9lFa8IcDcuqXl9vGUJUXP5g=,tag:90n9kr7sDP3ctFv2D6ad2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
