kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: cross-seed-secret
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    config.js: ENC[AES256_GCM,data:zz9DehC/SrFaj0yXdhNp1XJTOc88cyS6JKRxPeYA9bsfz8HE8FHUK1Ix1kiFSlNZ/sYXo0Q0ptKtYpRyQJLfSYMttkpHjM6LMHjHnH9TZekq/Kcnb4kHD/hSxaMcvbw6H/x6ggUQO5rhT/v13xMHk5uTW2jLCezmJ5owgwqYvT+SmICVP5qWbZgR8aBtyHgFKuH9U+JrXk1dnhbgw3iX3OMX2z6jupu1GAlxaXpQMJRqK3lyJ/d+ZI9sL4XQ4O1lkTX3YjExXJ/fH8ivmJCdzuftFnUAOFE4GpeDH9VWCPdm2iBA/mX/soc02qZlfsUcPA5mahdO2wYqgCb+bwXBZQJUaHpSRrgFZ45Q3d9dzX55gCdSl3M50SUgJV6gi+H3Y6F8K+pz84Fh82NuRamZc9yLcFQUZwshJ5+e9FL8LYhplN4BfiKqiNHOGEAZLWiZWrCvo0vG+SqP+4l1JHUP1xSdJtI+BsyBy9M5bjb/4fVIz1s6ER5jTloQPVaDAXEUr8sFXOW/laZjoSHSZnIikFR7w4Ax+sUZ0A1LA9enA3lGhZn3sQNYCkZNmT/VsRKsu3CtzZBxg6NwLJQSVhvvS+oB1AhHxDqMwmueqHJC7P3yMFaF8X/EChdxusEIgTYZdyRlA9m7hMmKP6fqO99g97JHTG1PqLmlTVQvtdcm8viAad8cgVYQpfmvQyM6OEyPXWocLovxjFaOM9+Qx2EZwION6Miy+ZJH79vmPI5cE+ztTGs/ooWrAsoLRsox8E7QlXs1HxFH32nzRqVaDCmjYH4hsw5x7986ACDXmrOFF2J/S29Afjhq4413MLmDf1Bn8F3Ufegq6LfI3PrxzucyE8yh9cFSYumURhePkpq2ZGbTIpqw3+TXmvITtwHi293iFSQ3mkNPtUa71tLu9652AUUReOHeaxc270Mnki4Z5F4tyQtNIb57TfwThNFduO3v204fQ/hBHOcksfuJYsLdd4jTjeP7G10DHND8wRzsgNqsGTtfqvxACM15hxYgAOh8inbHJHCqICskFDOmSioWDzHVLGWzCbqQzRa8BEJwW0gLjT0eRQAlVIBfeEuluROtj8jjcB3YMetF+v8No9VuPAH299g1Ma5+4Bwj/qc2/wQGHqKi5oPZszg02AtyzhRpfYO/rUQPTI6GBpg77pPC6XpfYhD+lfSeujE+/FcOsRG1iYsrctfbumGVKnKwB9c8BH7PNj6pmqhHPs3S89v/BuQ5Vi127TUJT2jnxJH470OoMxiAumXcfGPr8esfSvYfrZWCkC49jWgVIi6UE7gNijRKP9d6mQu4K7T7wsFjLbIS1fHwi2/cFKu/,iv:Honnk+xB9jPaOvGv++6ZdFfQrZ7y9c/dfkLtb5BJgos=,tag:7lxGpYqvLZohK4fjGbS/hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMVJmd1RDaXM0enFsR0Jv
            RlVScTZVelczTHcxcUVUNmVldTlyZExwVW5ZCkhuWkJEbXlVT1BIZ00wVTNnU3M0
            V2craHk2SmV1VGUxV2xqTnh4QktZa3cKLS0tIEV6d2tqRjNnVnhuV0YvL2k5SVUr
            YmcwQnl5NUNjQVFvZzFpSmJWY1Y5Q2MK2IgIBTAR1uBQ+zUrQkRyN2F+7xM7f0EO
            Xxpo7ue1mo5qA8XeeKMjt1+5yRuq2sSwhZvY/UpZmsBBj+Hb5R5FaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T17:28:05Z"
    mac: ENC[AES256_GCM,data:b1K4uoorUo6tRz4upjzQbScLWrHmRhQvC91OuZSpFmUoontbqUU/gtJ4TWDT7tPd90lwCvRuZF1ecO0SLlf/04jtk4/AEVpgVo4NPH7VQdK50RK4BS+ncVrr+gduBq4HhSiHWEFM2AoGQ05NaVIg5of6FiMIl/vrl/Wj0zWmIkQ=,iv:YH1JN3hNRdpEaRl6SWjOBMWg2+98zSi4bG+3+aEdfRo=,tag:7L251vGzkzkgiK1xEMmYNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
