kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: cross-seed-secret
    labels:
        encrypted-by: sops
        encryption-method: age
stringData:
    config.js: ENC[AES256_GCM,data:VusM7kE3vWHn1VXuQmXLM5RpQEdhnSfDRbnUlHIodYpn8QHCWUGuDZyrEZhBuLp2ivBKHD5P+zBrOM4HdLedgTjxiCNHeE2Mo1ewEoowY9nuYXFZQzPa6Hxfkr4nD4Sh5JL+GhMJtJ1q1iH0w3K8pXukN7dQAugB62jP7oiTTqjJ6c/FruroHbXeRO/OueNCk2SkDYlFs2eMYvHLlpR/+jSya+cXz+REfMuh2asV4EkRCY6DI4IDVZ/fr+E3C1LRaC2TQEOW7U9uKB/A6sbec/OvinwsLQusOaKes2SHqLDFNnjyp9D1kfES79Yri50Z3nCs6YRF9Mp74FSgaSU8PNFonQQsQsoRewnj+MXrvXTH+hM7opNF2++Koo5ip+wzmVfgecQ/pa9uZCAcos+4izB8HHM/PCvhXwTDKm5eXLCayf5lFFJ7BC4s2bppx1LrZUhP1hDis+i7mP133IGQLLIV4OLAPu6uDh2mfTXrwHGTGl3k7ohw1U7Q26U5PkQa2JnElnSSUuImaX6VWvgPrFBHQiLGTKW0U7HG91dl6kaD/OcSxDyeKVbQQIodi9FmWCEkuKQOiOqpeT2hQK+WeECexl+B24+tXaJnhrOA+vfP4CraxMl8lSam3vw8M3ghN4pLPyLq0t/CY7T0V8K2Ng8YgZeZSBe9W2f7NdvnIShe0xK4IP18O9YFrLcCLS7BRVdpLLlVBYqTJ5lPghIXLGPYyeS0mHVHvdXyKpEs2gwZ7eXcqnm+/9EsMgt5EZx2W4D3vdfr448yO7/Qg1fwI5Y5m5V6dQ96pnZkM0r5nyk7w/U6/i9S4UjMLxQQEuGOZ6mXkHlUihjI730uZxDBKfPOuH0qNWSmPwhYOfDIwQRrE6bjWBCvwTf0uAcW7RV22E1XGUbsAM00mo7orh6ai7vygGBxG+ugnbFpS4fm2nON4txwQjbq+7lMSlN8AKqp/1HWPsMarBktZI1tQvNVSJpkVZviBKzRHQuwwqRmZLSLkDYJn7AncFGCLN4YSyX98vsv/s7f4V4fcPlm1aLtt7b5RkxDj2DFbCdowb6gciPzbfRVa9AzGcMWVe2nEbEO4uwwt+5ZE7wmVYVg0usGSacAjuxtQvtr1+qVS4J5cru8lU11sxhlezV9mJFgwtYQJyT4a0iCDEwvz7z5q7ab0bg7VhmFNInbqJC6ZteRCSGwJ/hJOLPRuKeL9IHytG9AipGlPApHM/fzdMI0JH5wkBB5L0eI6e74O7nIAQmc22WGAIYjyUF0lkfh9qs9V6EXwkmZZMiT/m4Qi/7eF1VU65aEyYLmUb4cHTp4QE03l+ofUWomtVUk7h+z7KX2Vu1dOmkoBQJtPRTeKdpv/lQ=,iv:lyZu/PeLWjbQLmZykid8fVyP1WBcFqIrG9CU3GPY5lY=,tag:AtPNL0NUr/ml62l7X5Qi0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMVJmd1RDaXM0enFsR0Jv
            RlVScTZVelczTHcxcUVUNmVldTlyZExwVW5ZCkhuWkJEbXlVT1BIZ00wVTNnU3M0
            V2craHk2SmV1VGUxV2xqTnh4QktZa3cKLS0tIEV6d2tqRjNnVnhuV0YvL2k5SVUr
            YmcwQnl5NUNjQVFvZzFpSmJWY1Y5Q2MK2IgIBTAR1uBQ+zUrQkRyN2F+7xM7f0EO
            Xxpo7ue1mo5qA8XeeKMjt1+5yRuq2sSwhZvY/UpZmsBBj+Hb5R5FaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T17:58:19Z"
    mac: ENC[AES256_GCM,data:i+buzLVWYQSNbRcERWOnrFUi7LG/5Kj7i1PAr3Fro8o2fU1pAcc3xe5k1r/kfDgcuubUCUci9/2U/NU1UejyyNlp6VTmKyLgM/nt5CrkDye4zjShjTUiomqTtEMudxhnWyb79Rs96dquUerAe5AKg5bhkr5MV1iF9oGFwGFGRVw=,iv:0jPgHMMCQmWnW63r3KjMwGu46Yy1Od/qrnVRTJ3eD0o=,tag:TXcjcCINsAGpEjRBUbcJAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
