---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app-template.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./crunchydata.yaml
  - ./envoy-gateway.yaml
  - ./fluent-bit.yaml
  - ./grafana.yaml
  - ./silence-operator.yaml
  - ./tuppr.yaml
  - ./victoria-logs.yaml
  - ./volsync.yaml
