---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: freshrss-env
    template:
      type: Opaque
      data:
          OIDC_ENABLED: "1"
          OIDC_CLIENT_ID: "{{ .freshrss_auth_client_id }}"
          OIDC_CLIENT_SECRET: "{{ .freshrss_auth_client_secret }}"
          OIDC_PROVIDER_METADATA_URL: "{{ .freshrss_auth_issuer_url }}"
          OIDC_CLIENT_CRYPTO_KEY: "{{ .freshrss_auth_crypto_key }}"
          OIDC_SCOPES: openid email profile
          OIDC_X_FORWARDED_HEADERS: X-Forwarded-Proto X-Forwarded-Host
          OIDC_REMOTE_USER_CLAIM: preferred_username
  dataFrom:
    - extract:
        key: freshrss
      rewrite:
        - regexp:
            source: "(.*)"
            target: "freshrss_$1"
