# yaml-language-server: $schema: https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-db
spec:
  dataFrom:
    - extract:
        key: postgres-pguser-seerr
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: seerr-db
    template:
      data:
        DB_HOST: '{{ index . "host" }}'
        DB_NAME: '{{ index . "dbname" }}'
        DB_PASS: '{{ index . "password" }}'
        DB_POOL_SIZE: "10"
        DB_PORT: '{{ index . "port" }}'
        DB_TYPE: postgres
        DB_USER: '{{ index . "user" }}'
      type: Opaque
