---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gotify-secret
  namespace: utils
spec:
  encryptedData:
    GOTIFY_DEFAULTUSER_NAME: AgAJ2nmx9RpkgqRv0gU136PxngbURdnLDLz5t6TDzSZEUeKzOWuvFob2eS/l1mIYnpIPAaENxlJnjKTvMNyIoTpPVXv8O6v6y5ZVpahKD5IFnhT7CNFuguEVI7MfK66Glkq1mpO35f6SwNP58DxaP3irWe72Gs6Ig7rmbHeCZo+7own+fjIC8fBgTyWvyxGn0BWAt24fGxRDUahN6EvL9/9YoJOCdBbPW2kXQSfqnGhqI13DuhXuduwJwx4mvZuFK75WWWuwLLL01GLxPA5EOL8S0WFzGMJdxPwww5m/pwahmp++lwddpXLJ92ptfWvEItwM2ugBZ4XbQLhmyL1I8bL9NxuB+rrRM7horBdHYSRWJ9mWVVG9+JPY0GN4b8NK8oX/rU6oirNf7aAzpB+jU8H74eznjg7UZJadJXqmBgXIMZ8NGyQdR9e4BWgDmMZq5QVtMKANuJIz1A9Z9y5MWDO8Sb5hDTXHaG15GquVT8xyGSGJrLnJo9JnkKqfaEqH1MSh415bBaqou9HNJ4djQ5cmdPv4OJ0Ixsc2yCoAea/Goa2wg929KKq59wvNQsxxK+7Ml1R+W7cWX2bjkOZHx1FZFBL8FAgaCTkvydSC6HvLnQ/W5Y6TcjLYWvJ1DXwG96d7aHo/QCmVEchJOtFZvKgg6iDmEqVTGOKuycWsaPQHeI8lsxXLSj3zk1KUYxTjasLa+MMvvQ==
    GOTIFY_DEFAULTUSER_PASS: AgCoWING4F39xauHwQPPpzg/uls2aTyu79G7IlI+Cpewl9LBNGszPe2eQBJt8xZi56miwUbqnCqhn3LKe7DJiC+mA36f+fsHtS4yAUOiV0k5kBtK8vJXUQrZN0U1OQckHe8JHAyEWHWuUXf143YkketSmpPNkwr3RCI+NvBBBKOMnSPzJfmcr3rvOoD2XFX9RBhSU0lOhmozRUtEsslSu9xi088WB78VzE8AqpkuD80clDSVTctb0+WV+9GWBTjDLSQbo8kXbaryZzwCGm/eoaxSE/RoeDZFhwLIiM2KNG1PHAq6KaF8k9ktep3NOqCqMvhoWHeMH9+ORwoKSGSahrljLxipiF4KxVnqVHDf55woeUrpXDO1VrpGQn8Lv5JUKkck90Jir79Uo/qN1AUMpwSTRMT8vg0UXcC7Qcp7wpmHwkO8z9XoDgLKN0aDowzkzUJN6SAyyDAqUl8SZEbedZZG1dnkP+tOPSmdupmoFCeFGN6iQ9eU3QF7ohY5DH810DGcXodCzhMVXtTtFh+z/oa7optTI+OYQyo85897DAkDXvFpk6o+T4ppLzt+QoVktekULNq1Zztz9Gg1pUqZICLvRJafio1U2rx6lrDLknh5XbKdxOiBAcuI4tQXWBVLKXyjAy8lSlVJAQ7rwRTjmw7TeatSHVGVUWOU/xNtOJcxzWzkyt1t5NODFX/DOluQDeCrGE+8tw==
  template:
    metadata:
      creationTimestamp: null
      name: gotify-secret
      namespace: utils
    type: Opaque
