---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
  labels:
    encrypted-by: sops
    encryption-method: age
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:K8T8cn411rmsU9NaL7VdgQs2GXbxFL0ueleLvJSkYqhOfpCJHmnBQN5Vfn0y+CGijgyjrYhLZRfH9qldIwI+42PhsCBjAbduRiKmIjfgf+A=,iv:1yw1CcaZtVa5iqauSPLfklAXKH3DV3iyRzXa2Yl7wAg=,tag:kc8wKezHE7MXRn6rZfiSLw==,type:str]
  AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:YxpJRA==,iv:OsXmSWnwMLhLq0uNvNpRy9WBEl8lwqIuKNJORVFMKNk=,tag:GluZ70qoBXWCdlXs3A3AEw==,type:str]
  AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:/dkykR2qu2EbFRcGAcrN,iv:q9L+Tk48jYaugmltumyJTC7OsB8OfvT5zEmBPgDcWZE=,tag:2sClB1Unk0pQFJAWIIdOag==,type:str]
  AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:90N/,iv:GbGXqPwXLfoBr0hYxDpQMRGsQQHJdBkgTJrhxAf7yuY=,tag:FUqC+yZCnaBEoxm248l0tw==,type:str]
  AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:HVqIl0MQ,iv:6UImt0bpO4RRr5eUeIg0gK1WbGBB0D3FwbvQcJWtxaI=,tag:pmMzY0/Bhf96d4UWHkkR4g==,type:str]
  AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:M7bbk4ONZuuIskvS7iyyulqoaDjwaWuj+/PABg8qch/MIBUR,iv:6c81I1DizKs78tX3NIv1NiPIL9AC2qVJMc16JRZX0Mg=,tag:5h+Hr7tc4D13R6LWTIk48A==,type:str]
  AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:DO+Jmw==,iv:UOpE5/q60RzRMh5SASOS701kY0KVpSHo9hpFqk06i0E=,tag:bg6ld4laegZDBNg5CASUSw==,type:str]
  AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:U6TSoNg=,iv:ptT9gW3eleLv7W/480ciTyt0Xio92CoNeGOj8SSsMfI=,tag:vws3xWsW30YTGwDw6btYmw==,type:str]
  AUTHENTIK_EMAIL__TIMEOUT: ENC[AES256_GCM,data:dZs=,iv:1mKu6Mb6mEs/WT6muVfla3cYNHj5ZNUJRGhX37PfRnA=,tag:VoX/eyZ3K/bXduxL4+HxEw==,type:str]
  AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:WIwEQZe3NjqMp5hfdkX1VUPb9JE=,iv:HehYikKy7SLsAi/b2KtxG5JA8XVhV/neBbvM3yjlm3w=,tag:Ac3x5zW4w9T+oGY6lcVhVQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTUwvN2ZONmNvTXN5cExs
        bjNrRE16cnF6TWNOR2ZOa1ZzMFh5TldLV3pNCjFvbm1OamhOaEN3Q0p5U3dqZVJj
        UHJOazdkVmRrY1Fhb2pnTktwcTdSMXcKLS0tIE1wTGtNS0xiNkN1RDY0UHU3WHo3
        NUxwZWZ0T3ZOTEwwc3lqMjk4K1RySEEKXqlX3ZJUQLQPrXL39ONFJoj1ZVJGh1m6
        o92RTLyZzjFTnjISw/6mPc+hOBzH8MLJ9mjKYIuro7PnkFaFEBb8Bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-12-15T20:29:57Z'
  mac: ENC[AES256_GCM,data:Srmqv14uUtpjls+7+1G0yRAdg/LFt54dnzuTQ8NqVjmp+4tHoG7ktkJHvjHbKalblaIFmxIcDMdNCzYGw2pNtRhck0EeKkwaXCd2Hv1XKhtj0I+1ridpDw27aBS4Fc0vop6VMykvdof3EjZmNc1IXr98B8fkHrhUSY/Rq4Smi1w=,iv:BCbPtzoSuR+6q171SuR6KQc39d1OEE+G+8c583E3fHA=,tag:LE+x+dgI5FSJ7iGhpFXvsg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
  name: barman-credentials
  namespace: authentik
  labels:
    encrypted-by: sops
    encryption-method: age
stringData:
  access-key-id: ENC[AES256_GCM,data:R7tHn/aQxijS/hEhkqcT35Z1QMcYb7LsZSyuPtlwEvc=,iv:xmBUNFZemsuYoKnuJKIMfE4g31AoK/YzyGQ5/Gsf+ms=,tag:t6nmRfbeGuWtQRoeZSJUgQ==,type:str]
  secret-access-key: ENC[AES256_GCM,data:1d6GVIAAL8KPI33AIfR0v7NhW5NCCfYXR6Fj/Pl/qky+qOcPMS9z4+jczpGHvbQ73mM3kVZkpz+OiDipUUCs9g==,iv:TINOgie0ez2Jh+EYE2XSP4+uYi4FdibtXI32ennJJ3A=,tag:L9O4OBxRbwMMk4gueLDX7w==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTUwvN2ZONmNvTXN5cExs
        bjNrRE16cnF6TWNOR2ZOa1ZzMFh5TldLV3pNCjFvbm1OamhOaEN3Q0p5U3dqZVJj
        UHJOazdkVmRrY1Fhb2pnTktwcTdSMXcKLS0tIE1wTGtNS0xiNkN1RDY0UHU3WHo3
        NUxwZWZ0T3ZOTEwwc3lqMjk4K1RySEEKXqlX3ZJUQLQPrXL39ONFJoj1ZVJGh1m6
        o92RTLyZzjFTnjISw/6mPc+hOBzH8MLJ9mjKYIuro7PnkFaFEBb8Bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-12-15T20:29:57Z'
  mac: ENC[AES256_GCM,data:Srmqv14uUtpjls+7+1G0yRAdg/LFt54dnzuTQ8NqVjmp+4tHoG7ktkJHvjHbKalblaIFmxIcDMdNCzYGw2pNtRhck0EeKkwaXCd2Hv1XKhtj0I+1ridpDw27aBS4Fc0vop6VMykvdof3EjZmNc1IXr98B8fkHrhUSY/Rq4Smi1w=,iv:BCbPtzoSuR+6q171SuR6KQc39d1OEE+G+8c583E3fHA=,tag:LE+x+dgI5FSJ7iGhpFXvsg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
