---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maintainerr-overlay-helperr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: maintainerr-overlay-helperr
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        PLEX_TOKEN: '{{ index . "token" }}'
        PLEX_URL: http://plex.media.svc.cluster.local:32400
        MAINTAINERR_URL: 'http://maintainerr.media.svc.cluster.local:6246'
        IMAGE_SAVE_PATH: '/opt/data/overlay-helperr/images'
        ORIGINAL_IMAGE_PATH: '/opt/data/overlay-helperr/images/originals'
        TEMP_IMAGE_PATH: '/opt/data/overlay-helperr/images/temp'

        FONT_PATH: '/fonts/AvenirNextLTPro-Bold.ttf'
        FONT_COLOR: '#ffffff'
        BACK_COLOR: '#B20710'
        FONT_SIZE: '3.2'
        PADDING: '1.2'
        BACK_RADIUS: '0'
        HORIZONTAL_OFFSET: ''
        HORIZONTAL_ALIGN: 'center'
        VERTICAL_OFFSET: '3'
        VERTICAL_ALIGN: 'bottom'
        DATE_FORMAT: 'MMM d'
        OVERLAY_TEXT: 'Leaving'

        ENABLE_DAY_SUFFIX: "true"
        ENABLE_UPPERCASE: "false"
        LANGUAGE: 'en-US'
        CRON_SCHEDULE: '5 */8 * * *'
        RUN_ON_CREATION: "true"
        REAPPLY_OVERLAY: "true"
        REORDER_COLLECTIONS: 'Delete watched movies, Delete watched episodes'

  dataFrom:
    - extract:
        key: plex
