---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy
spec:
  gatewayClassName: envoy
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - kind: Secret
            name: ${CLUSTER_DOMAIN}-https-tls
          - kind: Secret
            name: ${LAB_DOMAIN}-tls

    # SMTP
    - name: smtp
      protocol: TCP
      port: 25
      allowedRoutes:
        namespaces:
          from: All

    # SMTPS
    - name: smtps
      protocol: TLS
      port: 465
      hostname: mail.${CLUSTER_DOMAIN}
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All

    # SMTP Submission
    - name: smtp-submission
      protocol: TCP
      port: 587
      allowedRoutes:
        namespaces:
          from: All

    # IMAPS
    - name: imaps
      protocol: TLS
      port: 993
      hostname: mail.${CLUSTER_DOMAIN}
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All

    # ManageSieve
    - name: managesieve
      protocol: TCP
      port: 4190
      allowedRoutes:
        namespaces:
          from: All
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: envoy
spec:
  parentRefs:
    - name: envoy
      namespace: network
      sectionName: http
  rules:
    - filters:
        - requestRedirect:
            scheme: https
            statusCode: 301
          type: RequestRedirect
