apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kube-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.2.1-10.0.2.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - kube-pool
