---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chart:
    spec:
      chart: cilium
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.18.4
  interval: 30m
  values:
    rollOutCiliumPods: true
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList: 172.16.0.0/12
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 7445
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    l2announcements:
      enabled: true
    k8sClientRateLimit:
      qps: 28
      burst: 32
    # devices: { enp+, eth+ }
    endpointRoutes:
      enabled: true
    envoy:
      enabled: false
    gatewayAPI:
      enabled: false
    hubble:
      enabled: false

      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
          annotations:
            grafana_folder: Cilium
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Cilium
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
    externalIPs.enabled: true
    loadBalancer.algorithm: maglev
    # routingMode: native
    # ipv4NativeRoutingCIDR: 10.0.2.0/16
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - PERFMON
          - BPF
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
