---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap-secret
spec:
  dataFrom:
    - extract:
        key: lldap
      rewrite:
        - regexp:
            source: "(.*)"
            target: "lldap_$1"
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: lldap-secret
    template:
      data:
        LLDAP_HTTP_URL: "{{ .lldap_url }}"
        LLDAP_JWT_SECRET: "{{ .lldap_jwt_secret }}"
        LLDAP_KEY_SEED: "{{ .lldap_seed_key }}"
        LLDAP_LDAP_BASE_DN: "{{ .lldap_base_dn }}"
        # If using SMTP, set the following variables
        LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: "true"
        LLDAP_SMTP_OPTIONS__FROM: "{{ .lldap_smtp_from }}"
        LLDAP_SMTP_OPTIONS__PASSWORD: "{{ .lldap_smtp_password }}"
        LLDAP_SMTP_OPTIONS__PORT: "465"
        LLDAP_SMTP_OPTIONS__SERVER: "{{ .lldap_smtp_server }}"
        LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: "TLS"
        LLDAP_SMTP_OPTIONS__USER: "{{ .lldap_smtp_user }}"
      engineVersion: v2
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap-db
spec:
  dataFrom:
    - extract:
        key: postgres-pguser-lldap
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: lldap-db-secret
    template:
      data:
        LLDAP_DATABASE_URL: "{{ .uri }}"
      type: Opaque
