apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_NAME: ENC[AES256_GCM,data:S8VztXU=,iv:PStap4Lie0pN9QBArYFvRPNqsqZusE0Og5dbBc9HO4k=,tag:P77gCDGfSpugH4z2Qxc/0w==,type:str]
    EMAIL: ENC[AES256_GCM,data:YAaUpS9H2oDVITj+gr444i5ZNdrpiys=,iv:SEfjdFF5kvY0O1ccvUNRZxqvafRbD9gIajxxdA1W8qM=,tag:+6qywQBt4EVYSpWT1d/Iyw==,type:str]
    EAB_KEY_ID: ENC[AES256_GCM,data:VdvsB7FayOkxFCVl7ZMpG2p0u9hF0Q==,iv:B1BW6RXH2UH9rrrKF+QoOpKvkxBLwEaZRy3/JjjeYys=,tag:g2JJ76VldFoVj3TW+xAzcg==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:uRA0kPDnQHTWsKFALdLh,iv:fby5SD6lHPx1SV/mhC2l4tOGAanAQeS8fkVjPAnh8KU=,tag:uX++0YaurWMQQzGh9abjFw==,type:str]
    LAB_DOMAIN: ENC[AES256_GCM,data:xwVt1vI8FZMZ,iv:9eVEqQ2JuHNE2woNWGceBOyeuYR8NZkVWQLJCcNI0pw=,tag:3aJn42qbsCx23MUcHaBpSA==,type:str]
    BAO_ADDR: ENC[AES256_GCM,data:NOp8r9L6XsUOgIT8ys2JezYJRZKM,iv:1WrHTHzyMHHVlSzLgYpCVBZ3rBF2aIFi+AWh1a356m8=,tag:u1+ivK0GW67ctZ1f1vmC6w==,type:str]
    BAO_SERVER: ENC[AES256_GCM,data:cvegd7G18z1n9HGrSA==,iv:cFGLGDgah2oInuiVjUJnanWgJWXARID6OXUxPiM/UAY=,tag:AtJDMS+IBVFZS92UsOP0ug==,type:str]
    BAO_ROLE_ID: ENC[AES256_GCM,data:5BuMU7S10V3jwIxsgGrfoAR5RAZn57umwaYh4fHtdDKKHTPv,iv:U6SwW3lhTBhNnUQeTEE7joSAdhWvaWpduaaNbTLh+tU=,tag:WqWe1FzRO2tx5iYAxUN5PQ==,type:str]
    R2_ENDPOINT: ENC[AES256_GCM,data:AP0OvG66vjTb6mM+c5Ly+4YhDsF04vqaR67Y0Ct8fwRlnO0eviNdWfnL3JPeo8a0uAuzh1iBtYoUaSWtE1Yzypg=,iv:DmLjkw1KcAoi0t1sadAMnaHWHMAJLnvteyssWdFbmEw=,tag:2t+LesxBuVVY3flj0QTuaA==,type:str]
sops:
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTEtWU0haK2NqMjR5K2ky
            Qkp5aktaSlZqQXYyVytSM2FnQXozYWIvUmtRCmhMS1VxQ1ZOaTV4emcwVkRBNFBI
            YmgrMnFKaHBmVW00RDgvY1JIUjhlWmsKLS0tIG9xQkIwSVJPTkFNNjVaanlOWGpt
            cFZoUmFZVjNMTHU3RkhJNjE1TkF5ck0K4CWU3xvtlz26FkRx8TfY0jsppqAXaHdK
            EU/LOu8UjW91x++nKoYatCcm+6aj61iQkmWB9nuDp22LdDFjrvNAJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T04:35:17Z"
    mac: ENC[AES256_GCM,data:dK66VddBsykvadnDAvpOXvQZubgxGX5p++eergoI3CPSKQVvCbuCvLaeI0LqBGVFTJf6qNldlbXFFSP4DxRy4HuVXgBMEqbpwRaUsQHn2KnP0E3rO61YZ+FnM8oSKT+soJSavxIgCBuOQyHa8ld4H7UN2NTHTM1HktKwUOqCDJA=,iv:Ed1zvwUnREmoY3ecaGeTb1+LHeXNa5y+qrhbKwVnnxY=,tag:Re2jdQlrCj/PkKZGCHLiFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
