server {
    listen 3000;
    listen [::]:3000;
    root /out/photos;
    location / { try_files $uri $uri.html /index.html; }
}
server {
    listen 3001;
    listen [::]:3001;
    root /out/accounts;
    location / { try_files $uri $uri.html /index.html; }
}
server {
    listen 3002;
    listen [::]:3002;
    root /out/albums;
    location / { try_files $uri $uri.html /index.html; }
}
server {
    listen 3003;
    listen [::]:3003;
    root /out/auth;
    location / { try_files $uri $uri.html /index.html; }
}
server {
    listen 3004;
    listen [::]:3004;
    root /out/cast;
    location / { try_files $uri $uri.html /index.html; }
}
server {
    listen 3005;
    listen [::]:3005;
    root /out/share;
    location / { try_files $uri $uri.html /index.html; }
}
server {
    listen 3006;
    listen [::]:3006;
    root /out/embed;
    location / { try_files $uri $uri.html /index.html; }
}
server {
    listen 3008;
    listen [::]:3008;
    root /out/paste;
    location / { try_files $uri $uri.html /index.html; }
}
server {
    listen 3009;
    listen [::]:3009;
    root /out/locker;
    location / { try_files $uri $uri.html /index.html; }
}
server {
    listen 3010;
    listen [::]:3010;
    root /out/memories;
    location / { try_files $uri $uri.html /index.html; }
}
