---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-web
spec:
  hostnames:
    - flux.${CLUSTER_DOMAIN}
  parentRefs:
    - kind: Gateway
      name: envoy
      namespace: network
  rules:
    - backendRefs:
        - name: flux-operator
          namespace: flux-system
          port: 9080
      matches:
        - path:
            type: PathPrefix
            value: /
