---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: utils
spec:
  encryptedData:
    WEBPASSWORD: AgBLCdXoMYpdsxiUI4+CO72lwajIPqBfqWsM7VTNLEAfUsDt+Yqb8xPxoNMM3eA8mECxSU5ZqTIn7MG/08OvW+SuLfiPJeEgdMVr8i6/Y43y0XhvxQR7DAWpszGsLGReHf7I2ShoYDNjDPWzoXEX9mrWv8atjh3bWtbsJvQEmRkr1xZGa7bMlw/Wx7HHmigMpN7p4xOEfRJVnKMJxcehsprqJrcey+Pmfgu7y9GSQiH+685hlwsDbyHcwib6dx3bcmyvV/RJwEjdgh7Uk2c4JsDAJ9704n1UHXYod3YBSmsu4bWRTkPIu8Y8al4WDfAOoUeyE6mXQ91oml5BhYSLGF8WgTT16cOZOh0kCR+ci9mfCeh4+ZNGG/lZK04Zk33XcqHQ++njSmOadscSaW7ly1W5jOaIExjtQuqs4a7IOjqB6Nq4Yq8aPYLp0q6kByrHxz4hoqTbG51AIBv+DwNFKQx4zUf7jBWV7bYpElrUntCT4vvHglIMGqkeHgbfg2duBl1GbIwUYgXaukjG54gjhReEt+bPfw+tsY1qU6WsfS3HaBd3tXmnnMw53o+AttRxCx22qT2D8bfF7coWoDeHPdOtS1i8OfXzHZA47hXQtjBJMIAgn7f2QKuz54Iw/gVTQpmBWjxPOeAncn2bD6VqJxoJcPeKujtXEZVcES3zgLVIMLR7on8bJwfOIliqS7PHoVg0lXUREA==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: utils
    type: Opaque
