---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  chart:
    spec:
      chart: snapshot-controller
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
      version: 5.1.0
  interval: 30m
  values:
    controller:
      serviceMonitor:
        create: true
