apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./default.yaml
  - ./helmrelease.yaml
  - ./dashboard/sealed-secret.yaml
  - ./dashboard/ingress.yaml
  - ./dashboard/middleware.yaml
