---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperless-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        PAPERLESS_ADMIN_USER: "{{ .paperless_admin_username }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .paperless_admin_password }}"
        PAPERLESS_SECRET_KEY: "{{ .paperless_config_secret_key }}"
        PAPERLESS_REDIRECT_LOGIN_TO_SSO: "true"
        PAPERLESS_DISABLE_REGULAR_LOGIN: "true"
        PAPERLESS_ACCOUNT_SESSION_REMEMBER: "true"
        PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
        PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "SCOPE": [
                "openid",
                "profile",
                "email"
              ],
              "OAUTH_PKCE_ENABLED": true,
              "APPS": [
                {
                  "provider_id": "pocket-id",
                  "name": "Pocket-ID",
                  "client_id": "{{ .paperless_pocketid_client_id }}",
                  "secret": "{{ .paperless_pocketid_client_secret }}",
                  "settings": {
                    "server_url": "{{ .paperless_pocketid_server_url }}"
                  }
                }
              ]
            }
          }
  dataFrom:
    - extract:
        key: paperless
      rewrite:
        - regexp:
            source: "(.*)"
            target: "paperless_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperless-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      type: Opaque
      data:
        PAPERLESS_DBENGINE: "postgresql"
        PAPERLESS_DBHOST: "{{ .host }}"
        PAPERLESS_DBPORT: "{{ .port }}"
        PAPERLESS_DBNAME: "{{ .dbname }}"
        PAPERLESS_DBUSER: "{{ .user }}"
        PAPERLESS_DBPASS: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres-pguser-paperless
