---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      data:
        PAPERLESS_ADMIN_USER: "{{ .admin_username }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .admin_password }}"
        PAPERLESS_SECRET_KEY: "{{ .config_secret_key }}"

  data:
    - secretKey: admin_username
      remoteRef:
        key: 702a171d-faa9-42ea-9072-a535a1cec1f5
        property: admin_username
    - secretKey: admin_password
      remoteRef:
        key: 702a171d-faa9-42ea-9072-a535a1cec1f5
        property: admin_password
    - secretKey: config_secret_key
      remoteRef:
        key: 702a171d-faa9-42ea-9072-a535a1cec1f5
        property: config_secret_key
