apiVersion: v1
kind: ConfigMap
metadata:
    name: immich-postgres-env
    namespace: immich
data:
    TZ: ENC[AES256_GCM,data:RfZ+7BnnbIZ+ZeFa,iv:lL9wHUJnBPUmDf39N0Jae2OCSgKn3GdX8EszBxN34Z4=,tag:0SbDVvGLocD1JszBoNdZhA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:0yFDn06U,iv:HpjJ4BnNy27M5zjEBXNxe1OMWk9/d3F0HEYOBl1WoNg=,tag:ARFSLKCi11JpKfXV/RZDPg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:H3TvmZA=,iv:53jZ6fy5eFPfPbMjcR0Cpoxz3aEwCJp2QW/xBOlGxKc=,tag:xHgN12zW7wYP9dsRpSJGmw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:V/il16lzpalUPlc=,iv:Ta4SXTMtQjZl0FYYqTZEr5wVorFJ/49aL7J67VAUaXw=,tag:nERLyOf2SDGd7mAI6G8Tfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cndyqzwsajzxrhkj2l04hrnde90gj26klkl85emck3zc28fzlfys8cta9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dk1vMXp3VjZrZngwcDRv
            ZDNiR3VIbGN2THdYcHpzYTBmNTc0L1pKTEJ3CjMwb2FjdEtmRm1vYWlqSVNJRmFk
            S3JpaCtpUGJ0dE91Q1JoWHIrdDRZeUkKLS0tIGpyU2dxL2ZLamxEZFZ4cWM2QmZV
            R09Rb0pYYWhIV0dGM3RIUGtxYzJyQWsK99/0gUxcaWsx9Y3y+lTzryauMkpwuy6k
            uXGnHS7ABMvtRWdz9r+wy6ILmXmhHjGnETVR6aKZHcGlGwpRYilmNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T14:51:03Z"
    mac: ENC[AES256_GCM,data:fSl5dY1Y6tPTo/PTbJ/egpku8ey3bw6RHHPhRl1wuhWaOAyTExjfsSjQVoiedRYdzDHid0M5CgWuE3Mk+sUt/DyTwLYeKPXM2L9X49FZiB1CG49ivzg6Nu3a8GOF9bKjFoi/GNO3It5odyh5fYj7H6BAtIMuC4FS6D8az3uGkAs=,iv:AgNKepQyzLcnwMCv+rRilGe2MgqcrRfT6NQHmWs9mSs=,tag:WpYmkact6SJgnKBrUF/mig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: immich-server-env
    namespace: immich
data:
    TZ: ENC[AES256_GCM,data:zISMLV44i9enS4Oz,iv:+RPnCc0w/PXb8O2rHHS4+4a0GC19A1/VUi24q93tKpA=,tag:AjQYTRDTl9i0eE5cjfuTgw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:Ap6Bzuc=,iv:3bfmFybyMAA0mlK88Gk31fzVgel02LSwCuJ4LJdP5kY=,tag:TzcxIUyWco6a7et/1T6gvA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:9+yL3kNnGpoclaw=,iv:EzjCVamIUUxdI17g4e+7c02J+gmZemkLnLdkBBu6rMc=,tag:K2W7S7GPXxpnV6TsIQGVVA==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:7/S2d3mB,iv:rlb1rJR7KbIVQJHm/cjHaFCZ5s4WTyJ2g3k3/Jy5+8U=,tag:MIt35iQytX/VStjJbyCHFg==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:DfqqtK2IcbV7oLlsuZ4b,iv:R59jpG1uQXZ39UUBqz239yCmEd5kIDET7iU9Oqe4/bQ=,tag:pOtZQEZAdcpQFu6JyykPqA==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:aTdblrCAi/uUweKd,iv:YoDaoDOt9HpwWEWRiuovIdWjZiG6jR06I9vY87CjMeI=,tag:RpXQZeC5jJ+F6IcnVVNDlw==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:YPandw==,iv:WTTPCIHMW0hNOtC5uG1mFOPFIVqwtoby65lOWC02L8E=,tag:mGu5f3dFtDe9Bf98yvDQsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cndyqzwsajzxrhkj2l04hrnde90gj26klkl85emck3zc28fzlfys8cta9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dk1vMXp3VjZrZngwcDRv
            ZDNiR3VIbGN2THdYcHpzYTBmNTc0L1pKTEJ3CjMwb2FjdEtmRm1vYWlqSVNJRmFk
            S3JpaCtpUGJ0dE91Q1JoWHIrdDRZeUkKLS0tIGpyU2dxL2ZLamxEZFZ4cWM2QmZV
            R09Rb0pYYWhIV0dGM3RIUGtxYzJyQWsK99/0gUxcaWsx9Y3y+lTzryauMkpwuy6k
            uXGnHS7ABMvtRWdz9r+wy6ILmXmhHjGnETVR6aKZHcGlGwpRYilmNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T14:51:03Z"
    mac: ENC[AES256_GCM,data:fSl5dY1Y6tPTo/PTbJ/egpku8ey3bw6RHHPhRl1wuhWaOAyTExjfsSjQVoiedRYdzDHid0M5CgWuE3Mk+sUt/DyTwLYeKPXM2L9X49FZiB1CG49ivzg6Nu3a8GOF9bKjFoi/GNO3It5odyh5fYj7H6BAtIMuC4FS6D8az3uGkAs=,iv:AgNKepQyzLcnwMCv+rRilGe2MgqcrRfT6NQHmWs9mSs=,tag:WpYmkact6SJgnKBrUF/mig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
