apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-vijayakumar-xyz
  namespace: traefik
spec:
  secretName: home-vijayakumar-xyz-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: '*.home.vijayakumar.xyz'
  dnsNames:
    - 'home.vijayakumar.xyz'
    - '*.home.vijayakumar.xyz'
