---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name postgres-superuser
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    creationPolicy: Owner
    name: *name
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: |-
          {{ .root_user }}
        password: |-
          {{ .root_password }}
        cpo_password: |-
          {{ .vijay_password }}
  dataFrom:
    - extract:
        key: cloudnative-pg
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name wasabi-pgsql
  namespace: database
spec:
  secretStoreRef:
    name: bao
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: *name
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        wasabi_s3_access_key: |-
          {{ .wasabi_access_id }}
        wasabi_s3_secret_access_key: |-
          {{ .wasabi_access_key }}
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: cloudnative-pg
