apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
stringData:
    api_key: ENC[AES256_GCM,data:ieQ1ZJKGozbwwiZR2crl/UctPOU4Ixg8N/8FolXIi2w=,iv:DiGzu7xmKEkYvsBa3obIJ4v+84bpTIvHBPXPhr3mRjA=,tag:zKk1s2GGleEjqaDz9z1r3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUVc5cElsNnFBQnNpTzdu
            VzRSYWppN0hCL0VsUm9xdG8xT0NpLzdwdkNjCllPNlNXcmxQRGJrMElhcS80UGF6
            VC83Nkw1R2kvWUt2VitYRFMweUgvU2MKLS0tIGVQeEdLZk9OMHBZYXEweXVhWktR
            Y2lhVVMrQnZRakdyVnYxbVd1OGZVU0EKQ052iMDHjbn39WmSXX/72Opd2a1M9zrp
            aymzqahqNw//3EQJ2EHBxp1lelZMMCrDakyNYldDiSz+Wc9K58bXdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-03T17:41:02Z"
    mac: ENC[AES256_GCM,data:4vlxjg6tLhXnh9DqSYZYTMyVxwviO1plv0QLfJGOySx2odZiJrV9XZ+5Jh34icWRJNFRES7VWPWZie1EZILLUEEzFnr8mJ2sZlKCQAi3ZHGmOD/Q1oZLC/OxPl8V7fJrwUB3AE6M9mmlg5B2G76twOpIK27B8QM+41bI0cf02Z0=,iv:4W4jaK5f2prN9nidi11ix8gzfdnh+8BEk8e+5upd6C8=,tag:c7Q8M5RqUncT+82kaMihIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
