---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
spec:
  chartRef:
    kind: OCIRepository
    name: ceph-csi-drivers
    namespace: flux-system
  interval: 30m
  values:
    operatorConfig:
      namespace: storage
    drivers:
      cephfs:
        enabled: true
        name: storage.cephfs.csi.ceph.com
        clusterName: storage
        fsGroupPolicy: File
        snapshotPolicy: volumeSnapshot
        controllerPlugin:
          replicas: 2
          priorityClassName: system-cluster-critical
        nodePlugin:
          priorityClassName: system-node-critical
      nfs:
        enabled: false
      nvmeof:
        enabled: false
      rbd:
        enabled: true
        name: storage.rbd.csi.ceph.com
        clusterName: storage
        fsGroupPolicy: File
        snapshotPolicy: volumeSnapshot
        controllerPlugin:
          replicas: 2
          priorityClassName: system-cluster-critical
        nodePlugin:
          priorityClassName: system-node-critical
