---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      lldap:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65542
        containers:
          app:
            image:
              repository: ghcr.io/lldap/lldap
              tag: latest-alpine-rootless@sha256:9dbd74a880268ded85fa6596fabc8345f40fb5768d70ebb380a89fd2740a5bad
            envFrom:
              - secretRef:
                  name: lldap-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 20m
                memory: 250Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]
    service:
      web:
        controller: lldap
        ports:
          http:
            port: &port 17170
      lldap:
        controller: lldap
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.0.1.5
        ports:
          ldap:
            port: 3890

    route:
      app:
        hostnames:
          - lldap.${CLUSTER_DOMAIN}
        parentRefs:
          - name: envoy
            namespace: network
        rules:
          - backendRefs:
              - identifier: web
                port: *port

    persistence:
      data:
        type: emptyDir
