apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTEtWU0haK2NqMjR5K2ky
        Qkp5aktaSlZqQXYyVytSM2FnQXozYWIvUmtRCmhMS1VxQ1ZOaTV4emcwVkRBNFBI
        YmgrMnFKaHBmVW00RDgvY1JIUjhlWmsKLS0tIG9xQkIwSVJPTkFNNjVaanlOWGpt
        cFZoUmFZVjNMTHU3RkhJNjE1TkF5ck0K4CWU3xvtlz26FkRx8TfY0jsppqAXaHdK
        EU/LOu8UjW91x++nKoYatCcm+6aj61iQkmWB9nuDp22LdDFjrvNAJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T03:41:12Z"
  mac: ENC[AES256_GCM,data:QNUT8XYF1BGp97t3BAFhUxBoHy2XXWkkqVbSJL9A6p8JJL+4R2IHfTZVwGh0ShciuudUMp4gICrhGkZT/e+cnbW/qYHPzw2q6K9Z7eYy40PPNXBLPaG+qD4ZANUF/t8c+WiHqemm5HnuuzEDe05zRq++hhlz//qusH0tBST0J1c=,iv:LEouHzn3urLlm88fMyhP41mNAVYOFDBaLM0EHxOxf00=,tag:iVN8/8GjCaDsd7iP88A/9Q==,type:str]
  version: 3.12.2
stringData:
  BAO_ADDR: ENC[AES256_GCM,data:NOp8r9L6XsUOgIT8ys2JezYJRZKM,iv:1WrHTHzyMHHVlSzLgYpCVBZ3rBF2aIFi+AWh1a356m8=,tag:u1+ivK0GW67ctZ1f1vmC6w==,type:str]
  BAO_ROLE_ID: ENC[AES256_GCM,data:vJ31N1gp5uAZ4S5VioiAXmWRvY7sy95Alk2CkYtWRcoFGxCT,iv:3Z33s2+52fjm8hlyAvwgl3AY/SgcVEqNYmYh53eCLzI=,tag:Rd5juXbsvJhVCb7YPT0Dtg==,type:str]
  BAO_SERVER: ENC[AES256_GCM,data:cvegd7G18z1n9HGrSA==,iv:cFGLGDgah2oInuiVjUJnanWgJWXARID6OXUxPiM/UAY=,tag:AtJDMS+IBVFZS92UsOP0ug==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:bHfESudTzTfIyNZDFK4I,iv:ntLVrIfvOWz+fChaqAVP+rXQLu7HBnDB/pr04Y/+qeU=,tag:GkF3jCPOxGndmGUeAf1owQ==,type:str]
  CLUSTER_NAME: ENC[AES256_GCM,data:fACgXgU=,iv:g4i/b1VRPrEVzDTgv3jO/dJDneBrpzpbrIdyoA7XilM=,tag:vNxJplx7M0ixlBtP7pmpEQ==,type:str]
  EAB_KEY_ID: ENC[AES256_GCM,data:mpO0b5s5V/IXojk9URzLdtl2FZY3PA==,iv:oNL5ILBCaVVg2jD6RjN5tfQHdKOhkyD1khFW6LAbVYI=,tag:0rSlKFNkFds9HLIo1gggFg==,type:str]
  EMAIL: ENC[AES256_GCM,data:8FE0pkg8qDOS3caPLMQ2YLFx9sqCz30=,iv:quei5UKyeFVAau+rhIJtRItVQCg50RWZwhPNqlVL2OU=,tag:pgEKL5QmioYZIum5HZzBxQ==,type:str]
  LAB_DOMAIN: ENC[AES256_GCM,data:XhwEJE6sSfLx,iv:087zcEGee3xaSIz+GIexKfiPXPuFN7TfhxeMe95spD8=,tag:R8cT9gtrDOWGPrxP9z/yQg==,type:str]
  R2_ENDPOINT: ENC[AES256_GCM,data:AP0OvG66vjTb6mM+c5Ly+4YhDsF04vqaR67Y0Ct8fwRlnO0eviNdWfnL3JPeo8a0uAuzh1iBtYoUaSWtE1Yzypg=,iv:DmLjkw1KcAoi0t1sadAMnaHWHMAJLnvteyssWdFbmEw=,tag:2t+LesxBuVVY3flj0QTuaA==,type:str]
  TUPPR_REPLICAS: ENC[AES256_GCM,data:yQ==,iv:5dDvxqdd7KjKivwdtRtrP3YBPP4Z610y2WsF86xCVLQ=,tag:c0RI8ONqdBhDoa4tgddsuA==,type:str]
