apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    LE_EMAIL: ENC[AES256_GCM,data:FtqABJ40lMQpnRtxgf8g6R0Spnekehw=,iv:8aVMp8DRTxn9Tn7Ab7QcyHolgealqQBvoiLwy+XVEEk=,tag:l1Boeh29sNzYLkDe5Q7WSg==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:bHfESudTzTfIyNZDFK4I,iv:ntLVrIfvOWz+fChaqAVP+rXQLu7HBnDB/pr04Y/+qeU=,tag:GkF3jCPOxGndmGUeAf1owQ==,type:str]
    BAO_ADDR: ENC[AES256_GCM,data:NOp8r9L6XsUOgIT8ys2JezYJRZKM,iv:1WrHTHzyMHHVlSzLgYpCVBZ3rBF2aIFi+AWh1a356m8=,tag:u1+ivK0GW67ctZ1f1vmC6w==,type:str]
    BAO_ROLE_ID: ENC[AES256_GCM,data:TtzW39gA1iRH9T51VcBcQeQxMaZhXbbqHzp2uJRTcDvhsrb9,iv:IhQsTtiapNk6zF6IlOxfUCJEnZtnhebCD6mMOgYfkqw=,tag:zKri1TAXs5xGiaS6Kg+wxQ==,type:str]
    R2_ENDPOINT: ENC[AES256_GCM,data:AP0OvG66vjTb6mM+c5Ly+4YhDsF04vqaR67Y0Ct8fwRlnO0eviNdWfnL3JPeo8a0uAuzh1iBtYoUaSWtE1Yzypg=,iv:DmLjkw1KcAoi0t1sadAMnaHWHMAJLnvteyssWdFbmEw=,tag:2t+LesxBuVVY3flj0QTuaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTEtWU0haK2NqMjR5K2ky
            Qkp5aktaSlZqQXYyVytSM2FnQXozYWIvUmtRCmhMS1VxQ1ZOaTV4emcwVkRBNFBI
            YmgrMnFKaHBmVW00RDgvY1JIUjhlWmsKLS0tIG9xQkIwSVJPTkFNNjVaanlOWGpt
            cFZoUmFZVjNMTHU3RkhJNjE1TkF5ck0K4CWU3xvtlz26FkRx8TfY0jsppqAXaHdK
            EU/LOu8UjW91x++nKoYatCcm+6aj61iQkmWB9nuDp22LdDFjrvNAJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-11T06:54:43Z"
    mac: ENC[AES256_GCM,data:QD57dN3+v6O0eHNc6H7kBxRbpDFYRflmWCNNr8HIIlirdK8hIMsBqWyVHLHQfReHbGcQrkTqqJQoGBg9uwvjwt4ITQ1nX0FVWs2iHIJUk1r4tPVhvrGMbGYsGGQ5Q54mwTTCj23BTfLlke1Aw7i2CW9nlVquVQSgXRFAbKx/Myk=,iv:TUAYl9j/m3PVl/sy2c/DmbdOh+x/n5rces4BG30rOk0=,tag:QhrxR+YkuABZPTmra7yZUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
