---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #  # production
  - ./production/cluster-domain.yaml
# staging
# - ./issuers/letsencrypt-staging.yaml
# - ./staging/cluster-domain.yaml
