---
name: Deploy Fly.io Apps on Dependency Updates
on:
  push:
    paths: [fly.io/**]
    branches: [master]
jobs:
  deploy-fly-app:
    runs-on: ubuntu-latest
    # if: >
    #   github.event.commits[0].author.name == 'renovate[bot]' ||
    #   github.event.commits[0].author.email == 'bot@renovateapp.com'
    strategy:
      matrix:
        app: [flyguard, gatusfly, flyvault, flylink]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@1.5
      - name: Determine Modified Files
        id: changes
        run: |-
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')
          echo "MODIFIED_FILES=$MODIFIED_FILES" >> "$GITHUB_ENV"
          echo "Modified Files: $MODIFIED_FILES"
      - name: Deploy Fly.io App
        if: contains(env.MODIFIED_FILES, format('fly.io/{0}/', matrix.app))
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |-
          echo "Deploying ${{ matrix.app }} to Fly.io..."
          flyctl deploy --remote-only fly.io/${{ matrix.app }}/
          flyctl -a ${{ matrix.app }} machine start "$(flyctl -a ${{ matrix.app }} machine list -j | jq -r '.[] |  "\(.id)"')"
