---
dbs:
  - path: /data/db.sqlite3
    replicas:
      - type: s3
        access-key-id: ${CF_ACCESS_KEY}
        secret-access-key: ${CF_ACCESS_KEY_SECRET}
        bucket: ${LITESTREAM_BUCKET}
        path: ${LITESTREAM_PATH}
        endpoint: ${CF_R2_ENDPOINT}
        region: ${LITESTREAM_REGION}
        retention: 72h
        snapshot-interval: 12h
        validation-interval: 6h
