vaultwarden: /start.sh
caddy: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
backup: supercronic /crontab
cf_tunnel: cloudflared tunnel --no-autoupdate run --token "$CF_TOKEN"
tailscale-daemon: /usr/local/bin/tailscaled --port 41641 --state=mem: --tun=userspace-networking
tailscale: /usr/local/bin/tailscale up --accept-routes --advertise-exit-node --hostname=${FLY_APP_NAME} --advertise-tags=tag:fly-exit --advertise-routes=172.19.0.0/16 --authkey=${OAUTH_CLIENT_SECRET}?preauthorized=true && tail -f /dev/null
