---
- Dashboards:
    - cloudflare dash:
        - icon: https://dash.cloudflare.com/favicon.ico
          href: '{{HOMEPAGE_VAR_CLOUDFLAREDASH_URL}}'
    - Cloudflare zero trust:
        - icon: https://dash.cloudflare.com/favicon.ico
          href: '{{HOMEPAGE_VAR_CLOUDFLAREZERO_URL}}'
    - Fly.io dash:
        - icon: https://fly.io/phx/ui/images/favicon/favicon-595d1312b35dfe32838befdf8505515e.ico?vsn=d
          href: '{{HOMEPAGE_VAR_FLYIO_URL}}'
    - Render Dashboard:
        - icon: https://dashboard.render.com/favicon-dark.png
          href: '{{HOMEPAGE_VAR_RENDER_URL}}'
- Services:
    - Reddit:
        - icon: reddit.png
          href: https://reddit.com
    - Youtube:
        - icon: youtube.png
          href: https://youtube.com
    - Hastebin:
        - icon: https://d4.alternativeto.net/EDR07C2WpQ33nHPI6-sx2_t-DHAXlmWUbjq7dqKZ3rk/rs:fit:280:280:0/g:ce:0:0/exar:1/YWJzOi8vZGlzdC9pY29ucy9oYXN0ZWJpbl85MTA3My5wbmc.png
          href: https://bin.vijayakumar.xyz/
    - Onelink:
        - icon: https://dub.co/favicon-32x32.png
          href: '{{HOMEPAGE_VAR_ONELINK_URL}}'
