---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: recyclarr-secret
  namespace: media
  labels:
    encrypted-by: sops
    encryption-method: age
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:suKp3NmxZg5K6RaKWHEeV2GSzDLNDYYwcuR5Vs/hCKg=,iv:G6MgSAYRXZDSq6+bqd/sjd/2Z6JNkAaMMMWu4LDAbm8=,tag:jqcH0QgrZYZdtUEFflSELA==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:cfPT8pQmURWzn9l4TqykYn2KrGB9VhMCNuvE7GHenOs=,iv:biSnpKGirsBD/smuL5orfCvYLx+PWJv3c19a9K5En/Q=,tag:jqUMEiOfeSFQlYx2lWsHXQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xhw4tl54k0dpsx8gkk3vkd2g6l8wng5xpvfysqke6rknz40cpyjq3ljlt6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSmFLSS9FS3BXVjJkWkQr
        Y1FsU0Q2SUlzRzg5UHZTYUZJRnlsbk1KeERrCk5aaEh2amZoSmxleFBzYjAzZjkx
        MkRaNVNLbjFENDdYRXJ0c3NOcDg2WDAKLS0tIGk0WmJEZGRzb1RISjhlNVN0aEVo
        bzl4eHJLdSs4UU9hRXJlQU1kSlcva00KOe3hpZk7NdWoOqL9hR8Us4+jN+uNAFpV
        aF5Ep7YIAT1OGtooA291Q/JyfDZCjWyiPkFs3B/or5UerBQqonHUKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-12-26T09:50:03Z'
  mac: ENC[AES256_GCM,data:pgZwBpT+OIi2r6RoojAWmHK1xsWAuuSXTHPPREx7wovM+l8rF7fPVSUyyAlwP2J001d1wAxNnqU8xDtpubmXsbFx3Sn+yNTA7/ssXUP8swmnEisj41oIFTQwU0uXEd57+s91hjEkO2nEVvyB46A0sN5IcYJ/btvnwAP1P1QkIw4=,iv:2B2g6TP3bwYwQoPFTL25+lcvB3vxN2WIo3TrkAKvmSM=,tag:YJcYWvK+qWEatbXJEfjHDg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
